### ISSUE TITLE
Only show file name

### ISSUE THREAD

**Issue by arminta7** [brianpetro/obsidian-smart-connections#1]
Great plugin!

My request is to only show the filename in the list, rather than the entire path. Perhaps show the path upon hover?

**Comment by brianpetro** [comment]
Hi Sarah, thanks for the suggestion, and I made the update!

Details:

- Now, you can toggle the full path on/off in the configuration. The default is off.
- I added the "show full path on hover" feature to the links by adding the "title" attribute.
- There is still room for improvement regarding how the "section paths" are displayed, which are currently displayed like "#header1#header2#header3".

Here's the link to the latest commit for reference https://github.com/brianpetro/obsidian-smart-connections/commit/70ba601d0b38b9ecc98fb293507326c6589c7b38

Thanks for trying out the plugin :)
