### ISSUE TITLE
I can't seem to get Chat GPT to have access to my notes

### ISSUE THREAD

**Issue by Krysem** [brianpetro/obsidian-smart-connections#102]
As far as I can tell I've gotten the embeddings and smart connections pane to work as intended. But when it comes to Smart Chat, it doesn't seem to be able to answer any questions about the notes in my vault. I only get generic responses equivalent to asking the same prompts via Chat-GPTs web interface. 

Is there something obvious that I am missing in order to have the chat be able to search, analyze and understand the context of my notes?

**Comment by brianpetro** [comment]
Have you tried starting your questions with "Based on my notes..."?

**Comment by Krysem** [comment]
That definitely worked for accessing the notes! I guess I just need to include something along the lines of referencing the notes for any prompt given. Thank you!

**Comment by brianpetro** [comment]
@Krysem great to hear that it worked!

And yes, the "context lookup" is currently triggered by pronouns. You can see which ones in the language settings for Smart Connections. 

Sorry for the confusion!

Brian 🌴
