### ISSUE TITLE
FR - Ability to ignore frontmatter in visible search-results

### ISSUE THREAD

**Issue by abhuva** [brianpetro/obsidian-smart-connections#115]
I am using frontmatter in all my notes. The search-results allow you to get a quick peak at the note by showing the first couple lines. For me this is always frontmatter - and therefor gives no additional value.

If we could ignore (toggle) this frontmatter (only for the shown search-results) - this would improve the value of this option by showing actual content.

**Comment by brianpetro** [comment]
Hey @abhuva , great idea!

Thanks for making this FR,
Brian🌴

**Comment by brianpetro** [comment]
Frontmatter should now be excluded from Smart View search results since upgrading `v2.0`.
