### ISSUE TITLE
FR - include Canvas Files into embeddings/search

### ISSUE THREAD

**Issue by abhuva** [brianpetro/obsidian-smart-connections#119]
Currently,  *.canvas files dont get included in the search / embeddings.
While there has to be some post-processing on them to retrieve the actual text information without all the "noise", they are a increasingly big part of the obsidian ecosystem.

The ability to get them included in the search would be fantastic, else this context is completely invisible to this plugin.

It might also have the future benefit of beeing the core- / groundwork for providing the ability to generate canvas files by AI.

**Comment by brianpetro** [comment]
Completed in V2.0
