### ISSUE TITLE
Unrecognizable text in the top-right corner of Smart View

### ISSUE THREAD

**Issue by anki630** [brianpetro/obsidian-smart-connections#131]
recently encountered an issue with the Smart View feature. In the top-right corner of the Smart View, I noticed some text that is difficult to recognize.Some documents display the unrecognizable text, while others do not.

![截圖 2023-03-30 上午11 33 46](https://user-images.githubusercontent.com/7203595/228721855-ecc43ea9-112a-485d-9ae3-b425097fdc98.png)

**Comment by brianpetro** [comment]
Hi @anki630 , thanks for the report!

Can you provide me with one of the files that does this?

**Comment by brianpetro** [comment]
Is this still an issue? If so, please re-open 🌴

**Comment by brianpetro** [comment]
Recorded response https://youtu.be/J3j-2XRic8I
