### ISSUE TITLE
Input token is too large to create embeddings failed

### ISSUE THREAD

**Issue by 3dot141** [brianpetro/obsidian-smart-connections#133]
some files always failed.
i guess that the content is too large and beyond the limit for openai?
can you fix it?

**Comment by brianpetro** [comment]
Which language are your notes in? This is probably related to https://github.com/brianpetro/obsidian-smart-connections/issues/126#issue-1646765709

**Comment by 3dot141** [comment]
yes, i use chinese too.
I agree with his answer. Segmentation may cause the final result to be inconsistent with what was expected. So a more reasonable solution may be needed for this problem.

**Comment by brianpetro** [comment]
Thanks for the response. I'm closing this in favor of #126
