### ISSUE TITLE
FR - Support for Hugging Space embeddings & custom models

### ISSUE THREAD

**Issue by FrankCold** [brianpetro/obsidian-smart-connections#137]
Hello! Could you provide support for Hugging space embeddings? There are many other ways of doing embeddings, can you make it easier to integrate them?

Also a way to replace openai llm with locally hosted custom model calls would be great! (we just need a way to provide string with a response to your plugin)

I know it's a lot, but your plugin still rocks right now. If you would add above things it would be perefct for my use case.

Cheers!

**Comment by brianpetro** [comment]
@FrankCold Thank you so much for your feature request! I genuinely appreciate your interest in expanding support for additional platforms like Hugging Face. I understand how important these enhancements can be for users like yourself, and I'm excited about the potential they hold.

However, I'm currently juggling multiple priorities, and as much as I'd love to, I'm not able to immediately address all feature requests. That being said, I believe that the best way to accommodate these enhancements is by tapping into the amazing power of our open-source community. By encouraging community members to contribute the necessary changes, we can bring these features to life more quickly and efficiently.

This approach will also allow me to focus my time and energy on developing model-agnostic features, which I believe will have a broader impact on our user community, and maximize my contribution to the project. 

Please don't hesitate to reach out if you have any questions or need support in getting started with contributing. Your input is invaluable, and I'm always here to help guide you through the process. Together, we can make this plugin even better for everyone!

Brian🌴

**Comment by wwwebweber** [comment]
> 
Dear Brian
Thank you for your kind and thoughtful message. I’m glad to hear that you are interested in expanding support for additional platforms like Hugging Face. I agree that these enhancements would be very useful and beneficial for users like me.

I understand that you have multiple priorities and that you cannot address all feature requests immediately. I appreciate your honesty and transparency about this. I also respect your decision to delegate these enhancements to the open-source community. I think that’s a smart and efficient way to leverage the collective skills and talents of our community members.

I’m also impressed by your dedication to developing model-agnostic features, which I agree will have a broader impact on our user community. I admire your passion and vision for this project, and I’m grateful for your contribution.

Thank you again for your message and your support. Together, we can make this plugin even better for everyone!

**Comment by engr-lynx** [comment]
I'd be glad to contribute here to support Amazon Titan (and other models too) once Amazon Bedrock GAs.
Right now, my use of Smart Connections is limited to include only non-sensitive data (i.e. those I'm okay sending out to OpenAI). That'll change if this can use a model that won't use my data for training.

But so far, really cool plugin.

**Comment by bparlan** [comment]
I have no idea how to contribute and code this, but would love to help as much as I can to have a solution for any of oollama - gpt4all - lm studio integration to use local LLM within Obisidan notes at ease.

**Comment by mweber06** [comment]
Would this [repo](https://github.com/keldenl/gpt-llama.cpp) work? It should be an easy drop-in replacement for the GPT-4 API. As long as the OpenAI endpoints aren't hard-coded, anyone should be able to test this within a single afternoon.

**Comment by brianpetro** [comment]
@FrankCold @wwwebweber @engr-lynx @bparlan @mweber06 

Local embedding models are now available in `v2.0` 😊

Thanks for the feedback regarding the local chat models. I'm currently looking into local chat model support for `v2.1`. I aim to ship `v2.1` with the option to use "built-in" local models (i.e. no additional installation required besides activating Smart Connections). However, at the minimum, it will be possible to configure the Smart Chat to utilize models available over `localhost` using one of the aforementioned solutions.

Lastly, I'm closing this issue since several other issues/discussions on the local chat models exist.

Thanks again for your help in making Smart Connections the best it can be!

🌴

**Comment by bbecausereasonss** [comment]
Is there a way we can use the LM Studio API/Server mode for custom models?

**Comment by brianpetro** [comment]
@bbecausereasonss yes! The ability to configure a model running on `localhost` will come in v2.1

🌴
