### ISSUE TITLE
text_length_exceed

### ISSUE THREAD

**Issue by Mashiro-Yukino** [brianpetro/obsidian-smart-connections#138]
how to solve?

**Comment by brianpetro** [comment]
Which language are your notes in? This is probably related to https://github.com/brianpetro/obsidian-smart-connections/issues/126#issue-1646765709

**Comment by brianpetro** [comment]
Which language are your notes in that aren't English? 

Even if it's just one note, a note with non-english alphabet is likely causing your error.

**Comment by brianpetro** [comment]
It's possible.

**Comment by brianpetro** [comment]
See this https://github.com/brianpetro/obsidian-smart-connections/issues/126#issuecomment-1491887113 for a solution would fix it regardless of language. I'm closing this issue in favor of that FR.
