### ISSUE TITLE
FR "copy all messages" button

### ISSUE THREAD

**Issue by TrueVru** [brianpetro/obsidian-smart-connections#139]
I want to transfer the whole story in the chat to the obsidian note with a clear separation of the question and answer. how to do it?

**Comment by brianpetro** [comment]
There is a "copy" button that you can use to copy messages on at a time. 

However, I think a "copy all" button would be a good idea. So I'm going to update this issue to a feature request (FR) to add the copy all feature.

**Comment by brianpetro** [comment]
Closing because you can now open the chat history to have access to all of the message 🌴

**Comment by brianpetro** [comment]
Recorded response https://youtu.be/J3j-2XRic8I
