### ISSUE TITLE
FR: Exclude folder

### ISSUE THREAD

**Issue by arminta7** [brianpetro/obsidian-smart-connections#14]
It would be very helpful to have a setting to exclude various folders. The excluded file option doesn't really satisfy my needs.

**Comment by brianpetro** [comment]
Thanks for the suggestion. I'm going to update this shortly.

In the meantime, if you add a slash to the end of the folder name in the existing file exclusion configuration, that should work to exclude it as a folder.

**Comment by arminta7** [comment]
Great! The slash trick only works for the first item in the list. So if I have `Reviews/, Admin/` only Reviews is excluded.

**Comment by brianpetro** [comment]
I think you found a bug that occurs when there is a space after the comma. I'm fixing that, too.

**Comment by brianpetro** [comment]
Added the folder-specific exclusions config and fixed the whitespace bug with the last patch version.
