### ISSUE TITLE
Hope to add Chinese option in the settings

### ISSUE THREAD

**Issue by LiSir7** [brianpetro/obsidian-smart-connections#143]
This is a very good plugin. I hope to add Chinese option to the default language in the settings

**Comment by brianpetro** [comment]
Hi @LiSir7 , thanks for the request.

Please see https://github.com/brianpetro/obsidian-smart-connections/issues/126#issue-1646765709 for the latest update on supporting additional languages and follow-up there. 

Thanks,
Brian 🌴
