### ISSUE TITLE
FR: Disable/toggle headers completely

### ISSUE THREAD

**Issue by masonc15** [brianpetro/obsidian-smart-connections#15]
Hello, this plugin is amazing but it would be great if there was a way to completely block or hide headers from showing up in the Connections pane.  I know you can exclude them individually currently, but I would like to do it for all headers.  Thanks!

**Comment by brianpetro** [comment]
Hi @masonc15 

I will get to this soon because I think it may also be helpful in debugging issues like #13 

Thanks for your feedback!

**Comment by brianpetro** [comment]
I added this feature in `1.0.40`. It comes with a disclaimer, though. At this time, you will have to "Force Refresh" all embeddings if you want to re-enable connecting to specific sections in the future.
