### ISSUE TITLE
FR: Add support for local LLM to avoid sending data out

### ISSUE THREAD

**Issue by vguillet** [brianpetro/obsidian-smart-connections#152]
Hey, another idea I thought might be worth throwing in (though admittedly it could be a bit complex). I have been sharing around the news of smart-connections with a lot of my colleagues, and while most of them were very excited, few were actually able to use it as a lot of their vault's content is private company information. This was also much a regrets as a lot of them (me included) use obsidian for all the internal documentation. smart-connect could then effectively enable for a powerful AI integration with internal tools and workflows. 

As a potential solution I would suggest looking into [llama.cpp](https://github.com/ggerganov/llama.cpp) , which would possibly provide an effective local-first substitute for OpenAI's models. This would furthermore go in the direction of Obsidian's local first ethos which I believe is a key aspect of the platform.

Ideally having the ability to switch between the two would probably allow for the best of both worlds. 

Cheers!

**Comment by brianpetro** [comment]
Hi @vguillet , thanks for your continued support in providing feedback and sharing Smart Connections 😊

While I'd be happy to support efforts to contribute integrations like local models, I've decided that my personal focus for development should be on model-agnostic features. 

You can read more about my thoughts on this in https://github.com/brianpetro/obsidian-smart-connections/issues/137#issuecomment-1492775955

**Comment by brianpetro** [comment]
Closing as the local model configuration has been available since `v2.1` 🌴

**Comment by brianpetro** [comment]
Recorded response https://youtu.be/LiTr6Lqg6Fs
