### ISSUE TITLE
FR: Add a lock button for the search results of the Smart Connection files

### ISSUE THREAD

**Issue by wwjCMP** [brianpetro/obsidian-smart-connections#153]
Wish to add a lock button for the search results of the Smart Connection files. Now, it is bound to the currently opened file compulsively. Sometimes, it is very convenient for us to lock the search results of the Smart Connection files for checking them one by one.

**Comment by hewcaw** [comment]
I think we could use [Dynamic Code Block](https://github.com/brianpetro/obsidian-smart-connections#smart-view-dynamic-code-block) (blank content) to achieve this.

Related (or same) issue #46.

**Comment by brianpetro** [comment]
Closing in favor of #46 🌴

**Comment by brianpetro** [comment]
Recorded response https://youtu.be/VRslvjrcfnQ
