### ISSUE TITLE
Smart Connections dumps unhelpful error. 

### ISSUE THREAD

**Issue by clening** [brianpetro/obsidian-smart-connections#154]
It appears that any error I receive generally gets the following result: *API Error. See console logs for details.*

I have tested the API key and confirmed it works. What I am trying to understand is where SmartConnections console logs actually reside? I can't figure out any more details on the error, as the error message is not detailed at all.

**Comment by brianpetro** [comment]
Hi @clening 

To open the console, try `CTRL+SHIFT+I` or `F12`.

Then look for a tab named `console`. You should be able to find more details about errors here.

Let me know if that helps clear things up.

Thanks,
Brian 🌴

**Comment by clening** [comment]
Hey Brian -- didn't realize it was just the browser console. Duh. 

BTW, this is the error I receive most often (had a few other ones but those were more solvable). 

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at SmartConnectionsPlugin.request_embedding_from_input (plugin:smart-connections:1041:20)
    at ScSearchApi.search (plugin:smart-connections:2408:36)
    at SmartConnectionsChatView.get_context_hyde (plugin:smart-connections:3223:41)
    at async SmartConnectionsChatView.initialize_response (plugin:smart-connections:2904:23)
    
    Not sure if this is an error running up against token limits. If it is, you might find some of what I did here useful as a means to overcome this issue. https://codeberg.org/privacat/GPT3CaseParser/src/branch/main/caseparse.py 
    
    If I'm fundamentally misreading the error, well... that's a different story.

**Comment by brianpetro** [comment]
@clening thanks for the follow-up. 

Are any other errors appearing with this?

🌴

**Comment by brianpetro** [comment]
@clening also, if you could update to the latest version it will make it easier for me to debug because the line numbers will match up.

**Comment by clening** [comment]
Hi Brian: 

I have the latest version available via Obsidian (1.5.3). Is there a later version? 
Separately, I think I figured out the problem was a combination of ChatGPT downtime, and the fact that ChatGPT4 doesn't seem to work (despite me having a ChatGPT+ subscription). I reverted to 3.5 and seem to be getting results as expected. 

Thanks!

**Comment by brianpetro** [comment]
@clening great, yes, that's the latest. I had just made the update earlier today.

And yes, that would definitely cause the problem. The GPT-4 API is separate from the ChatGPT Plus subscription.

You can join the wait-list for GPT-4 at this link https://openai.com/waitlist/gpt-4-api

Sorry for the confusion, but glad you got it figured out!

Brian 🌴

**Comment by robinmcclellan** [comment]
I just installed Smart Connections and enjoying it so far. When I use GPT-4 I get this error:

Smart Connections API Error :: TypeError:
Cannot read properties of undefined (reading '0')

Doesn't happen with GPT-3.5. 

I have a ChatGPT-Plus subscription and when I test the API in Smart Connections settings, it's working. 

Based on the thread above, do I understand right that using GPT-4 in Smart Connections will not work until I get a new/separate API from the GPT-4 API Waitlist? 

Is there a way to use GPT-4 in Smart Connections now? Unfortunately GPT-3.5 isn't up to the tasks I need to do. 

Thank you!

**Comment by brianpetro** [comment]
@robinmcclellan That requires GPT-4 access via the API, which requires a separate wait-list and is not the same as the ChatGPT Plus access last time I checked.

**Comment by brianpetro** [comment]
That is correct. You will need to get the API access.

**Comment by robinmcclellan** [comment]
Ok thank you. I wonder if you could mention this in your documentation for other users - to say that GPT-Plus subscribers who are still on the waitlist will not be able to use GPT-4 in Smart Connections. 

If you develop other ways to use GPT-4 in Obsidian, I look forward to trying them!

For me, the difference between GPT-3.5 and 4 is night and day.

**Comment by brianpetro** [comment]
@robinmcclellan I have a ChatGPT plugin I'm working on, uses GPT-4 via ChatGPT, hope to release it soon.

Example: https://twitter.com/wfhbrian/status/1654515765633077249

**Comment by robinmcclellan** [comment]
Awesome - I'll keep an eye out for it!

**Comment by brianpetro** [comment]
Note: [Smart Connections GPT](https://chat.openai.com/g/g-SlDDp07bm-smart-connections-for-obsidian) is the successor to the aforementioned plugin. 

Closing this issue as likely fixed or outdated.
