### ISSUE TITLE
ctrl enter to send chat

### ISSUE THREAD

**Issue by yorrd** [brianpetro/obsidian-smart-connections#156]
as the title says, `ctrl + enter` to send a chat message would be amazing :)

**Comment by brianpetro** [comment]
Hi @yorrd 

I think there was some sort of conflict preventing `CTRL+ENTER` from working.

So instead, `SHIFT+ENTER` should work. Also, `TAB` then press `ENTER` should also work.

**Comment by yorrd** [comment]
understood. Feel free to close if the `ctrl + enter` is not something you're going to pursue. I'm used to `ctrl` so I didn't check and I wasn't aware of the alternative :)

**Comment by para-droid-ai** [comment]
Having some issues with this currently. Shift enter just tabs to the next paragraph. crtl enter doesn't do anything.
