### ISSUE TITLE
FR: Drag link into current note

### ISSUE THREAD

**Issue by arminta7** [brianpetro/obsidian-smart-connections#16]
Two parts:

1. Indicate link is clickable with a hand cursor or something.
2. Enable dragging a suggested note into the current note to add a link, or drag to a new pane/tab to open.

**Comment by brianpetro** [comment]
Hey @arminta7 

Regarding 1, which OS and theme are you using? Because the hand is already appearing for me on Windows using the "LYT Mode" theme.

And "dragging to add like to note" sounds like a great idea and should be especially useful when combined with #11 .

**Comment by arminta7** [comment]
I'm on MacOS Ventura 13.1 and using the default theme.

**Comment by brianpetro** [comment]
Thanks. I added the cursor pointer CSS, which should fix "1" on all themes (v. `1.0.41`).

Still looking into how to go about 2, though. If you see this drag-and-drop link functionality anywhere else, please let me know so I can check out how they did it.

**Comment by arminta7** [comment]
Awesome!

The Calendar and Recent Files plugins both have that functionality.

**Comment by brianpetro** [comment]
Added the same functionality as seen in the recent files plug-in.

Unfortunately, this only seems to work with the full files. I played around with it a bit, but I can't know for sure without getting to see the internals.
