### ISSUE TITLE
Fixed views from resetting their location between sessions

### ISSUE THREAD

**Issue by CrashVs** [brianpetro/obsidian-smart-connections#166]
Great plugin, one small thing has been bothering me.
I divide the right part of my screen for the plugins. Some are on top right and I like to keep the smart-connections button on the bottom right of my screen, but every time Obsidian is opened, the button resets to the top right. 

I don't know if this is a Obsidian problem or specific to this plugin. Thanks.

**Comment by brianpetro** [comment]
Can you send me a screenshot? I'm not sure what you mean. It sounds like you have a similar setup to me with the smart chat in the bottom right corner, and I keep the smart view in the top right:
![PXL_20230411_134539779](https://user-images.githubusercontent.com/1886014/231182951-8ec0f40b-b19a-4346-a654-044e957a8509.jpg)

**Comment by CrashVs** [comment]
Thanks for the reply. In fact, it is exactly the opposite. I keep the smart view on the bottom right and the smart chat on top right (see first figure below). But if I close Obsidian, when I open it again, the smart view goes back to top right (see second figure below) and I have to manually place the smart view button on the bottom again.
![image](https://user-images.githubusercontent.com/97754180/231224873-42b05f15-a80c-4934-b0c1-dc496c13e832.png)

![image](https://user-images.githubusercontent.com/97754180/231225263-0c6ed794-fd3b-47b6-a82e-2f861ffbda0e.png)

**Comment by beingskyler** [comment]
I have the same issue. It always resets itself and it always wants to open by default for some reason.

**Comment by martindkaz** [comment]
I am using the Workspaces plugin to solve this, although I haven't found a way to automatically change a Workspace layout when you launch Obsidian so I still have an extra step every time I open a vault.

**Comment by brianpetro** [comment]
I believe this is fixed in the latest versions. Please let me know if you're still having the issue 🌴

**Comment by brianpetro** [comment]
Recorded response https://youtu.be/VRslvjrcfnQ
