### ISSUE TITLE
[FR]: Use a "tab windows" instead of the panel for the chat view

### ISSUE THREAD

**Issue by Mara-Li** [brianpetro/obsidian-smart-connections#170]
I will prefer to have the option to open in "big" the chat view (in a tab), instead of the panel, by default. 

In fact, I think the smart view is too little in the panel, so I will love to have the option to open it directly in the tab. 

For the moment, I move the panel in the tab view, but when closed, I need to use the command that open it in the panel.

**Comment by brianpetro** [comment]
Recorded response https://youtu.be/VRslvjrcfnQ
