### ISSUE TITLE
Summarize excluded note

### ISSUE THREAD

**Issue by asmagen** [brianpetro/obsidian-smart-connections#171]
How come notes from excluded folders are being analyzed when calling them with [[]] in the prompt?

**Comment by brianpetro** [comment]
Hi, thanks for trying the plugin @asmagen 

Exclusions prevent embedding files. But if you specify a note in the chat then it loads the note into context without embedding the note.

This is the intended functionality. If you went through the trouble of excluding a note, then why would you specify it in the chat.

Closing but you can reopen if I misunderstood the issue.
