### ISSUE TITLE
Add included folders filter

### ISSUE THREAD

**Issue by asmagen** [brianpetro/obsidian-smart-connections#172]
Instead of exclusion some would definitely need to be retrictive and do the opposite by only including certain folders (so that any new folders will not be included automatically)

**Comment by jamie9090** [comment]
Love this, would get me using it

**Comment by brianpetro** [comment]
Closing in favor of https://github.com/brianpetro/obsidian-smart-connections/issues/121 🌴

**Comment by brianpetro** [comment]
Recorded response https://youtu.be/VRslvjrcfnQ
