### ISSUE TITLE
*API Error. See console logs for details.*

### ISSUE THREAD

**Issue by ThirvenGree** [brianpetro/obsidian-smart-connections#174]
How should this be resolved?

**Comment by doruksahin** [comment]
Did you add API key from settings?

**Comment by ThirvenGree** [comment]
I have added the api to the settings and it shows that the api is valid.
I can work with some documents but not others because of the rate limitation of the api?

**Comment by flyingparanoia** [comment]
I've encountered the same problem and the reason for this error message on my occasion is that the words of the note are too long.

My solution: slice the note into separate notes.

**Comment by R3dTeamN1nja** [comment]
Is there a way to fix this without slicing notes?

**Comment by ThirvenGree** [comment]
If the application for GPT-4 API is successful, it will provide a greater context limit to handle longer text segments

**Comment by sam1am** [comment]
![image](https://github.com/brianpetro/obsidian-smart-connections/assets/127555/1e520c5a-21e0-4946-8fa2-b780582eab17)

Yea, this is broken. If it is a longer note you get an API error. They should already be converted to vectors so a vector query against the note is what should be taking place. Instead I suspect it's just dumping the entire note into the prompt.

**Comment by brianpetro** [comment]
Closing this in favor of issues that specify the exact error which can be found in the developer console logs 🌴

**Comment by brianpetro** [comment]
Recorded response https://youtu.be/VRslvjrcfnQ
