### ISSUE TITLE
FR: capibility of syncing chat history with Obsidian sync

### ISSUE THREAD

**Issue by imrehg** [brianpetro/obsidian-smart-connections#175]
The chat history is not synced between devices currently, and that makes it a bit less convenient than it could be. Given how useful the plugin is, being able to take chats from device to device has a lot of value.

My guess is that the way the plugin saves the chat history locally at the moment is not very amenable to syncing, but just a hunch.

**Comment by brianpetro** [comment]
Chat history is syncable as of the latest versions. Additionally, the folder for chat history is also configurable 🌴

**Comment by brianpetro** [comment]
Recorded response https://youtu.be/CJyeSJ60eXk
