### ISSUE TITLE
error msg: "Error getting embeddings for some-note-title.md"

### ISSUE THREAD

**Issue by gw666** [brianpetro/obsidian-smart-connections#18]
error msg: "Error getting embeddings for some-note-title.md"

I think this error is being generated before all the vault's notes are initially processed. Any ideas on how to fix this? I can't wait to see what this plugin can do for me.

**Comment by lcl27** [comment]
Likewise, I am receiving the same error message. Tried disabling / re-enabling and uninstalling / re-installing and deleting the embeddings.json file along with opening different notes.

**Comment by brianpetro** [comment]
Does this keep happening with the same file? If so, there's a chance the file has something that the parser isn't handling correctly. It would help me to see the file, and you can email it to brian@plexm.com if you want to keep it private (but let me know when you send it on here so I don't miss it). 

And is the plugin working except for the reported file? Or is it not displaying anything at all? (ex. Always says "Making Smart Connections...")

@gw666 @lcl27  Thanks for your reports and helping me figure this out!

**Comment by lcl27** [comment]
@brianpetro for me the smart connection tab opens in the right hand tab and similarly reports the "error getting embeddings for 2. Fleeting Notes/2023-01-15.md" file (same for other files). On opening the inspect function, I can see lots of "retrying request in 1 second..." attempts followed by the below:

{
  "deleted_embeddings": 0,
  "exclusions_logs": {},
  "files": [],
  "new_embeddings": 44,
  "token_usage": 24448,
  "tokens_saved_by_cache": 0,
  "total_files": 182
}

**Comment by brianpetro** [comment]
@lcl27  Good news is that the "new embeddings" means that it's working for at least some notes. 

Can you send me one of the failing files?

**Comment by lcl27** [comment]
That's good to hear. Here attached is the failing file - nothing sensitive or long, I have copied the text below also for reference:

# 2023-01-15

- Gold
- Silver
- Commodities
- Macro investing

[2023-01-15.md](https://github.com/brianpetro/obsidian-smart-connections/files/10420730/2023-01-15.md)

**Comment by brianpetro** [comment]
@lcl27 that file worked for me, and I used the same folder name as reported in a prior log that you shared. I'll have to retrace the logic and think about this for a bit. Not sure what could be happening, but obviously there's a bug somewhere. Thanks for your help and patience with this!

**Comment by gw666** [comment]
I'll chime in with what I've observed:

* last night, I got "Error getting embeddings for some-note-title.md" for almost all files.
* Today (afternoon), most notes provided a (long) list of smart connections.
* Some notes signaled "Making smart connections". Some of these gave results in one minute or so; others never gave results (at least for as long as I waited).
* This is the most interesting case: When selecting a note, the result was "Error getting embeddings for some-note-title.md". Then, after a few minutes, the expected list of smart connections appeared (!)

Thank you!

**Comment by brianpetro** [comment]
@gw666 Thank you for the detailed observations!

It seems like a lot of what you experienced could be the plugin still "catching up" because of the rate-limiting of the OpenAI API.

I just released an update https://github.com/brianpetro/obsidian-smart-connections/issues/13#issuecomment-1383276783 that addresses this. It also creates a `failed_embeddings.txt` for managing previously failed files. Now, previously failed files will be skipped. This should allow the plugin to work, even with partially complete embeddings. And the failures can be retried manually from the settings.
