### ISSUE TITLE
Search on our highlight

### ISSUE THREAD

**Issue by dvl00** [brianpetro/obsidian-smart-connections#181]
Hi @brianpetro , 

I'm loving your plugin so far. It's really helpful for organizing my notes and finding relevant information. I have a suggestion for a possible feature that I think would make it even better. It would be nice if the plugin searched our other notes based on the text that we highlight. For example, if we bring in a news article and we highlight a quote we like, it would be nice if the plugin searched for other notes based on our highlight. This way, we could see how our notes relate to each other and discover new connections.

Again, thank you for your work on this plugin. It's awesome!

**Comment by brianpetro** [comment]
Closing because this is implemented in the latest versions.

Thanks for making the feature request 🌴

**Comment by brianpetro** [comment]
Recorded response https://youtu.be/Cr1jEftMuZM
