### ISSUE TITLE
Excluded folders with subfolder content not being excluded

### ISSUE THREAD

**Issue by TfTHacker** [brianpetro/obsidian-smart-connections#183]
### Discussed in https://github.com/brianpetro/obsidian-smart-connections/discussions/177

<sup>Originally posted by **TfTHacker** April 18, 2023</sup>
I used the folder_exclusions in settings, but while tracing the activity of the plugin I saw file contents from the exclusion folders being sent up. This is the value I gave to this field in settings:

00-Folders/10-TfT, 00-Folders/zArchive, Areas/Entities

So three folders and they all have subfolders with files. Should these be defined differently? 

Also, the path_only variable isn't clear to me what it's doing.

</div>

So it seems the exclusions are not working or somehow the UI input of the exclusions is not working or clear. Of course, the issue then is information that the user does not want to be sent to the OpenAI API, since it was marked for exclusion, is in effect being sent to the API. 

This could be considered as a serious privacy issue for plugin users.

Just to mention, I am doing this on the Mac platform.

**Comment by brianpetro** [comment]
`path_only` matches both file and folder. It should be better named and described, though. 

This link has some more notes on the settings https://github.com/brianpetro/obsidian-smart-connections#settings

**Comment by brianpetro** [comment]
@TfTHacker regarding the privacy concerns, you should see this https://twitter.com/TheRealAdamG/status/1649144739319488513?s=20

**Comment by AW2307** [comment]
I also need to exclude a folder contained in my vault. This doesn't seem to be working, as questions related to contents only found in that folder still get an answer.
What I did is to add the exact folder name to the paths_only field. Is that correct, or is the entire path needed? Any other reasons why it might not be working, or additional steps needed?
Thanks in advance for any input.

**Comment by brianpetro** [comment]
Closing as complete, please open a new issue if I missed something 🌴

**Comment by brianpetro** [comment]
Recorded response https://youtu.be/Cr1jEftMuZM
