### ISSUE TITLE
Does not seem to catalogue full text as embeding.

### ISSUE THREAD

**Issue by bbecausereasonss** [brianpetro/obsidian-smart-connections#187]
Is there away we can ensure a full text is catalogued as embedding? Right now i've got 3 years worth of weekly journal entries, but it's only capturing 1/2 a year. I'd like it to store the data in the embedding? 

Any plans to add langchain/pinecone?

**Comment by brianpetro** [comment]
Hi @bbecausereasonss 

Are you using a paid OpenAI account? Rate limits could be the issue.

If you are already using a paid account, what is the format of your journal entries? That would help debug. 

And no plans to implement either. If there are specific features from either of those companies that you'd like to see then please do add it to the issues section as a feature request. 

Thanks for trying the Smart Connections,
Brian 🌴

**Comment by bbecausereasonss** [comment]
Yep, using a paid account and don't believe I'm going over limits. My limit is $40 and I've barely passed $2

**Comment by brianpetro** [comment]
> If you are already using a paid account, what is the format of your journal entries? That would help debug

**Comment by bbecausereasonss** [comment]
I have tried a table and also just text as a format. March 2020 -> current date weekly updates.
