### ISSUE TITLE
configurable "block" definition

### ISSUE THREAD

**Issue by chs33** [brianpetro/obsidian-smart-connections#188]
As discussed [here](https://github.com/brianpetro/obsidian-smart-connections/discussions/186), right now, the block means heading section, and matching result are displayed in that manner. My notes are taken with a outliner manner, with each item in unordered list as a "block". Is it feasible to make that an configurable option?

**Comment by brianpetro** [comment]
The latest version implements this 😊🌴

**Comment by brianpetro** [comment]
Recorded response https://youtu.be/Cr1jEftMuZM
