### ISSUE TITLE
Suggestions on providing Chinese options or secondary development for plugin languages

### ISSUE THREAD

**Issue by xiaoyu-success** [brianpetro/obsidian-smart-connections#198]
Hi @brianpetro

Very happy to use such a great (๑•̀ㅂ•́)و✧ plugin in Obsidian.

I am a college student from China. May I ask if this plugin can be used for secondary development or can we provide a Chinese version for this plugin?

I am very looking forward to your reply, thank you!

**Comment by C63H88CoN14O14P** [comment]
I also wholeheartedly support this request. Enhancing support for multiple languages is advantageous for the upkeep and widespread adoption of plugins. And there are indeed many users in China who utilize obsidian.

**Comment by brianpetro** [comment]
Close this in favor of https://github.com/brianpetro/obsidian-smart-connections/issues/176 😊🌴

**Comment by brianpetro** [comment]
Recorded response https://youtu.be/Cr1jEftMuZM
