### ISSUE TITLE
API not working as expected even though it worked previously.

### ISSUE THREAD

**Issue by darylchc** [brianpetro/obsidian-smart-connections#199]
HI there, 

Smart Connections was working for me previously. All of a sudden today, i'm getting issues using it. I checked the API and now it says not working as expected. 

I've regenerated another API in OpenAI and it's still not working. 

Any help is greatly appreciated. 

Thanks,

Daryl

**Comment by darylchc** [comment]
hi there, I just realised that my $50 hard limit on OpenAI was reached. 
This leads to a new issue I don't understand? 

1. How was it possible that I've used $50 in less than an hour with about 10 queries I made on Smart Notes? 

2. Does Smart Connections (ie relevant note detection) from the plugin also count into the prompt? 

3. Does the amount of notes in my vault matter too? (I have approx 10k of notes)

Here's a screenshot of my usage in 15mins. 
![CleanShot 2023-05-07 at 15 58 41@2x](https://user-images.githubusercontent.com/22932429/236665497-d2be4777-5ab8-4752-ac4f-56f676c42ce9.png)

Would appreciate some guidance on this, and apologies for my naivety in this area. 

Thanks,

Daryl

**Comment by brianpetro** [comment]
@darylchc The usage you are showing equals only ~$4. Which is about average for 10K notes.

So I would check what else your spend is on.

**Comment by darylchc** [comment]
Hi Brian, thanks for replying.

I'm attaching here the [full usage](https://www.dropbox.com/s/6vldzi3uxvriv6y/Usage%20-%20OpenAI%20API%206May23.pdf?dl=0) as I was testing out Smart connections.

**Comment by brianpetro** [comment]
Thanks for the clarification @darylchc 

So for some reason, it seems like your whole vault is re-embedding periodically.

Can you check the `.smart-connections/embeddings-2.json` file?

What size is it? When was it last modified?

It's possible that your embeddings aren't being saved as intended.

**Comment by darylchc** [comment]
> 

I think you nailed it... there doesn't seem to be the file .smart-connections/embeddings-2.json saved anywhere in my vault nor in my computer...

- how do I make sure the file .smart-connections/embeddings-2.json is created? 


Context: My vault is saved in iCloud (i'm on a mac). I know you mentioned somewhere not the save the json file in the cloud, but I couldn't even locate that file.

Thanks so much for your help.

Daryl

**Comment by brianpetro** [comment]
This is the best advice I have right now https://github.com/brianpetro/obsidian-smart-connections/issues/123#issuecomment-1491844459

That, and also possibly excluding large folders.

You can review that thread to better understand the problem. But basically your vault may just be too large for the current system.

**Comment by darylchc** [comment]
Big thanks Brian. 

I'm looking through [#123 Comment](https://github.com/brianpetro/obsidian-smart-connections/issues/123#issuecomment-1491844459)

I don't seem to have a smart connections folder created. If I were to give this another go, 
1. How do i creat a smart connections folder, and 
2. ensure that I've created a .smart-connections/embeddings-2.json 

I'd probably try smart connections with a subfolder in my vault to re-kick it off (and limit my hard limit on OpenAI). 

Thanks so much, 

Daryl

**Comment by brianpetro** [comment]
> I don't seem to have a smart connections folder created. If I were to give this another go

Did you check using your normal file explorer? You may also have to "show hidden files" to see it.

**Comment by darylchc** [comment]
Thanks Brian. I've located the embeddings-2 file in my native Finder on Mac. 

![CleanShot 2023-05-10 at 22 18 25@2x](https://github.com/brianpetro/obsidian-smart-connections/assets/22932429/df001bac-1899-4293-b665-ae42c50eb25b)


In GitHub you said, 
> "The embeddings.json file can get to be quite large, so it is recommended that you exclude the folder from your sync settings." 

I'm using iCloud to store my obsidian notes. do you mean to exclude it from iCloud sync? Or do you mean to exclude it from the sync in smart connections? if the latter, do you mean simply keying in here? 

<img width="703" alt="CleanShot 2023-05-10 at 22 22 10@2x" src="https://github.com/brianpetro/obsidian-smart-connections/assets/22932429/1cba9572-8aac-4ee6-a69a-6679a5ec7ed0">


Really appreciate the back and forth. I do apologise, as I'm not a developer.

**Comment by brianpetro** [comment]
The exclusion in the second screenshot is for the plugin. However, you'll need to find the exclusion settings specific to iCloud. I recommend searching for other similar issues, where I believe this has been discussed with suggestions for how to exclude.

However, exclusion may no longer be necessary since the latest versions no longer use a single embedding file 😊🌴

**Comment by brianpetro** [comment]
Recorded response https://youtu.be/Cr1jEftMuZM
