### ISSUE TITLE
Jump to header section

### ISSUE THREAD

**Issue by arminta7** [brianpetro/obsidian-smart-connections#2]
Loving the plugin so far!

It would be great if, when I click on a result in the side pane, I'm taken to the relevant header section in the related page and the header is highlighted. Right now it just starts at the top of the page.

**Comment by brianpetro** [comment]
This is also how I imagined it working. But I couldn't find any clear way to do it.

I know the Dataview plugin does this, but I haven't been able to figure out how by looking at their code.

Do you know of other plugins that do this that I can look at as an example?

Thanks!

**Comment by arminta7** [comment]
I don't know of any, but the Discord might be able to point you in the right direction!

**Comment by brianpetro** [comment]
I'll check that out. Which discord? Can you give me a link? Thanks!

**Comment by arminta7** [comment]
https://obsidian.md/community  discord link is there. #plugin-dev might be a good place to start.

**Comment by brianpetro** [comment]
Links now open to the relevant heading.
