### ISSUE TITLE
Empty embeddings.json

### ISSUE THREAD

**Issue by callumalpass** [brianpetro/obsidian-smart-connections#20]
Hi,

This is an amazing plugin!
I've been having a small problem in that my `embeddings.json` file remains empty, even after the connections have been made and are displayed in Obsidian. This means that the connections are remade each time I open up Obsidian. 

I'm getting the following error, as well as a couple of failed embeddings, but I'm not sure this is related:

```
Error: net::ERR_FAILED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:101:7169)
    at SimpleURLLoaderWrapper.emit (node:events:390:28)

```
The failed embeddings are being written to the `failed-embeddings.txt`. The `embeddings.json` file however contains only a pair of curly brackets. A force refresh makes a new embeddings file, with a time stamp, but this too remains empty.

Thanks!

**Comment by brianpetro** [comment]
I have in place multiple safeguards to prevent the loss of the embeddings, which should have stopped something like this.

Do you have any file syncing that might be interfering?

Have you seen any errors in the console log?

Thanks for reporting this issue and helping improve Smart Connections!

**Comment by callumalpass** [comment]
It does seem strange! I haven't got any file syncing going on, except for git, and there aren't any errors appearing in the console log. I have been monitoring the embeddings file, and it doesn't seem to be updated with information at any point. It is created, and then remains empty (with only the curly braces), so I don't think it is being overwritten by an external process. 

For what it's worth, I'm running this on linux in a Flatpak install of Obsidian.

Would there be any way of trying to trigger the save embeddings function from within the console?

**Comment by brianpetro** [comment]
> Would there be any way of trying to trigger the save embeddings function from within the console?

In theory, yes. Did you want this for testing? I can look into getting you the code.

Would you be interested in a cloud hosted solution for the embeddings? It's something I've been considering. 

Thanks for your help!

**Comment by callumalpass** [comment]
I think that could be helpful for testing. After the most recent update, I've now got the `embeddings-2.json` file, but this is also remaining empty. 
I think a cloud hosted solution could be interesting, but I also do like the idea of the local solution. If a cloud hosting would be more resilient, though, then I guess that would make sense!
Thanks!

**Comment by callumalpass** [comment]
Hi. I just wanted to let you know that the embeddings file now has data in it. I'm not sure what led to it being saved.

 
Thanks for all your help!

**Comment by brianpetro** [comment]
@callumalpass sometimes the best action is to wait! Thanks for the update 😊
