### ISSUE TITLE
LOVING this so far but one issue.

### ISSUE THREAD

**Issue by bbecausereasonss** [brianpetro/obsidian-smart-connections#202]
Absolutely LOVE this plugin. However, one issue I am having is that there is no vector/memory on the actual GPT interactions about my notes/folders, so outside of a few 'continue' prompts, it loses memory/context completely, requiring me to [ do a re-prompt... Or if I try and continue the conversation in the chat window to ask another question it assumes I'm speaking about some random note.

Would be amazing to be able to have context/memory in our conversation regarding a specific note(s). Is that possible?

**Comment by brianpetro** [comment]
Hey @bbecausereasonss 

Thanks for trying out Smart Connections.

I haven't mentioned this yet, but I think the next evolution of Smart Chat is going to be a [ChatGPT plugin](https://twitter.com/wfhbrian/status/1654515765633077249?s=20). 

For:

> continue the conversation in the chat window to ask another question

The plugin works well out of the box.

Though, I'm still figuring out how the plugin will fit into the larger ecosystem, but that's the direction I'm leaning for Smart Chat since I feel like I'd be reinventing the wheel otherwise.

From there, there's definitely room for additional cool features like aggregating chat history relative to individual notes, which I think is what you might mean by:

> Would be amazing to be able to have context/memory in our conversation regarding a specific note(s). Is that possible?

Thanks for the feedback
Brian 🌴

**Comment by bbecausereasonss** [comment]
Interesting, as a ChatGPT plugin though you'd be working int he chat-gpt interface which would take you out of Obsidian. I think that could break the UX and chain-of-thought, is there a way to stay within Obsidian?

**Comment by brianpetro** [comment]
@bbecausereasonss I use ChatGPT in the sidebar just like the Smart Chat feature. I also use a custom desktop app that better integrates [ChatGPT with my desktop](https://SmartPrompts.app).

And I also use it in the browser.

I haven't found myself really preferring any of the locations when it comes to using it with my notes. The reason might be that the usage becomes more like a background job than something I'm actively participating in. For example, I could say "manage my inbox" then go and do something else while it completes the process.

Brian 🌴

**Comment by bbecausereasonss** [comment]
Would you be able to continue to use a ChatGPT plugin in the side-bar of Obsidian?

**Comment by brianpetro** [comment]
@bbecausereasonss is this what you mean?
![PXL_20230510_134153547](https://github.com/brianpetro/obsidian-smart-connections/assets/1886014/ecdcfab5-db80-42e0-8588-f38a71bf2019)

**Comment by bbecausereasonss** [comment]
Yea, interesting. So as a plugin it would somehow plug into your personal local obsidian notes/vectors? I guess I find that kind of confusing. Anyway, looking forward to seeing the developments :)

**Comment by brianpetro** [comment]
![image](https://github.com/brianpetro/obsidian-smart-connections/assets/1886014/e3af5451-3014-454d-817f-fea90d67728d)

Chat history may be used for embeddings, this is excluded by default, but can be removed from exclusions in the settings. And the above screenshot shows the new ChatGPT view provided by Smart Connections 😊🌴

**Comment by brianpetro** [comment]
recorded response https://youtu.be/ORbmZgmfjKw
