### ISSUE TITLE
Link in smart connections panel doesn't work

### ISSUE THREAD

**Issue by gw666** [brianpetro/obsidian-smart-connections#21]
See the attached two images. The first one ("benefits" in title) has multiple smart connections. Look at the top one ("practicing gratitude...") The text of this note is the second image, labeled "practicing".

Clicking this link does not cause the "practicing" note to appear.

Here are some things I find of interest.

1) The "gratitude" note has a tag, "#c001", at the bottoom
2) The top smart connection in "benefits" has text in two sizes; the larger size begins with ">>c001"
3) Could the "#" changing to a ">>" be relevant to the fact that clicking the smart connection link does *not* result in the "practicing" being displayed?
4) Now that I think about it, should the ">>c001 *key* quote re. gratitude...circuits" be showing up? After all, it's part of the *text* of the note, not its title.

Thanks for your help.

PS: In the next few days, I'll be sending you an email with some ideas. My name is Gregg Williams.

<img width="603" alt="practicing  note; the target of the top link in  benefits  note" src="https://user-images.githubusercontent.com/227650/213101117-7b1efd9a-c43e-4e6c-abd0-e65d17df7628.png">
<img width="851" alt="benefits  note; see also the top link in right-hand column" src="https://user-images.githubusercontent.com/227650/213101120-a771c3ce-2762-4db5-9923-16b3a50d16c6.png">

**Comment by brianpetro** [comment]
> See the attached two images. The first one ("benefits" in title) has multiple smart connections. Look at the top one ("practicing gratitude...") The text of this note is the second image, labeled "practicing".
> 
> Clicking this link does not cause the "practicing" note to appear.

Are there any links in the Console log after clicking this link? Based on "c001" observation, this issue may also have something to do with the interpreter misreading the line as a heading. 

> Could the "#" changing to a ">>" be relevant to the fact that clicking the smart connection link does not result in the "practicing" being displayed?

This is possible. 

> Now that I think about it, should the ">>c001 key quote re. gratitude...circuits" be showing up? After all, it's part of the text of the note, not its title.

The reason that text is showing up is that Smart Connections is interpreting that line as a heading. If it's not formatted as a heading, then I'd be interested in getting access to that file to debug why it's being interpreted as one.

---

After re-reading the above, this may be explained by the interpreter reading a line that starts with a tag the same as if it were a headline. I am making a note to test this.

**Comment by gw666** [comment]
> Are there any links in the Console log after clicking this link? Based on "c001" observation, this issue may also have something to do with the interpreter misreading the line as a heading.

Brian, I've attached the "practicing" note; I dragged it from a Finder window, so it should not contain any flaws.

In the Console program, in both the Log Reports folder and the system.log fiile, I couldn't find anything relevant. Thanks.

[202205131124 practicing gratitude strengthens neural circuits.md](https://github.com/brianpetro/obsidian-smart-connections/files/10453242/202205131124.practicing.gratitude.strengthens.neural.circuits.md)

**Comment by brianpetro** [comment]
@gw666 I tried to address this in the latest update. 

It was a big update on the internals, so I didn't get a chance to test this case. But I did add the logic that should fix it.

Let me know if it works as expected. If not I'll go back and test with file above. 

Thanks for your help with this!

**Comment by gw666** [comment]
Unfortunately, I'm still getting errors (I updated the plugin around 10:10PM Pacific time); see the attached image.

Note the second and fourth links, which are smaller and don't work.

Again, the link shows ">>" where, in the original it shows "#" as marking what comes next as a link. In the fourth link, the filename is "201904081129 outline for #bba01-conversations (4-8-19).1.1.md". On the link, it's shown as ">>bba01...".

Would it help if I sent you my Obsidian workspace? I don't mind because there's nothing personal in it.

<img width="789" alt="second and fourth links (in smaller type) don't work" src="https://user-images.githubusercontent.com/227650/213630968-3924a664-0ce5-4d15-b80e-a624dbda384f.png">

**Comment by brianpetro** [comment]
@gw666 Thanks for following up about this. I'm curious about what's causing this. 

> Would it help if I sent you my Obsidian workspace? I don't mind because there's nothing personal in it.

Yes, that would be helpful. Please send it to brian@plexm.com and ping me here when you do.

**Comment by gw666** [comment]
Hi Brian,

I'm attaching a copy of my current work file (minus some graphics, to get the resulting zip file to be under the 10 MB limit for emailing). The file I used as an example is "202301160843 learning from what goes right, not from what goes wrong". Good luck!

Gregg Williams
408-207-5652; feel free to call

**Comment by brianpetro** [comment]
@gw666 

I didn't find the zip anywhere. Did you send it directly to my email? Or as reply to the GitHub email?

You might need to host it in Google drive and give me a link, Gmail seems to have been being extra strict recently in preventing sending files.

**Comment by gw666** [comment]
@brianpetro 

I just emailed the file to your personal email address.

**Comment by brianpetro** [comment]
@gw666 still not seeing it :/

**Comment by gw666** [comment]
Bummer. Well, this should work.

[GW-thinking-box ARCHIVE 1:21:23.zip](https://github.com/brianpetro/obsidian-smart-connections/files/10472784/GW-thinking-box.ARCHIVE.1.21.23.zip)

**Comment by brianpetro** [comment]
@gw666 The fix is now available in version `1.1.4`. Thanks for your help!
