### ISSUE TITLE
Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by Zeina01** [brianpetro/obsidian-smart-connections#216]
After installing the Smart Connections plugin, I am experiencing difficulties getting it to work correctly. Whenever I try to use the plugin, I encounter the following error message in the console:

plugin:smart-connections:1083 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at SmartConnectionsPlugin.request_embedding_from_input (plugin:smart-connections:1083:20)
    at ScSearchApi.search (plugin:smart-connections:2488:36)
    at SmartConnectionsChatView.get_context_hyde (plugin:smart-connections:3337:41)
    at async SmartConnectionsChatView.initialize_response (plugin:smart-connections:3005:23)

I have taken a few steps to troubleshoot the issue, including updating the plugin to the latest version and restarting Obsidian. However, more measures were needed to resolve the problem.

**Comment by nzervoudis** [comment]
I'm having a similar issue every time I try to use the chat feature :(
![image](https://github.com/brianpetro/obsidian-smart-connections/assets/7318361/967bbe81-b84f-4990-9f8d-8dcfe3cccde1)

**Comment by brianpetro** [comment]
Is this the same https://github.com/brianpetro/obsidian-smart-connections/issues/217#issue-1719358779 

🌴

**Comment by brianpetro** [comment]
Closing this issue as likely fixed or outdated.
