### ISSUE TITLE
API Error message

### ISSUE THREAD

**Issue by remsho** [brianpetro/obsidian-smart-connections#217]
I'm trying to use the Smart Connections, but I keep getting this message when I run it. Can you please explain how to fix it?

"Smart Connections API Error :: TypeError: Cannot read properties of undefined (reading '0')

Sorry if the answer is simple. I'm not very tech-savvy.

**Comment by nzervoudis** [comment]
I'm getting the same error, not sure what's causing it.

**Comment by nzervoudis** [comment]
I was getting the same issue. I changed the Chat model from gpt-4 to gpt-3.5 and it seems to work now. I guess it was because I don't have GPT-4 API access?

**Comment by tehnetaholic** [comment]
same for me, works with 3.5, doesnt work with 4
would be happy to provide more info if you tell me how

**Comment by remsho** [comment]
I received the same message even when trying it in ChatGPT 3.5 (although I do have GPT 4 access). 
Also, when I tried testing the API key in settings, I got the message "API key not working as expected." So maybe that's connected to the problem.

**Comment by tehnetaholic** [comment]
From what I read having access to ChatGPT through API is not the same thing as having it available on https://chat.openai.com/
You gotta join the waitlist https://openai.com/waitlist/gpt-4-api

**Comment by remsho** [comment]
I subscribe. But in any case, I couldn't get the plugin to work either way.

**Comment by remsho** [comment]
Last time I opened the app, the window "Hi, I'm ChatGPT with access to your notes, etc." appeared. When I asked it a question, however, I received the message "API error. See console logs for details." Below is the log. The "status of 429" means that I've made too many requests of the API, but this message shows up even the first time I try using the plugin. I'm not aware that I am using the API anywhere else. I would appreciate help. Thank you.

Loading Smart Connections plugin
plugin:longform:35569 [Longform] Loaded and watching projects. Found 0 drafts in 0.023s.
2plugin:smart-connections:2446 loading external embeddings
api.openai.com/v1/chat/completions:1          Failed to load resource: the server responded with a status of 429 ()
plugin:smart-connections:3243 CustomEvent
eval @ plugin:smart-connections:3243
plugin:smart-connections:3283 Uncaught (in promise) CustomEvent

**Comment by brianpetro** [comment]
See this https://github.com/brianpetro/obsidian-smart-connections/issues/225#issuecomment-1567441530

**Comment by remsho** [comment]
I understand that. But there is an option to purchase tokens for 3.5 or 4. Is one of them preferable for the plugin?

**Comment by remsho** [comment]
Problem solved. I had run out of tokens. Thank you.

**Comment by bbecausereasonss** [comment]
Hmm. I just started receiving this error even though I'm using my own API key (never had any issue before)

*API Error. See console logs for details.*

**Comment by brianpetro** [comment]
That's most frequently an "exceeds token limit" issue.

Is it happening every time? Or only on some requests?

Could you please screenshot the developer console when this happens?

Thanks for reporting this,
Brian 🌴

**Comment by bbecausereasonss** [comment]
Every single time now...  cant seem to figure out how to open the dev console :/

**Comment by brianpetro** [comment]
@bbecausereasonss 
On windows: CTRL+SHIFT+I
On mac: Click the "View" dropdown in the top menu bar and then click "Toggle Developer Tools"

**Comment by bbecausereasonss** [comment]
> @bbecausereasonss On windows: CTRL+SHIFT+I On mac: Click the "View" dropdown in the top menu bar and then click "Toggle Developer Tools"

Gotcha, likely related to this... Is 6k Tokens a hard limit?

ax_total_tokens 6000
plugin:smart-connections:2636 curr_token_est 6643
plugin:smart-connections:2638 max_available_tokens -643

**Comment by brianpetro** [comment]
@bbecausereasonss, that's definitely it. 

Can you make sure the plugin is updated to the latest version? The estimated token calculations were more problematic in earlier versions.

If you are on an earlier version and update, that should fix it.

Please let me know either way.

Thanks,
Brian 🌴

**Comment by bbecausereasonss** [comment]
So I'm getting this error again on documents which I was able to speak to in prior versions.

['[[Snippet - Business -100 Million Dollar Offers - Alex Hormozi]]']
plugin:smart-connections:2639 chat_ml (2) [{…}, {…}]
plugin:smart-connections:2641 max_total_tokens 6000
plugin:smart-connections:2643 curr_token_est 7914
plugin:smart-connections:2645 max_available_tokens -1914

**Comment by brianpetro** [comment]
@bbecausereasonss 

> Can you make sure the plugin is updated to the latest version? The estimated token calculations were more problematic in earlier versions.

**Comment by bbecausereasonss** [comment]
Yep it is, I keep it up to date.

**Comment by brianpetro** [comment]
@bbecausereasonss hold tight. I have a fix coming!

Thanks
🌴

**Comment by brianpetro** [comment]
@bbecausereasonss the latest update, `1.6.34`, contains a fix that prevents the `max_tokens` parameter from going negative. I think this should do the trick.

In short, I use very conservative token estimate calculations, and this caused the `max_tokens` to go negative in cases where a larger note used up "all available" context. However, due to the conservative calculation, there are usually still tokens available so I set the minimum `max_tokens` to 200.

Thanks for your help in solving this,
Brian 🌴

**Comment by bbecausereasonss** [comment]
Great, will test. Thanks for turning this around so quickly.

**Comment by irasanchez** [comment]
> I subscribe. But in any case, I couldn't get the plugin to work either way.

Unfortunately, I thought subscribing meant GPT-4 **API** access, but it only grants access through the OpenAI site and playground.

**Comment by brianpetro** [comment]
Closing this issue as likely fixed or outdated.
