### ISSUE TITLE
[Feature Request] Make refreshing connections smoother

### ISSUE THREAD

**Issue by yan42685** [brianpetro/obsidian-smart-connections#220]
Current behavior of refreshing connections is a bit annoying with a flash between two result pages, I've changed some code to make it smoother and will submit a PR after the previous one if you are interested in it. 
before:
![before](https://github.com/brianpetro/obsidian-smart-connections/assets/41834091/6bf9e0e8-243e-4777-a720-67ef53ae368e)
after:
![after](https://github.com/brianpetro/obsidian-smart-connections/assets/41834091/5d9c8d73-c883-494f-8413-7c2d7b791bd6)

**Comment by yan42685** [comment]
![image](https://github.com/brianpetro/obsidian-smart-connections/assets/41834091/c1215a6b-478f-4b41-8e03-37d69a26ecab)
This will still provide a prompt if the refresh time is too long.

**Comment by brianpetro** [comment]
@yan42685 PR would be helpful.

Thanks for the contribution 😊

🌴
