### ISSUE TITLE
Error getting embeddings

### ISSUE THREAD

**Issue by gregoirealvarez777** [brianpetro/obsidian-smart-connections#221]
Hello everyone,

I tried to install the smart connections plugin which seems to be amazing, but I always receive an error message saying "Error getting embeddings for:" and the name of the note...
<img width="386" alt="Capture d’écran 2023-05-24 à 15 16 16" src="https://github.com/brianpetro/obsidian-smart-connections/assets/31627259/9841532f-3af9-422f-8e70-454f67436bfd">

Even for my API, obsidian is telling me that API is not working as expected...

Do someone have an idea of what could make this problem ?

Thank you in advance for your help
Greg

**Comment by RiciTrisnaP** [comment]
I get this error too, I beg someone to help please

**Comment by Tylia-rt** [comment]
Same here, and when i look at the console log : 

![Capture](https://github.com/brianpetro/obsidian-smart-connections/assets/103041503/b9109729-a001-4f24-84e0-1525eb81a072)

**Comment by brianpetro** [comment]
Could be this https://github.com/brianpetro/obsidian-smart-connections/issues/225#issuecomment-1567441530

**Comment by brianpetro** [comment]
[Recorded response](https://youtu.be/yNjkPY_FGA8): 429 error code from OpenAI indicates issues with the account connected to the API key. Ensuring that the account has prepaid API credits should resolve these issues.
