### ISSUE TITLE
Embeddings.json dissappeared...

### ISSUE THREAD

**Issue by bbecausereasonss** [brianpetro/obsidian-smart-connections#222]
Was working today, I didn't touch anything. Come back and it's telling me it can't find the embeddings.json and warning me that it will have to re-catalogue my entire file-system....

Also tried running an undelete, a file could not be found. I'm confused.

Where is the embeddings.json stored usually? Why did it disappear? 

FYI Cost me $20 bucks to re-embed my DB :/

**Comment by bbecausereasonss** [comment]
Also, is a file with 53k words too big? All of a sudden it's not making embeddings... for that specific file. Won't throw an error, and the connections tab just mentions the filename.md

**Comment by bbecausereasonss** [comment]
Wow. Just spent 20 bucks reindeding new connections in like 2 seconds... Ugh... Facepalm

**Comment by bbecausereasonss** [comment]
@brianpetro Can you please let me know where the embeddings.json is stored so I can manually back it up, it to prevent this from hapepning again? Thank you!

**Comment by brianpetro** [comment]
@bbecausereasonss 
`.smart-connections/embeddings-2.json`

**Comment by brianpetro** [comment]
[Recorded response](https://youtu.be/1yuGv9MgNQ4)
