### ISSUE TITLE
Request to consider support for API2D

### ISSUE THREAD

**Issue by wujigge** [brianpetro/obsidian-smart-connections#224]
Hello author!

First of all, I'm not a programmer, so my statement may not be very scientific!
I like your plug-in very much, please provide support for API2D. This is the website of API2D, which contains the introduction of API2D.
Simply put, it is a third party switching substitute for the official API, as my country does not have smooth access to chatgpt, including api, etc.
Thank you!
API2D:    https://api2d.com/wiki/doc

**Comment by wujigge** [comment]
![image](https://github.com/brianpetro/obsidian-smart-connections/assets/128662968/d76d938c-94c4-4eb5-9f80-af61cf91bb6d)
This is another plugin for obsidian that allows you to customize the endpoint to use API2D.
Configuration method
Third-party applications must support user-defined OpenAI keys and hosts.
In general, in the app/web page you want to use, go to the Settings page and:
Fill in the OpenAI Key or Key with the Forward Key created earlier
Type https://openai.api2d.net into Host or server
And you're done! It's ready to go.

**Comment by brianpetro** [comment]
In [this response video](https://youtu.be/r__RIepesjY), we have confirmed that API 2D support is now available for chat models, providing a viable third-party substitute for regions where the official API is not supported. Although API 2D is not yet available for embedding models, local embedding models can be utilized to work around regional restrictions. This issue will be closed upon posting this recording. Thank you for the request.
