### ISSUE TITLE
API Key is not working as expected

### ISSUE THREAD

**Issue by lucasciotti** [brianpetro/obsidian-smart-connections#225]
Hi all!

I installed the Smart Connections plugin in my Obsidian but when I try testing Obsidian shows me a message: **"API Key is not working as expected"**.

![Screen Shot 2023-05-28 at 08 30 39](https://github.com/brianpetro/obsidian-smart-connections/assets/134845068/0b97a983-fac4-403d-aec4-8c5e31e4b9a9)

I tried to reinstall the plugin and generate new ChatGPT API Keys, but it didn't solve.

⚠️ Important:I don't use ChatGPT Plus, but I have some credits in my account to use the API ($18).

Can someone help me?

**Comment by jakemkc** [comment]
Hi,

I suppose you are using the free credit provided by openAI. 

It should be related to a rate-limit issue associated with the free credit.

I pay for API access and then everything runs smoothly.

see more at: https://github.com/brianpetro/obsidian-smart-connections/issues/44

Best,
Jake

**Comment by remsho** [comment]
I'm having the same problem, so this is probably the solution. Do you recommend buying tokens for 3.5 turbo or 4?

**Comment by brianpetro** [comment]
ChatGPT is neither required nor sufficient. You must have billing setup (to pay for API token usage) in your OpenAI account. The billing setup is required whether or not you have "free credit" available.

🌴

**Comment by FiekeB** [comment]
Yeah great...I have a debit card  with enough money on it and it is not accepted by OpenAI, nor is there any other way of paying for OpenAI. S*cks bigtime, imho. Very stupid of them to rule out half the world, where credit-cards aren't nearly as normal as in the USA. In The Netherlands almost no one has a credit card. Only businessmen or people that need to travel across the world. SO frustrating.

**Comment by Florian-Rustler** [comment]
I am having the same problem and I tried to implement the solutions provided here: I have $20 credits for the API through: https://platform.openai.com/. I have then created a new API-Key which I have copied into the Smart Connections plug-in settings. Smart Chat Model is set to gpt-3.5.-turbo 16K. When I press Test API Key, I receive the error message above.

Any further advice what I could do to make it work?

**Comment by brianpetro** [comment]
@Florian-Rustler did you add billing information to your OpenAI API account?

Without adding billing info, the rate-limits may be the same as a "free" account even if you have credits.

**Comment by Florian-Rustler** [comment]
Yes @brianpetro I have credit card information under "Payment methods" and my personal information and address under "Billing preferences" from the start.
Inspite of all this I receive the error message of the plugin.

**Comment by jeldrett** [comment]
> Yes @brianpetro I have credit card information under "Payment methods" and my personal information and address under "Billing preferences" from the start. Inspite of all this I receive the error message of the plugin.

Did you ever find a solution? I'm having the same issue...

**Comment by brianpetro** [comment]
@jeldrett checkout this thread https://github.com/brianpetro/obsidian-smart-connections/discussions/155#discussioncomment-7632050

🌴

**Comment by brianpetro** [comment]
[Recorded response](https://youtu.be/yNjkPY_FGA8): 429 error code from OpenAI indicates issues with the account connected to the API key. Ensuring that the account has prepaid API credits should resolve these issues.
