### ISSUE TITLE
OpenAI data usage

### ISSUE THREAD

**Issue by nikbishop** [brianpetro/obsidian-smart-connections#227]
Hi,
I've recently installed the plugin and love what it can do - no need to migrate to Mem! However, when I check my OpenAI data usage there seems to be something going crazy in the background gobbling up all my tokens. 
The usage went from a couple of requests (which is the testing I was doing) to 4,000 a couple of hours later then 24,000 requests an hour later.  Something very strange going on!  Checking on the usage info gives "text-embedding-ada-002-v2, 12500 requests".. does anyone have any idea where this may be coming from?
![Screenshot 2023-05-30 at 14 56 24](https://github.com/brianpetro/obsidian-smart-connections/assets/117286929/3025aac7-4edb-4ddc-88a1-df7df3c860e2)

**Comment by brianpetro** [comment]
It's possible that your `.smart-connections/embeddings-2.json` isn't being saved properly. You should be able to find that file and it will be upwards of 100MB of it's being saved properly.

**Comment by nikbishop** [comment]
Hi Brian,

Thank you sincerely for your help.

The file is 88MB.  The .failed-embeddings.txt also has about 200 entries. How should it be reset? Delete and reinstall the plugin?

Thanks and regards,

Nik

**Comment by brianpetro** [comment]
If you have less than 5K total notes, then you should be able to hit "retry failed embeddings" and your initial usage concern was simply the initial processing.

Keep an eye on your OpenAI usage and the amount of requests for embeddings should have dropped off significantly.

Lastly, I would not delete the embeddings file, it isn't helpful to do so in any circumstance I've encountered and it prevents re-embedding (reduces usage cost).

**Comment by brianpetro** [comment]
[Video response](https://youtu.be/iQA_xgmPI9o)
