### ISSUE TITLE
FR: Setting to turn on/off fetching from OpenAI

### ISSUE THREAD

**Issue by brimwats** [brianpetro/obsidian-smart-connections#23]
I'd like to explore the smart connections for awhile without having the plugin fetch new smart connections with the files mtime. It would be nice to have a setting to turn off fetching (I spent $7 USD total for 10k files by the way!)

**Comment by brianpetro** [comment]
@brimwats $7 is what I expect for that amount of notes. The good thing is that your API usage shouldn't be anywhere near that from now on unless you delete your `embeddings.json` file.

In addition to the `mtime`, I have already implemented hashing to prevent re-embedding unchanged content. There are also several other improvements I have planned regarding efficiency. These will also help in keeping the usage down.

That said, there should still be a way to continue using the plugin without updating embeddings, even if the results are stale/dated. Thanks for the suggestion!

**Comment by brimwats** [comment]
that all sounds incredible! thank you so much for your labour!

I have a lot of files that get minor yaml updates (so the mtime changes) but the file itself doesn't substantially change, so there would be no need to run the full analysis again until a major rewrite. from my own tests I know it would be cheaper if minor changes, but this is a case where the human is smarter 😅

**Comment by brianpetro** [comment]
Let me know this gets any better with the latest update.

It should skip the file if no content of sub-headings changes. But that won't work if there aren't sufficient headings in the note.

I have a TODO that will also utilize file size in determining whether to re-embed. I'll add some priority to it!

**Comment by brimwats** [comment]
amazing!!! thank you! I'll try this weekend

**Comment by brianpetro** [comment]
Recorded response https://youtu.be/lSzBvqvfvuk
