### ISSUE TITLE
Smart Chat can't search folders when typing "/"

### ISSUE THREAD

**Issue by BrianJChoi** [brianpetro/obsidian-smart-connections#233]
Hi Brian!
You have revolutionized the way I use Obsidian with the plugin!

Just one issue that I am having which I can't seem to work it out.
I am trying to search based on files in a particular folder, as shown in the example in the input line for Smart Chat.
The links `[[]]` works! typing [[ prompts me to search for a specific file, but it doesn't seem to work for folders when I type `/`

**Comment by brianpetro** [comment]
Video response https://www.youtube.com/watch?v=s0rFfqXOV6A
