### ISSUE TITLE
Obsidian freezes, Error Request failed, failed embedding batch

### ISSUE THREAD

**Issue by shameforest** [brianpetro/obsidian-smart-connections#236]
I try to use Smart Connections, I have ChatGPT subscription and inserted my API key.
But when I have installed and enabled Smart Connections, Obsidian becomes very slow.

In the console there are these errors:

undefined
plugin:smart-connections:1123 Error: Request failed, status 400
    at new t (app.js:1:1719205)
    at $U (app.js:1:1719397)
    at app.js:1:1720074
    at app.js:1:236930
    at Object.next (app.js:1:237035)
    at a (app.js:1:235753)
plugin:smart-connections:1026 failed embedding batch
plugin:smart-connections:1116 undefined
plugin:smart-connections:1123 Error: Request failed, status 400
    at new t (app.js:1:1719205)
    at $U (app.js:1:1719397)
    at app.js:1:1720074
    at app.js:1:236930
    at Object.next (app.js:1:237035)
    at a (app.js:1:235753)
plugin:smart-connections:1026 failed embedding batch
plugin:smart-connections:1116 undefined
plugin:smart-connections:1123 Error: Request failed, status 400
    at new t (app.js:1:1719205)
    at $U (app.js:1:1719397)
    at app.js:1:1720074
    at app.js:1:236930
    at Object.next (app.js:1:237035)
    at a (app.js:1:235753)
plugin:smart-connections:1026 failed embedding batch
plugin:smart-connections:1116 undefined
plugin:smart-connections:1123 Error: Request failed, status 400
    at new t (app.js:1:1719205)
    at $U (app.js:1:1719397)
    at app.js:1:1720074
    at app.js:1:236930
    at Object.next (app.js:1:237035)
    at a (app.js:1:235753)
plugin:smart-connections:1026 failed embedding batch

Whats going on? What did I wrong?

**Comment by shameforest** [comment]
Is this Github still alive? Does anyone have solutions?

**Comment by c1505** [comment]
I'm also getting freezing when this plugin is enabled. I tried just leaving it to embed everything. It still is embedding after leaving it for a few hours and about $4.00 of open AI usage. The cost doesn't bother me as long as I know that it isn't just cycling through the same things over and over again.
