### ISSUE TITLE
GTP 4 connection not working incl error log

### ISSUE THREAD

**Issue by ingewertwijn** [brianpetro/obsidian-smart-connections#237]
I used smart notes with the free open AI connection, on GPT3. That worked fine.

I have now paid for an open AI subscription. I can now use GTP4 on their website, but smartnotes/chat gpt will not answer any questions  in obsidian if I set the model tot GPT4. It just blinks and does nothing.
Once I change the plugin option back to GPT3, everything works again.

**Comment by ingewertwijn** [comment]
I have now included the error file.
[when I use GPT4 obsidian.md-1687180144464.log](https://github.com/brianpetro/obsidian-smart-connections/files/11788449/when.I.use.GPT4.obsidian.md-1687180144464.log)

**Comment by ingewertwijn** [comment]
I have now included the error file.
[when I use GPT4 obsidian.md-1687180144464.log](https://github.com/brianpetro/obsidian-smart-connections/files/11788457/when.I.use.GPT4.obsidian.md-1687180144464.log)

**Comment by brianpetro** [comment]
@ingewertwijn are you referring to using GPT-4 within ChatGPT Plus?

If so, unfortunately, the API version, which is utilized in Smart Connections, requires a different level of access that can be obtained by applying to this waitlist https://openai.com/waitlist/gpt-4-api

🌴

**Comment by brianpetro** [comment]
@ingewertwijn can you confirm that GPT-4 is available for you in the OpenAI API playground at this link https://platform.openai.com/playground?mode=chat

**Comment by ingewertwijn** [comment]
Yes!

This email has been written on a mobile device and may contain typos etc
________________________________

**Comment by ingewertwijn** [comment]
I even have it on my phone. Image attached

This email has been written on a mobile device and may contain typos etc
________________________________

**Comment by ingewertwijn** [comment]
Proof of subscription. And I have put myself on that “waiting list” lots of times.

This email has been written on a mobile device and may contain typos etc
________________________________

**Comment by brianpetro** [comment]
@ingewertwijn I don't see any image. Try clicking "view on GitHub" then replying there. Here's what it should look like if you have access 
![Screenshot_20230619-213152](https://github.com/brianpetro/obsidian-smart-connections/assets/1886014/04000523-981e-4fa0-be37-ffb38fa35995)

**Comment by ingewertwijn** [comment]
Hi Brian, on the playground I cannot get GPT 4.
But I have a subscription to use ChatGPT at GPT 4 level. Apparently that is a different thing. I enclose the image.

I find it strange that developers get prioritized on the waiting list but their users do not.  I have applied so many times, nothing seems to shift on that list.

![Screenshot 2023-06-20 083638](https://github.com/brianpetro/obsidian-smart-connections/assets/11061485/9b02a786-4192-40d3-9aea-d268c282bdf3)

**Comment by ingewertwijn** [comment]
I have GPT4 now, and all seems to be working
