### ISSUE TITLE
smart connections : notes exluded without reasons

### ISSUE THREAD

**Issue by mickahouan** [brianpetro/obsidian-smart-connections#241]
Hello,

I've been using smart connections for a few months. But for about 1 week I've had notes excluded for no apparent reason. Does anyone else have the same problem?
To solve the problem, I've tried deleting all my old exclusion settings, but that didn't change anything.
I'm about to carry out a forc refresh.

**Comment by mickahouan** [comment]
It works again. I suspect that the supercharged links plugin has slightly modified the structure of the embedd files, making them inaccessible. I was able to restart the files that weren't working...

**Comment by brandones** [comment]
I'm also having this issue, but am not using the supercharged links plugin. Any file which is in a folder is excluded. I have some folder exclusions, but other folders seem to be excluded too.

**Comment by brandones** [comment]
Ooh, it works when I exclude by path, with the folder names followed by a slash. Like "Foo/,Bar/". The folder exclusions option seems not to work.
