### ISSUE TITLE
Responses get truncated

### ISSUE THREAD

**Issue by EpicPilgrim** [brianpetro/obsidian-smart-connections#242]
I often ask Smart Connections questions that have long responses. Whereas in ChatGPT, you can click "Continue" when this happens and it will keep feeding you the response, with Smart Connections, it just truncates it and stops. Is there a way Smart Connections can detect this truncation has happened and continue polling until it has processed the entire response?

**Comment by pongnguy** [comment]
I am also having this issue.  Would be nice to see the whole response, as I am not sure what is in the truncated portion....

**Comment by brianpetro** [comment]
Should be better now with longer context models
