### ISSUE TITLE
What is `vec-lite`

### ISSUE THREAD

**Issue by qazxcdswe123** [brianpetro/obsidian-smart-connections#245]
There is a `vec-lite` dependency but according to `package.json` it's a local file on your computer. 

I'd like to help with this project and I wonder what the secret sauce would be :)

**Comment by brianpetro** [comment]
It will be published as its own an open source project. 

I'm working on extracting the components that aren't specific to Obsidian from this plugin into their own modules.

One of the reasons for this is to make it easier for others to contribute.

Thanks for the interest 

🌴

**Comment by brianpetro** [comment]
Closing as vec-lite was a component of v1 that is no longer used 😊🌴
