### ISSUE TITLE
Not updating to the latest version.

### ISSUE THREAD

**Issue by DonTheApex** [brianpetro/obsidian-smart-connections#246]
After repeatedly updating the plug-in through the community plugins tab, it says it’s updating and then it removes the update button followed by a pop up alerting that there’s a new version available.

**Comment by groovebak** [comment]
Same here. I must have tried 20 times and it still won't update to the latest version. I considered uninstall/reinstall, but I'm worried it will have to reprocess all the notes again and cost a bajillion tokens.

**Comment by brianpetro** [comment]
@groovebak @DonTheApex Thanks for bringing this to my attention!

If you try again, it should work this time.

For future reference, uninstall/reinstall will *not* delete your embeddings.

Thanks for your help
Brian 🌴

**Comment by groovebak** [comment]
Fantastic! It worked like a charm. Thank you so much!
