### ISSUE TITLE
FR: Improve Startup Time

### ISSUE THREAD

**Issue by brimwats** [brianpetro/obsidian-smart-connections#25]
I think this might partially be my large embeddings file, but on startup obsidian will lock up for a good 5ish minutes, and use a large amount of memory:

![image](https://user-images.githubusercontent.com/73113656/213623509-90f09fde-5133-47be-8509-7a9ef5d266b7.png)

here are the filesizes:

![image](https://user-images.githubusercontent.com/73113656/213623562-6a88382c-7524-41a6-a647-d49047b74578.png)

**Comment by brianpetro** [comment]
Do you know if this is every time you startup? The migration from `embeddings.json` to `embeddings-2.json` would have made it worse, but that should only happen once.

Performance has been on my mind. And I have some ideas. Could you keep me posted on this? I will add priority to those performance updates depending on how it goes.

**Comment by brimwats** [comment]
It's been getting a little better! Relatedly: if someone closes the right pane module it shouldn't automatically reopen/reload on startup; I think that may be part of the issue. Perhaps it should only load when it's opened?

**Comment by brianpetro** [comment]
Yeah, that's a good idea. Basically move the "on load" logic into the "on open view" logic.

**Comment by brianpetro** [comment]
@brimwats better late than never! This was added in `1.2.5`. Thanks for your help :)
