### ISSUE TITLE
Files shown as failed to process but presenting smart connnections in lateral tabs

### ISSUE THREAD

**Issue by MarkSant** [brianpetro/obsidian-smart-connections#250]
In the plugin menu, several files/notes are shown as being failed to be processed, but when I open the files/notes listed there, the lateral tab that shows me the smart connections actually show me that the processing happend and the smart connections are avaiable.
So, now, I don't know if the files actually have been processed or not.
I already have posted in another issue about the fact that some file/notes are not being processed or embedded because of some characters, like ":" or "-", but now, even after changing the data and eliminating those characters, they are in the list of errors again...
Anyone have any idea of what may be going one? Did the files/notes were indeed processed or is it a bug?

**Comment by brianpetro** [comment]
@MarkSant have you tried the "retry failed files" button in the settings?

Also, it's possible that some sort of bug has kept those files in the "failed" list while having embedded them successfully. Off the top of my head, this could happen to failed files that you visit after they were added to the failed list. The retry button (in settings) should clear that up right away.

As long as the retry button clears things up, an occasional few failed files isn't anything to be concerned with. It could happen from any interruptions ranging from your WiFi restarting/reconnecting to the OpenAI API having downtime. Rate limits also can cause failure, especially when first installing the Smart Connections.

Thanks for trying out Smart Connections and let me know if the retry solves this or if we need to troubleshoot further.

Brian 🌴

**Comment by MarkSant** [comment]
Unfortunately, I've used the button sometimes in the attempt to test again if those files were failling because of some other character in the YAML. After some modifitations, some tests and clickings in the buttom, nothing changed.
As I said, most of these files listed were already embbeded sucessfully after I had taken out the characters, but when I reloaded them updating some content, they went to the list (some updates in the plugin happend to in the meanwhile). 
I've checked and is not a problem of limit rates, because I've also waited some days and retried the buttom with no sucess.
The thing that makes me believe that it must be a bug is the fact that when oppening the file, the smart connections tab shows me the connections being made and the results. But yet I feel insecure to say that it has indeed being processed, since it is in the list.
Anyway, thanks for the quick response and for the great work you're doing with the plugin! 
It's astonishing the power it provids to deal with scientific research and scientific articles included in the vault.
Congratulations!

**Comment by brianpetro** [comment]
@MarkSant is it possible for you to share any of those files with me?

A successful embedding is necessary for the Smart View to work, and the prior embedding is deleted prior to generating a new one. However, a new embedding will only be created of the file size had been changed by 10%. So maybe there's a big somewhere between those points.

Keep me in the loop if you have any ideas what else might be triggering the problem.

Thanks for following up
Brian 🌴

**Comment by MarkSant** [comment]
Sure!
![image](https://github.com/brianpetro/obsidian-smart-connections/assets/22659808/f4b63b72-98d1-437e-b5f1-4162b93ff492)

Here a three of them:
https://1drv.ms/f/s!AqukJ_yJ8sAolOFiA4PORlsRj7LXdw?e=CkRnSG


After this information you just gave me (about the need of 10% change), one idea came to me: the changes I made to files when I updated then my have no reached 10%, but I cann't be sure and I don't know how it could impact on this error.
Anyway, I hope the files help to dealing with it,

**Comment by brianpetro** [comment]
@MarkSant have you tried without the "@" in the file name?

When you change the file name or move a note to a new folder, it will override the 10% threshold and cause a re-embedding.

Also, in the settings you can toggle on [logging](https://github.com/brianpetro/obsidian-smart-connections#settings-advanced) to the developer console. This will give you a list of files that have changed but were skipped over for re-embedding because of low change %.

**Comment by MarkSant** [comment]
I just tried that. 
Removed @ forced with buttom = nothing changed, still in the list and tab showed connections being made;
Closed and reopen the program and forced with buttom = the same;
Added @ forced with buttom = nothing changed, still in the list and tab showed connections being made;
Closed and reopen the program and forced with buttom = the same;

The logging options were already enabled and returned with the same errors for all files:
![image](https://github.com/brianpetro/obsidian-smart-connections/assets/22659808/394f58be-3ee6-42db-932e-9ba461247565)

**Comment by hannal** [comment]
I've tried disabling and re-enabling the plugin, "retry failed files" and "Force Refresh", but they all fail.

I'm using Vault in iCloud Drive, and the full path has a `~` or space character in it. It looks like this: `/Users/%username%/Library/Mobile Documents/iCloud~md~obsidian`. Could this be the cause? For example, for the Vimrc support plugin, some features don't recognize these paths properly, so I had to use a workaround.

```
" not working
exmap nextHeading jsfile mdHelpers.js {jumpHeading(true)}

" it works.
exmap nextHeading jsfile ../../../../../.config/obsidian/mdHelpers.js {jumpHeading(true)}
```

**Comment by brianpetro** [comment]
@hannal That is possible. 

Is there a way you can test it?

Thanks,
Brian 🌴

**Comment by hannal** [comment]
<img width="321" alt="Screenshot 2023-06-18 at 2 01 49" src="https://github.com/brianpetro/obsidian-smart-connections/assets/4952/6233c318-3397-4f17-81d5-461d4b70ea91">

My OpenAI API Key set to Smart Connections is limited to too many requests (429), so I can't test it. That message is an error log from Smart Connections, as you know.

I think Smart Connections needs to retry the API call after an interval when the OpenAI API call fails. Unfortunately, my OpenAI API key is blocked for the fifth time, which makes it difficult to test further. 🥲

**Comment by brianpetro** [comment]
@hannal you need to setup billing in your OpenAI account

Brian 🌴

**Comment by MarkSant** [comment]
Update: @brianpetro , I Forced Refresh and, Unfortunately, the same files remained with the same behavior: displayed at the failed list and showing smartconnections at the lateral tab.
