### ISSUE TITLE
TypeError: empty array with no initial value 

### ISSUE THREAD

**Issue by Kevjinx** [brianpetro/obsidian-smart-connections#252]
When the input is a really vague question, I get this type error. 

![image](https://github.com/brianpetro/obsidian-smart-connections/assets/25070905/866c7d30-b45c-4e46-bd2b-0062a13bb674)

`
caught (in promise) TypeError: Reduce of empty array with no initial value
    at Array.reduce (<anonymous>)
    at SmartConnectionsChatView.get_nearest_until_next_dev_exceeds_std_dev (plugin:smart-connections:2704:22)
    at SmartConnectionsChatView.get_context_hyde (plugin:smart-connections:2685:20)
    at async SmartConnectionsChatView.initialize_response (plugin:smart-connections:2393:23)
get_nearest_until_next_dev_exceeds_std_dev @ plugin:smart-connections:2704
get_context_hyde @ plugin:smart-connections:2685
await in get_context_hyde (async)
eval @ plugin:smart-connections:2377
`

**Comment by ZenboxMarketing** [comment]
I have this same error, but it's for every question I ask, even simple ones like "How many notes do I have?" I have 3.5 turbo selected. I haven't gotten the chat to work yet, although my API key is valid

**Comment by ZenboxMarketing** [comment]
Actually I'm starting to have conversations with the chat now and I'm beginning to see that it's only looking at the note I have open unless I say "Based on my notes"

**Comment by lumsdnb** [comment]
@ZenboxMarketing I had the same issue and fixed it by restarting obsidian.
