### ISSUE TITLE
CAN AZURE API be supported？

### ISSUE THREAD

**Issue by fan1jun** [brianpetro/obsidian-smart-connections#256]

**Comment by perryfr** [comment]
@brianpetro  I too would like to know whether Azure API will be supported at some point, as I have a vault with sensitive information in it that I would like to use with Smart Connections. It seems the Copilot plugin supports Azure, but having just successfully set up Smart Connections with a different vault, I'd love to set it up with this new vault as well.

**Comment by brianpetro** [comment]
@perryfr 

While this isn't a priority for me personally, as I'm focusing on model-agnostic developments, it isn't particularly difficult so I do encourage the community to see what they can do about contributing integrations with additional models/providers.

**Comment by perryfr** [comment]
Thanks, Brian. I appreciate the rapid response.

**Comment by squid-man** [comment]
+1 to this! I have an Azure OpenAI subscription and no plans to get an OpenAI subscription. I would love to be able to use Azure with this plugin. Have there been any developments to support Azure OpenAI endpoints/keys?

**Comment by brianpetro** [comment]
Recorded response https://youtu.be/T2I1QQxCb1Q

I am pleased to announce that the Azure API can now be custom configured. The new capability allows for more flexibility and customization in managing API endpoints.

**Comment by jullimullins** [comment]
Could someone give some help how to configure Azure API properly? I have got Azure API working with TextGenerator plugin but not with Smart Connections. I asume that the custom API settins wont give right info after you push save. For example leaving everything empy, you will get info which states: "Success, API key is valid"
![image](https://github.com/user-attachments/assets/987e82a9-f886-4041-9471-f2c250cc5951)
