### ISSUE TITLE
always being "loading embeddins file ... " apikey is valid 

### ISSUE THREAD

**Issue by wxl002** [brianpetro/obsidian-smart-connections#258]

**Comment by wxl002** [comment]
<img width="331" alt="image" src="https://github.com/brianpetro/obsidian-smart-connections/assets/47291655/c921ab17-67e6-4fde-a538-626ec77badf5">

**Comment by brianpetro** [comment]
Hmmm. Was this working properly for you before this?

Thanks for letting me know about the issue @wxl002 ,
🌴

**Comment by wxl002** [comment]
> 

Never. I reinstalled it many times.

**Comment by brianpetro** [comment]
@wxl002 Check out this thread https://github.com/brianpetro/obsidian-smart-connections/issues/244#issuecomment-1603458823

🌴

**Comment by wxl002** [comment]
@brianpetro Thanks. it works !
