### ISSUE TITLE
Does the chat gpt plugin work?

### ISSUE THREAD

**Issue by bbecausereasonss** [brianpetro/obsidian-smart-connections#259]
I followed instructions, did sync (although it did not tell me done, or throw an error). Then went into chat GPT and asked it a general question re some of my content. It said "To create a step-by-step guide to recreate the tone, structure, and characteristics of X's emails, I would need to analyze a sample of these emails. However, as an AI developed by OpenAI, I don't have access to personal data about individuals unless it has been shared with me in the course of our conversation. I am designed to respect user privacy and confidentiality."

What am I missing? I suppose there's no way to query a specific note or folder through the plugin but seems it's not querying the data either.

**Comment by brianpetro** [comment]
Can you share a screenshot?

Could you tell me if you're talking about the Smart Chat in Obsidian? Or the new ChatGPT Plugin that requires a supporter license?

Thanks
🌴

**Comment by bbecausereasonss** [comment]
I'm describing the plugin in chatGPT. I got the key, added to both (pressed sync) then tried to speak to my notes through the plugin to no avail.

**Comment by brianpetro** [comment]
@bbecausereasonss in order to better help, please reply to the email where you received the supporter key so I can look into your specific account.

To help speed things along, please also provide the exact prompt(s) you are using when receiving the error.

Thanks
Brian 🌴
