### ISSUE TITLE
Allow keys for sending chat messages to be configurable

### ISSUE THREAD

**Issue by ElanHasson** [brianpetro/obsidian-smart-connections#262]
would be great if we could have an option to let shift+enter be for new lines again, but CTRL+enter be for sending. With enter also doing new lines.

**Comment by brianpetro** [comment]
[Recorded response](https://youtu.be/-w8i2i3HjGM): While a complete solution is being explored, a temporary workaround is to use the tab and enter keys when in the chat input.

Closing in favor of https://github.com/brianpetro/obsidian-smart-connections/issues/163
