### ISSUE TITLE
FR Better handle token limit reached from past messages in Smart Chat

### ISSUE THREAD

**Issue by ElanHasson** [brianpetro/obsidian-smart-connections#263]
### Script Error when attempting to chat

Chat was working, but then began to not work:

```
Uncaught (in promise) TypeError: Reduce of empty array with no initial value
    at Array.reduce (<anonymous>)
    at SmartConnectionsChatView.get_nearest_until_next_dev_exceeds_std_dev (plugin:smart-connections:2798:22)
    at SmartConnectionsChatView.get_context_hyde (plugin:smart-connections:2779:20)
    at async SmartConnectionsChatView.initialize_response (plugin:smart-connections:2485:23)
```

**Comment by brianpetro** [comment]
> Chat was working, but then began to not work:

Based on that, it sounds like you hit the token limit in past messages.

If you haven't already, switch to the 16K model in the settings to increase the max length of the thread. You should then be able to continue the thread from there. 

Unfortunately, there isn't a way to handle hitting the max tokens from past thread messages in the plugin yet. So you'll need to create a new thread (top right 'plus' button) to start a new chat if this happens.

Thanks for noticing this and putting it on the record with helpful error codes in your message!

Brian 🌴

**Comment by ElanHasson** [comment]
thanks @brianpetro 

I'm a technical user, so I knew to look in debug console. 

You should surface an `alert()` or something so people don't get frustrated.

**Comment by ElanHasson** [comment]
Additionally, I want to stay on GPT4 for the increased functionality it provides for what I'm doing.


Also, I did try with a new chat and ran into the same issue. I have large documents.

Perhaps a better approach is to better limit the number of tokens from documents as `get_nearest_until_next_dev_exceeds_std_dev` is attempting to do.  Relevance doesn't seem to be computed "accurately" here as it's trying to send more than it can. 

IMO the priority should be functioning vs using a different model.

**Comment by brianpetro** [comment]
@ElanHasson Thanks for the insight.

Document context is only used in the message where it is triggered, for example, with the "based on my notes" phrase or by linking to a specific note in the chat. This is less than ideal, of course. 

> IMO the priority should be functioning vs using a different model.

That's 100% my thoughts on this as well. The model change I suggested was just in case you could use it a temporary patch.

I've been floating around a few different ideas for how to improve the chat, but I haven't settled on anything yet.

I appreciate your insights as I continue to noodle on the best direction for this. Thanks for your help in making Smart Connections better!

Brian 🌴

**Comment by brianpetro** [comment]
Enhancements have been implemented to better handle token limits. These improvements come from the latest version updates and the extended context capabilities now available in most models. This addresses the original concerns, making the handling of token limits more efficient.

[Video response ](https://youtu.be/5rRkB8cxB40)
