### ISSUE TITLE
Answers are cut off and won't continue

### ISSUE THREAD

**Issue by ingewertwijn** [brianpetro/obsidian-smart-connections#265]
Before today, I could ask the plugin to continue an answer by saying "go on" or simply pressing send again.
Now it won't . The answers seem shorter too.
This renders the plugin useless to me.  I need long answers.
Is this a bug or should I be looking at another solution?

**Comment by brianpetro** [comment]
@ingewertwijn are you still having this issue?

**Comment by ingewertwijn** [comment]
No, it seems to have disappeared. But I hav GPT-4 access now (finally!) so I am not sure what solved it.
