### ISSUE TITLE
Feedback/Questions.

### ISSUE THREAD

**Issue by bbecausereasonss** [brianpetro/obsidian-smart-connections#266]
Thanks for your recent, work tool is really improving! 

Few pieces of feedback.

I love how now we barely have to type 'continue'. Seems to just automatically continue the string. Love that.

I am wondering about in (obsidian) context though. 

I am finding that when I query a note, and get an answer I end up having to query that specific note again through [[ ]] otherwise GPT does not recognize what we were talking about. In fact, it does not seem to recognize any of the context of the actual conversation.

Is there a way to fix this or at least allow a checkbox to use the conversation as context as well?

**Comment by mashean** [comment]
I have noticed the same behavior

**Comment by brianpetro** [comment]
[Recorded response ](https://youtu.be/9NsgnGEhHzU)

This has been addressed by enhancing the chat system to retain all relevant context when retrieving from notes. This improvement resolves the feedback provided and ensures a more comprehensive context inclusion in chat interactions
