### ISSUE TITLE
longer context with gtp3.5 16k model gets stuck

### ISSUE THREAD

**Issue by avataraustin** [brianpetro/obsidian-smart-connections#270]
When using the chat and the gpt 3.5 16k model if I ask a question making use of a fairly long context I get the "..." indication that the app is processing but it never returns a result. If I ask a short question with short context, I get an answer back.  I tried the same context+question with the Obsidian TextGenerator ChatGPT plugin and I get an answer, so It does not seem to be an OpenAi issue but rather an issue with Smart Connections.

**Comment by kathekon** [comment]
I also experienced this behavior

**Comment by brianpetro** [comment]
@avataraustin @kathekon can you check the developer console for errors next time this happens?

It will help me track down the source of the bug.

Thanks for reporting this!
Brian 🌴
