### ISSUE TITLE
Issue when slashes (/) are included in the text of the Chat

### ISSUE THREAD

**Issue by RealRavens** [brianpetro/obsidian-smart-connections#275]
If I was getting a summary from a section in a book or article lets say on code, and the text includes a slash anywhere, even just 1, it seems to hang indefinitely. I don't know if it's searching for a folder location since I know that's a feature. Take all slashes out and it works normally as intented. 

Does this for both Chat GPT 3.5 4k and 16k

**Here's a very quick example:** 
**Text I'll summarize:** "You can start a comment anywhere within your code by placing two forward slashes (//). After these two slashes, everything on the line will become a comment, which the compiler will pretend doesn’t exist."

**As a prompt, lets say I want a bullet point list:** Summarize as bullet points: You can start a comment anywhere within your code by placing two forward slashes (//). After these two slashes, everything on the line will become a comment, which the compiler will pretend doesn’t exist.

**Error**
[![Image from Gyazo](https://i.gyazo.com/b10837640e4fa4cb8e35d89533f9e153.png)](https://gyazo.com/b10837640e4fa4cb8e35d89533f9e153)

[obsidian.md-1688242756789.log](https://github.com/brianpetro/obsidian-smart-connections/files/11927070/obsidian.md-1688242756789.log)

**Same prompt w/o slashes**
Summarize as bullet points: You can start a comment anywhere within your code by placing two forward slashes. After these two slashes, everything on the line will become a comment, which the compiler will pretend doesn’t exist.

**Desired Result**
- Two forward slashes can be used to start a comment in code.
- Everything on the line after the slashes will be considered a comment.
- The compiler will ignore and skip over the commented code.

**What the console looks like when working:**
[![Image from Gyazo](https://i.gyazo.com/6a30ceb4035529c22120a0876ef45f43.png)](https://gyazo.com/6a30ceb4035529c22120a0876ef45f43)

Anyways, keep up the good work Brian and folks. I'll be supporting as usual. Can't wait to see this continue to grow, especially the Note Linking feature.  Take care~

**Comment by brianpetro** [comment]
Thank you for bringing this issue to my attention.

> I don't know if it's searching for a folder location since I know that's a feature.

That seems likely to be the culprit. Whether it's being caused by a lack of matching folders, or something else, I will have to investigate further.

Thanks for your support and helping me make Smart Connections better by reporting this issue!
Brian 🌴

**Comment by RealRavens** [comment]
Looks like Mr.Brian sneakly fixed this under the covers. Done a bunch of testing and works fine. You can close this if you'd like.

**Comment by brianpetro** [comment]
Thanks @RealRavens

**Comment by RealRavens** [comment]
Hmm, this just came up recently. I'm not too sure why, compared to when I was testing it before. But it's as if it's happening again. Here's the error I got:

[![Image from Gyazo](https://i.gyazo.com/2140125e958216bd8512fdaea77583bb.png)](https://gyazo.com/2140125e958216bd8512fdaea77583bb)

It's doing that folder check problem again. This is a head scratcher. So text like code blocks including // in them are causing stalling again. Cause when no folders are found, it chooses not to proceed. I think, in the mean time, if it can't find the folder, it should still send it through. Else may need to be an option to turn of folder checks. 🤔💭

**Comment by brianpetro** [comment]
@RealRavens thanks for bringing this to my attention.

I'll have to give it a look.

🌴

**Comment by brianpetro** [comment]
Video response: https://youtu.be/gQ2Lj1GvCHo

Now, only slashes in the folder format for triggering a lookup will be registered, and slashes that do not match a folder pattern will be ignored.
