### ISSUE TITLE
Shortcut for "smart Connections: Open: View Smart Connections" is invalid

### ISSUE THREAD

**Issue by hongxunming** [brianpetro/obsidian-smart-connections#277]
<img width="855" alt="image" src="https://github.com/brianpetro/obsidian-smart-connections/assets/43163254/bb257717-5859-4884-9586-4ba78cd8a40a">

**Comment by brianpetro** [comment]
@hongxunming what do you mean by invalid?

Thanks for your help in solving this,
Brian 🌴

**Comment by hongxunming** [comment]
> @hongxunming what do you mean by invalid?
> 
> Thanks for your help in solving this, Brian 🌴
---------------------------------------------------------
Hi,

1. Issue: When the "Smart Connections Files" tab is already open but not in focus, it cannot be reopened using a shortcut.

2. After adding the code in the red box in the image below, this issue was resolved.
<img width="710" alt="image" src="https://github.com/brianpetro/obsidian-smart-connections/assets/43163254/f04215de-b105-4b41-894a-a9f2be5f5bd3">

Thank you for creating such a great plugin, it has brought a lot of convenience to my studies!

**Comment by brianpetro** [comment]
@hongxunming thanks for solving this. Should be able to get it pushed shortly along with the GPT-4 turbo update.
