### ISSUE TITLE
Customize Question

### ISSUE THREAD

**Issue by Another5405** [brianpetro/obsidian-smart-connections#278]
HI,  I'm very interested in this sentence.

"The quality of the responses depends on the content and organization of your notes. 
Ensure your notes are well-structured and comprehensive for the best experience."

and I view README.md and peek some issues, I have so many word wait to speak.
But first I was very happy to find this plugin, and you were notice dataview and Excalidraw during development.

I have not study AI so much, I keep learning and multimedia related things, 
and learn database and obsidian since one year and half,
Sorry if my FR and opinion is not match the point, I don't know how vector database work.

==straight to the point==

I think the biggest advantage of obsidian is the custom organization, but this will make it very troublesome to integrate AI.
In the past year and a half, I have been actively learning the skills of organization and management in Obsidian, 
and I also hope that I can quickly retrieve useful information

here are some of my thoughts:

Is it possible to let the Chat function choose to execute our code according to the situation, 
so as to obtain specific information or let AI perform work?
This allows everyone to set up their own personal assistant? 
(Since everyone's structure is completely different, and there are always situations where content needs to be restricted)

(Just like QuickAdd, but you can set the temperature, specify the content of the output, 
and the overall description of the content, or attach a valid description to the content)
(Or let AI send out json or object, let the custom function read and process)

---

Like my item management method:

I will use dataviewjs to track the status of the Task on the Project panel, and I will also create an Excalidraw for the TaskBorad
If some tasks are not in TaskBorad, a code box will be provided on the Project panel for easy addition.
So each note of a particular type would have a panel like this:

```dataviewjs
let file = dv. current();
let EmbedPanel = dv.pages("#EmbedPanel").where(x=>x.file.name == file.Type + "Top")[0];
if(EmbedPanel!=null)
{
  let fpath = EmbedPanel.file.path;
  let file = app.vault.getAbstractFileByPath(fpath);
  let text = await app.vault.read(file);
  dv.paragraph(text);
}
```

(So one of my FRs can be turned off to read the dataviewjs codeblock. )
(I haven't started installing Smart Connections yet, and I'm still learning on it)

I also made a command line function to replace the homepage,
 he can get the code of the file connection to judge whether it can be selected, so as to achieve the effect of reminder.

Also, I've tried linking projects and matters to visions or interests.
But every project or matter has many factors, I think it is very difficult to prioritize

At best it is based on diaries and visions to suggest arrangements such as:
"You have eaten junk food for the last 7 days, do you want to eat healthy food for two days next week?"
Obviously, if we want AI to be an assistant, we have to provide our own indexing method and template
AI doesn't necessarily have to leverage vertical databases to get the job done

As you know, it's impossible to fake ordering
But AI may be able to check for you based on the set template 
(your item management notes (descriptive structure, and steps))

So I think we should do something like "Step", let AI use it when it thinks it needs to be used, 
and have the ability to output objects for function to read.
And the steps can be chained, because the AI may first understand what categories are in my current Tag #Data, 
and then use another Step to obtain related content.

I think that makes the conversation more effective because there's less confusion.

Also Step should have a priority judgment in case your preconditions not fulfilled.
I think that is the priority problem's answer, maybe.
you can set your goal, and let AI remind you.

Also about this part:
https://github.com/brianpetro/obsidian-smart-connections/issues/159

I think it is possible to set up a scratch space similar to RAM and a custom refresh mechanism, 
so that some things can be kept updated, and others do not need to be updated.

---
My case 1
from the perspective of game design, both raising and lowering the temperature are worth trying

I can set the temperature to zero and ask:
Is there anything left over from my summary (eg: #Knowledge/GameDesign)? (compare #Data/GameDesign)

0.3:
What do you think of rouge-like with racing games? (#Data/GameDesign + #Knowledge/GameDesign)

1:
Trying to design a racing game based on current insights into game design (#Data/GameDesign)

---
My case 2
https://github.com/brianpetro/obsidian-smart-connections/issues/27

Also, I prefer to build a database because I can enter more data
If I create a unit for each piece of music in the music list

"This music is very similar to that [[music]] with instruments!"

"Hey Chat, list ten 8-bit songs that would fit Christmas"

I do need to link to an external database, the Assets Management Tool: Eagle
But I can use the same method (Step) to let AI help me according to my original structure, without making you tired.

---
My case 3
I am already very familiar with how to create a database in Obsidian, using the same technique is boring, 
and creating an interface is more time consuming
If I can use the above functions, I believe that I can also let AI help me build database and interface functions, my method.
This way I can keep updating my library and manage assets better.

---

Again, sorry in advance if this information is not in the same direction as yours

PS:I find this via Chat GPT Plugin, How can I set up email and license_key?

**Comment by brianpetro** [comment]
I'm not sure what this is asking. Please feel free to re-open if you'd like to clarify the issue 🌴
