### ISSUE TITLE
More API errors.

### ISSUE THREAD

**Issue by bbecausereasonss** [brianpetro/obsidian-smart-connections#279]
These are happening pretty consistently now, even with files that are not very large (latest plugin).

scheduled save
plugin:notion-like-tables:13314 WebSocket connection to 'ws://localhost:8097/' failed: 
connectToDevTools2 @ plugin:notion-like-tables:13314
plugin:notion-like-tables:13314 WebSocket connection to 'ws://localhost:8097/' failed: 
connectToDevTools2 @ plugin:notion-like-tables:13314
plugin:obsidian-outliner:1150 Uncaught TypeError: Cannot read properties of null (reading 'getListUnderLine')
    at DragAndDrop.startDragging (plugin:obsidian-outliner:1150:27)
    at DragAndDrop.handleMouseMove (plugin:obsidian-outliner:1068:22)
plugin:notion-like-tables:13314 WebSocket connection to 'ws://localhost:8097/' failed: 
connectToDevTools2 @ plugin:notion-like-tables:13314
2plugin:obsidian-outliner:1150 Uncaught TypeError: Cannot read properties of null (reading 'getListUnderLine')
    at DragAndDrop.startDragging (plugin:obsidian-outliner:1150:27)
    at DragAndDrop.handleMouseMove (plugin:obsidian-outliner:1068:22)
plugin:notion-like-tables:13314 WebSocket connection to 'ws://localhost:8097/' failed: 
connectToDevTools2 @ plugin:notion-like-tables:13314
plugin:notion-like-tables:13314 WebSocket connection to 'ws://localhost:8097/' failed: 
connectToDevTools2 @ plugin:notion-like-tables:13314
plugin:notion-like-tables:13314 WebSocket connection to 'ws://localhost:8097/' failed: 
connectToDevTools2 @ plugin:notion-like-tables:13314
plugin:notion-like-tables:13314 WebSocket connection to 'ws://localhost:8097/' failed: 
connectToDevTools2 @ plugin:notion-like-tables:13314
plugin:smart-connections:148 embeddings file size: 106524473 bytes
plugin:notion-like-tables:13314 WebSocket connection to 'ws://localhost:8097/' failed: 
connectToDevTools2 @ plugin:notion-like-tables:13314
plugin:notion-like-tables:13314 WebSocket connection to 'ws://localhost:8097/' failed: 
connectToDevTools2 @ plugin:notion-like-tables:13314
plugin:notion-like-tables:13314 WebSocket connection to 'ws://localhost:8097/' failed: 
connectToDevTools2 @ plugin:notion-like-tables:13314
plugin:notion-like-tables:13314 WebSocket connection to 'ws://localhost:8097/' failed: 
connectToDevTools2 @ plugin:notion-like-tables:13314
plugin:smart-connections:3052 Array(2)
plugin:smart-connections:2639 chat_ml Array(2)
plugin:smart-connections:2641 max_total_tokens 6000
plugin:smart-connections:2643 curr_token_est 8394
plugin:smart-connections:2647 max_available_tokens 200
api.openai.com/v1/chat/completions:1          Failed to load resource: the server responded with a status of 400 ()
plugin:notion-like-tables:1904 CustomEvent
overrideMethod2 @ plugin:notion-like-tables:1904
plugin:smart-connections:2734 Uncaught (in promise) CustomEvent
plugin:notion-like-tables:13314 WebSocket connection to 'ws://localhost:8097/' failed: 
connectToDevTools2 @ plugin:notion-like-tables:13314
plugin:notion-like-tables:13314 WebSocket connection to 'ws://localhost:8097/' failed: 
connectToDevTools2 @ plugin:notion-like-tables:13314
eval @ plugin:notion-like-tables:13296
plugin:notion-like-tables:13314 WebSocket connection to 'ws://localhost:8097/' failed: 
connectToDevTools2 @ plugin:notion-like-tables:13314
eval @ plugin:notion-like-tables:13296
plugin:notion-like-tables:13314 WebSocket connection to 'ws://localhost:8097/' failed: 
connectToDevTools2 @ plugin:notion-like-tables:13314
eval @ plugin:notion-like-tables:13296
plugin:notion-like-tables:13314 WebSocket connection to 'ws://localhost:8097/' failed: 
connectToDevTools2 @ plugin:notion-like-tables:13314
eval @ plugin:notion-like-tables:13296

**Comment by brianpetro** [comment]
@bbecausereasonss are you still running into this error?

**Comment by bbecausereasonss** [comment]
I am every once in a while yes... Not sure the reason, but seems to be mostly attributed to miscalculations on tokens.
