### ISSUE TITLE
Can we use a minimum relevance score to limit most relevant notes?

### ISSUE THREAD

**Issue by davidszp** [brianpetro/obsidian-smart-connections#28]
Does OpenAI provide some sort of score for 'matching goodness of fit' of the results? If so, could we get an option that allows us to limit results e.g. to options with a score better than 0.60 for example (if scoring from 0.00 to 1.00). Alternatively, maybe we could limit the results to the top N most relevant connections?

**Comment by brianpetro** [comment]
This is in the works. Thanks for your feedback @davidszp !

**Comment by brianpetro** [comment]
@davidszp a recent update now shows the similarity percentage in the results. It's not exactly what you requested, but may help us narrow down the parameters to decide on what's necessary for this feature request. Let me know what you think .

**Comment by davidszp** [comment]
I have 1.1.18 installed but do not see percentages in the results.

**Comment by brianpetro** [comment]
> I have 1.1.18 installed but do not see percentages in the results.

So I just checked and you need to have the "show full path" toggled on in the settings. I'm making a note to change this so it will appear with both settings in the future. 

Without full paths turned on, then the percentages only appear in the "expanded" view (when you click the icon on the left side of the filename to display blocks matched within a file).

**Comment by brianpetro** [comment]
@davidszp based on the minute variations between similarity scores, I think it would be hard to set a specific limit. However, I am considering implementing a feedback system to improve results.

I'll be closing this issue for now. Feel free to re-open if you have anything to add. And thanks for your help in making Smart Connections better!
