### ISSUE TITLE
Option for having a different API Key per vault?

### ISSUE THREAD

**Issue by ElliottDyson** [brianpetro/obsidian-smart-connections#281]
Say I have a few large totally distinct and independent vaults... I feel like it could be useful in terms of functionality to be able to assign a different API key per vault so that it is possible to have per vault embeddings.

Do you think this is something that could be doable?

Also, on another note. Do you think you'll ever integrate being able to link with locally hosted LLMs?

Love what you've done btw, I've really been finding this so useful! Thank you!

**Comment by nomadphase** [comment]
My understanding is that the embeddings are stored locally as a json file within the smart connections folder in your vault. As such, each file would be specific to that vault. Not sure that a specific API key would be required, but it should be feasible, you just plug each key in to the smart connections plugin in each vault.

**Comment by brianpetro** [comment]
@nomadphase is correct.

Your API key is stored in a settings file that is specific to the vault.

**Comment by brianpetro** [comment]
[Video response](https://youtu.be/m1LBQmv6NZo)
