### ISSUE TITLE
Please add the ability to customize the API endpoint

### ISSUE THREAD

**Issue by wujigge** [brianpetro/obsidian-smart-connections#283]
# Hello author!

I realy like this plugin very much, it became my translation, calculation, code assistant!
However, due to the region, payment and other problems, I can't get the official api smoothly!

## So, please add the ability to customize the API endpoint, like in the screenshot
![chatbox](https://github.com/brianpetro/obsidian-smart-connections/assets/128662968/634b5ac0-5592-4b74-a005-ff5f76d7b1e5)
![Snipaste_2023-07-11_10-14-46](https://github.com/brianpetro/obsidian-smart-connections/assets/128662968/683d617c-0fa8-4e5d-ad92-26222915a1a0)

Something like "API Host", or "Endpoint",
I can use chatgpt's service by purchasing a third-party transfer.

Thank you very much!

**Comment by brianpetro** [comment]
@wujigge  Thank you for your feedback and suggestion. I understand that being able to customize the API endpoint would be beneficial for users who are facing region, payment, or other issues with the official API.

I appreciate your input and the details provided with the screenshot. I will be considering when the might be the right time to implement something like this.

Thank you for using the plugin and for your support!  
Brian🌴

**Comment by bbecausereasonss** [comment]
I think being able to use other API's would be very beneficial as well. Right now GPT 4 is degrading faster every day. I've been using Claude 2 and blown away by how good it's reasoning and writing is relative to GPT4... Would love to be able to use it eventually as well.

**Comment by chymian** [comment]
that goes hand in hand with: https://github.com/brianpetro/obsidian-smart-connections/issues/276

**Comment by brianpetro** [comment]
This is available since `v2.1` 🌴😊
