### ISSUE TITLE
"invalid string length"

### ISSUE THREAD

**Issue by Smitty010** [brianpetro/obsidian-smart-connections#290]
I just installed Smart Connections.  Based on what I think is in the embedding-3.json file, it would appear there are about 28,000 embed vectors.

I very frequently get the error message from Smart Connection "invalid string length".  When this occurs, Obsidian locks up for a few seconds (like it's processing the error).  However, my failed-embeddings.txt file is still 0 length.

After several minutes, the entire Obsidian display goes black and the only thing I can do is close Obsidian and restart it.  I have only rarely seen this until I install Smart Connections.  It has now happened several times in the last hour.  Based on that, I assume it's Smart Connections.

When I've been able to try searching using Smart Connections, the results are pretty impressive.  However, these other issues are probably going to force me to turn it off.  

If there is anything I can look at to help diagnose the problem, let me know.

**Comment by Smitty010** [comment]
Just disabling the plugin wasn't sufficient.  I was still getting the "smart connection: Invalid string length".  I will try restarting obsidian.  That seems like a bug as well.

**Comment by Smitty010** [comment]
I was thinking about this, does Smart connections consider "invalid string length" a recoverable error and does a retry.  It feels like it may be in a loop.  The activity on my machine (high CPU on a dual-quad core cpu)  suggests it might be.

**Comment by Smitty010** [comment]
I tried to play with this some more.  Here are some more observations.
1. Note that I have a fairly large vault, 8000+notes.  A lot of the notes are articles and can be somewhat long.  As I mentioned, there appear to be 28,000+ embeddings in the embeddings json file.  I'm guessing that's not enough to be complete.  I'm going based on John Mavrick's description of when you generate an embedding.
2. When I first reenabled Smart Connections today, I saw a lot of "get_embeddings_batch" messages.  This went on for several minutes.  I'm assuming that Smart Connections is crawling the vault and comparing it to what's in the embeddings file to determine what's left to be done.  
3. When it finally looked like it was going to start adding more embeddings, I got the following exception
```
plugin:smart-connections:73 loaded embeddings file: .smart-connections/embeddings-3.json
plugin:smart-connections:1939 rendering connections
plugin:smart-connections:1003 get_embeddings_batch
**plugin:smart-connections:351 Uncaught (in promise) TypeError: Cannot create property 'be7ca27adda6de5897be9bfeebb519ff' on boolean 'false'
    at VecLite2.save_embedding (plugin:smart-connections:351:30)
    at SmartConnectionsPlugin.get_embeddings_batch (plugin:smart-connections:1028:31)
    at async SmartConnectionsPlugin.get_file_embeddings (plugin:smart-connections:923:7)
    at async SmartConnectionsPlugin.find_note_connections (plugin:smart-connections:1115:9)
    at async SmartConnectionsView.render_note_connections (plugin:smart-connections:2000:20)**
save_embedding @ plugin:smart-connections:351
get_embeddings_batch @ plugin:smart-connections:1028
await in get_embeddings_batch (async)
eval @ plugin:smart-connections:1970
setInterval (async)
render_connections @ plugin:smart-connections:1966
initialize @ plugin:smart-connections:1926
plugin:smart-connections:73 loaded embeddings file: .smart-connections/embeddings-3.json
```
4. The screen immediately went totally black (i.e., the entire Obsidian UI was one black box) and was unusable.  I could stop it by closing the window.
5. I started obsidian back up and turned Smart Connections off.  However, as I mentioned above, I don't think that stops the background task that's getting embeddings.  I got hundreds of Dataview errors:
```
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
(anonymous) @ app.js:1
plugin:smart-connections:274 cleaning up embeddings
plugin:smart-connections:1003 get_embeddings_batch
**index.html:1 Uncaught (in promise) Error: No available storage method found.
    at driverPromiseLoop (plugin:dataview:12218:33)**
setTimeout (async)
e.notify @ app.js:1
e.add @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
``` 
I don't know what the interaction with Dataview is, but the problem went away as soon as I restarted Obsidian without Smart Connection being enabled

When I've seen Smart Connections work, it seems really cool.  Unfortunately, I think it's unusable for me in the current state.

Let me know if you want any other information.

**Comment by brianpetro** [comment]
@Smitty010 version 2 is a complete re-write, so if you haven't tried recently, give it a go and let me know what you think 😊🌴
