### ISSUE TITLE
Smart Connections Files LATEX doesn't render on begin-end align (edge case)

### ISSUE THREAD

**Issue by johnbie** [brianpetro/obsidian-smart-connections#292]
This is the current behavior:
![begin-end-align not working](https://github.com/brianpetro/obsidian-smart-connections/assets/12724122/9e009663-aa7a-4f7f-b887-1fd0751a1462)

And this is the behavior on Obsidian note file:
![expected version](https://github.com/brianpetro/obsidian-smart-connections/assets/12724122/08b0b0f4-1ad5-40b0-a7f7-5a1851932077)

**Comment by brianpetro** [comment]
Hey @johnbie 

That's interesting, and good to know.

Thanks for bringing this to my attention!

Brian 🌴

**Comment by brianpetro** [comment]
This should be fixed in the latest versions 😊🌴
