### ISSUE TITLE
Embeddings file not found

### ISSUE THREAD

**Issue by skorphil** [brianpetro/obsidian-smart-connections#297]
Regularly i get an error that embeddings.json is not found. And need to create a new one
Where is this file stored?

**Comment by skorphil** [comment]
Well, seems like plugin struggle to work with iCloud sync. I don't know. 
Plugin worked ok for some time after I deleted all embeddings files and force it to create a new one, but after some time it is telling me that there is no embeddings file, but the file is there. 
It happens all the time. So basically I need regularly recreate embeddings files

**Comment by brianpetro** [comment]
Files are now stored in a new format that is more compatible with syncing services 😊🌴
