### ISSUE TITLE
 FR: Toggle results to show context

### ISSUE THREAD

**Issue by arminta7** [brianpetro/obsidian-smart-connections#3]
It would be helpful to be able to see some context in the results pane. Perhaps a toggle to show a part of the related section? Obsidian's native search UI is a good example.

**Comment by brianpetro** [comment]
That is a great suggestion, and the search UI is a great example of what should be done here.

In the meantime, you can hold `CTRL` + hover/mouseover to preview the notes without opening a new tab.

**Comment by arminta7** [comment]
That's what I'm currently doing, although there are sometimes unintended consequences because when the preview comes up the results panes changes and if my mouse is still there I'm kicked into a new preview. Not a huge deal, small annoyance.

**Comment by brianpetro** [comment]
@arminta7 version `1.1.7` begins to add this feature. Let me know what you think.

**Comment by smartguy1196** [comment]
@brianpetro Issue seems to be stale (last update was almost 2 months ago).

Recommend closure, unless you're still working on this

**Comment by brianpetro** [comment]
@smartguy1196 Thanks for the help
