### ISSUE TITLE
[FR] Hide the extension file in the smart links preview for md files

### ISSUE THREAD

**Issue by vguillet** [brianpetro/obsidian-smart-connections#30]
A small tweak which would improve readability. Once other file types start to be also parsed it should probably be included, but for md files I feel like it is a bit superfluous given the context.

Solution: Do not include the .md file extension at the end of the file name in the smart links file list

**Comment by brianpetro** [comment]
@vguillet, good catch, I must've gone blind to it!

Updated in `1.1.8`

**Comment by jacknoff** [comment]
> [@vguillet](https://github.com/vguillet), good catch, I must've gone blind to it!
> 
> Updated in `1.1.8`

Am I missing something in the settings menu? I can't seem to find an option to hide the .md extensions. Thank you.
