### ISSUE TITLE
Unlock Local AI Processing in Obsidian (feature request)

### ISSUE THREAD

**Issue by dicksensei69** [brianpetro/obsidian-smart-connections#302]
I'm writing to request a feature that would allow users to easily switch between different AI APIs within obsidian-smart-connections. Specifically, I'm interested in being able to toggle between the OpenAI API and emerging alternatives like Oobabooga's textgen and Llamacpp.

These new services offer exciting capabilities like local embeddings and on-device processing that could enhance the Obsidian experience, especially for users who want to avoid sending personal data to third parties. I've found where the API endpoint is configured in the code, and with some tweaking I may be able to switch between them manually. However, having an official option to select different APIs would provide a much smoother experience.

For those wondering, the API endpoint is currently specified in multiple locations the first being on line 1043 of main.js. 
url: `https://api.openai.com/v1/embeddings`,

line 2666
const url = "https://api.openai.com/v1/chat/completions";

line 2719
url: `https://api.openai.com/v1/chat/completions`,

To manually change the API, these endpoints could be modified to point to local services like Oobabooga or Anthropic. However, this involves directly editing the source code which is cumbersome.

Ideally, there could be a function that defaults to OpenAI, but allows the API URL to be easily configured as a setting. Users could then switch to local IPs or services with just a simple configuration change. Furthermore, if this setting was exposed through the GUI, it would enable seamless API swapping without any code editing required.

The open source ecosystem is rapidly evolving, and empowering users to take advantage of these new innovations aligns with Obsidian's ethos of flexibility and customization. Users would love to rely on my own local hardware for AI processing rather than being locked into a single provider.

Thank you for your consideration. Obsidian has been invaluable for my workflow, and I'm excited by its potential to integrate some of these cutting-edge AI capabilities in a privacy-preserving way. Enabling easy API switching would be a major step forward. Please let me know if I can provide any other details!

**Comment by dragos240** [comment]
I may make a PR for this. I've gotten it to work on my local instance of text-generation-webui. All that needs to be done to change the URL is to open `main.js` and replace the OpenAI API base URL with your own. For it to work with text-generation-webui, you'll need to enable the `openai` extension, which mimics the endpoints of the OpenAI API. One thing I am not entirely sure about is how the embeddings play with it. I'm testing it out now.

**Comment by dragos240** [comment]
Nevermind, someone [beat me to it](https://github.com/brianpetro/obsidian-smart-connections/pull/229)

**Comment by nomadphase** [comment]
In case this is not prioritised here, it may be useful to look at the Khoj/Obsidian plugin, which is opensource and enabling Llama2

**Comment by brianpetro** [comment]
@nomadphase thanks for sharing that project.

I checked it out and it does require a separate desktop application to be installed to use the Obsidian plugin. This is the route I expect will be necessary to utilize local models with Obsidian.

While there hasn't been much publicly to see lately in terms of plugin updates, I have been doing a lot in private that will have big implications for this plugin. For example, allowing the Smart Chat to add to and edit notes is just one long weekend away.

And during my weekday work, I've been chugging away at something that, when it makes its way into Obsidian, will be unlike anything else I've seen publicly as far as AI tools are concerned. To clarify why I bring this up now, I've been focussing on using GPT-3.5 for that project _because_ I want the result to be compatible with local models. Basically, my hypothesis is that, if I can make it work with GPT-3.5, then the same functionality should work with local models very soon.

It's still been tough to find a local model for the embeddings that beats OpenAI's `ada` embeddings. If anyone comes across anything, please let me know.

And lastly, thanks everyone (@dragos240 @dicksensei69 ) for your interest in Smart Connections and I'm looking forward to making more updates soon!

Now back to it,
Brian 🌴

**Comment by ReliablyAwkward** [comment]
I yearn to be updated on this topic, as I am now playing with Docker for windows to obtain LocalAi, such descriptions as the owner hinted upon above would be a genuine game changer.

**Comment by wenlzhang** [comment]
Here are some local LLM related tools that might be of interest:
- [jmorganca/ollama: Get up and running with Llama 2 and other large language models locally](https://github.com/jmorganca/ollama)
- [hinterdupfinger/obsidian-ollama](https://github.com/hinterdupfinger/obsidian-ollama)
- https://github.com/mistralai/
  - The recently released Mistral model is faster than LlaMA on my Intel Mac.

**Comment by huachuman** [comment]
What about using g4f?

https://github.com/xtekky/gpt4free
https://github.com/xiangsx/gpt4free-ts

**Comment by brianpetro** [comment]
@wenlzhang @huachuman thanks for the resources!

I'm still reviewing options and requirements, but I think we're pretty close to having a local embedding model.

The chat models still require an amount of hardware resources that make me pause, but we can do a lot with embeddings alone. And if we were to still use OpenAI for the chat responses while relying on a local embedding model, then that would also significantly reduce the exposure of vaults to OpenAI, as only context used for a specific query would be sent to their servers.

🌴

**Comment by joelmnz** [comment]
In addition to local LLM support, would you consider a LLM router such as https://withmartian.com/ that boasts faster speeds and reduced costs?

I haven't tried this service out yet but if it would be considered I would be happy to investigate further

**Comment by barshag** [comment]
any updates on how to connect Ollama ?

**Comment by brianpetro** [comment]
@barshag 

V2.1 will enable configuring API endpoints for the chat model. While I can't say how featureful this option will be compared to what's possible with the OpenAI API, especially considering I intend to add significant capabilities via function calling in v2.1 and I'm not up-to-date on where local models are in that regard, the configuration should allow for integration with local models for individuals capable of setting up the model locally to be accessed via `localhost`.

**Comment by benabhi** [comment]
I desperately need this feature ^^ I tried editing the main.js openai url and changing them to my local llm with lvstudio but it didn't work.

**Comment by wwjCMP** [comment]
LM Studio provides proxy functionality compatible with the OpenAI API.

**Comment by brianpetro** [comment]
@wwjCMP yes, it does.

I've already connected it in my development version of Smart Connections.

Configurable endpoints/models is just one of the chat features that will be rolling out with `v2.1`. Still got a few things I'm working on, but it should be rolling out pretty soon as an early access option for supporters.

🌴

**Comment by UBy** [comment]
Support for an OpenRouter connection would be huge, as it gives you access to a great amount of models using the same API.
https://openrouter.ai/docs#models

**Comment by brianpetro** [comment]
@UBy that looks interesting, thanks for the tip.

**Comment by Korayem** [comment]
> Support for an OpenRouter connection would be huge, as it gives you access to a great amount of models using the same API: https://openrouter.ai/docs#models Maybe this is a bit off topic, but related as this is just another configuration of a custom endpoint.

was about to post a Feature Request but did a search first and found your comment @UBy 

Glad @brianpetro likes it!

**Comment by leethobbit** [comment]
Thanks for the great plugin - I'd like to add to the requests for local LLM usage - if it's to be allowed that we can modify the base_url for the model, can we ensure it will work beyond just localhost? I think a lot of us are hosting our models on servers or gaming desktops atm, and I definitely can't run anything locally on my laptop.

Very excited for this!  Sending data to a 3rd party like OpenAI is a showstopper for me and most people I know that are dabbling in the LLM space currently.

**Comment by brianpetro** [comment]
Hey @leethobbit , happy to hear you like Smart Connections 😊

Custom local chat modes are already partially available in the `v2.1` early release. I say partially because none of the people helping me beta test `v2.1` seemed to have tried to use it. I could get it working in my tests, but the local models I was testing with, the only ones I could run on an M2 8GB Mac, returned mostly gibberish.

The current implementation allows custom configuration over `localhost,` but I already decided to implement access to all configurations for the "custom" models. This would allow using any hostname if the endpoint accepted the OpenAI API format. That's probably what you're looking for to access your gaming machine from your laptop. But this hasn't been a priority since no one participating in the early release has indicated any interest, or even use of, the local chat models.

Maybe you can help work out the bugs once `v2.1` becomes a general release, which should be relatively soon, as I have some other big updates I'm looking forward to implementing in `v2.2`.

Thanks for participating in the Smart Connections community!
🌴

**Comment by Allwaysthismoment** [comment]
Bravo!!

Nice update and loading it up now.
________________________________

**Comment by wwjCMP** [comment]
> Update: Thanks to the help of an individual who prefers to remain unnamed, I got the Smart Chat working with Ollama. So far, the new settings for the local chat model look like this in the v2.1 early release: ![Screenshot 2024-04-01 at 6 10 49 PM](https://private-user-images.githubusercontent.com/1886014/318581346-ec79e555-c042-4c32-9437-75fd0cbdf164.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3OTQ1NjgsIm5iZiI6MTcxMzc5NDI2OCwicGF0aCI6Ii8xODg2MDE0LzMxODU4MTM0Ni1lYzc5ZTU1NS1jMDQyLTRjMzItOTQzNy03NWZkMGNiZGYxNjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjJUMTM1NzQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDhjMDQ4YTA2OTQ5MDgwYWY2OTZjZjNmMTE0NmQzMmUxZmFkYzRkZmQ3MmZlODYxODFiMjgwMDM3MTFlMGZlNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.oC7hHjpcIQM_Yoqb9QmqYNi8cmkKTIKymfiWKYa3QKI) 🌴

Whether it supports using the embedding model run through Ollama.

**Comment by brianpetro** [comment]
@wwjCMP embedding through Ollama is not yet supported. If this is something you're interested in, please make a feature request here https://github.com/brianpetro/obsidian-smart-connections/issues

**Comment by daaain** [comment]
Took me a few tries to get it working with LM Studio so sharing the settings below. Apparently model name is required even if it's not relevant (so I just put some random characters in there).

One thing though, even if I start my question with "Based on my notes..." it doesn't look like any context is being sent to the model. Why could that be? I tried 2 different local embedding models, but same thing.

![image](https://github.com/brianpetro/obsidian-smart-connections/assets/69962/3ad4ab0b-a72c-471f-9b64-68dfedce1568)

**Comment by daaain** [comment]
Oh, I just found out that there are loads of warnings and errors in the console.

First of all I guess this is a bug? No need for an API key when using a local backend.

> No API key found for custom_local. Cannot retrieve models.

Then it also seems to be struggling to retrieve the embedding and with using a tool.

What is `OrtRun().`?

Sorry, realised that a lot of this might be off-topic, just trying to debug the issue...

![image](https://github.com/brianpetro/obsidian-smart-connections/assets/69962/7653ad87-46ad-43a2-9c4d-5b64689f410b)

**Comment by huachuman** [comment]
this extension used to work really well but since v2 came out it's been a nightmare. i never managed to get it working properly again.

**Comment by brianpetro** [comment]
Closing in favor of creating new more-specific issues since the original request, adding local model support, has been added to the latest versions 😊🌴

**Comment by huachuman** [comment]
weird i just said it's not working you marking all my posts as off-topic is a little suspicious but hey brian, you do you.
