### ISSUE TITLE
Error Message: Error Getting Embeddings for "filename"

### ISSUE THREAD

**Issue by Bail1241** [brianpetro/obsidian-smart-connections#313]
Plugin installed and API key. When I open a note the plugin searches the vault for all links but then finishes with error message: 

ERROR getting embeddings for Zettelkasten/Lawrence of Arabia.md or similar for any file I try.

Please can you advise what I can try to clear this logjam?

Many thanks,

David

PS Smart Connections looks a wonderful plugin and I can't wait to use it.

**Comment by Bail1241** [comment]
I have also discovered that the TEST API key causes error message  which says API not working as expected. I will try ceating a new API for the second time and see whether this helps.

**Comment by Bail1241** [comment]
New API installed and still does  not work as expected and I still get the same embeddings error message as I first reported.
Hope you can suggest a way forward.

**Comment by Bail1241** [comment]
Chat feature enables me to ask questions but returns error message:

API errors, see console logs for details

I do not know what  the console log is or where it is located.

Really would appreciate some help as am becoming disheartened by this plugin. It is far easier for me to ask my queries direct via my browser access to Chat GPT. That is working fine.

**Comment by Bail1241** [comment]
Have had a working PAID chatGPT account for months so my problems are not with Chat GPT but seem to centre on embeddings and failed embeddings in the plugin but I do not understand enough to do any more.

HELP, please!

**Comment by Bail1241** [comment]
Sorry to hear you are struggling with the same issue, Sacha73, but I am pleased that I'm not on my own! Lets hope we can both be sorted quickly.

**Comment by brianpetro** [comment]
Did you try the "Test API key" button in the settings?

Re https://github.com/brianpetro/obsidian-smart-connections/issues/316#issuecomment-1684145750 Supporters do get access to a special support email that is monitored more regularly than these GitHub issues.

Thanks for trying Smart Connections!

🌴 Brian

**Comment by Bail1241** [comment]
I did try "Test API Key" button as per my second message above which I followed with a new API key  which did not solve the problem as per my third message above.

Brian, I take your point (by e mail) that you wish you had the time to answer every item but you prioritise issues not raised before. My comment is that  I am a new user trying to install Smart Connections and unable to do so. I very much wish I had the time and knowledge to get Smart Connections working and could then become a supporter which you float as the way to get prompter answers. Becoming a user comes before becoming a supporter....... 

 I admire what your plugin sets out to do but can't unfortunately get at it so must turn thumbs down at this stage.

David

**Comment by brianpetro** [comment]
@Bail1241 it's tough to help you further without more information. 

For windows, accessing the console log can be done with F12 or Ctrl+Shift+I > Console > Check for errors.

You can share any errors you see as screenshots and also use the search feature for this GitHub repository to find similar issues / discussions about what you're encountering.

Thanks again for your interest in Smart Connections 😊

🌴 Brian

**Comment by Bail1241** [comment]
Thanks further comments. I do not have the time or the will to pursue a n exhaustive trail  to try and solve this problem. Basically, Im using my M2 Mac mini with Studio Display and Obsidian works a treat as do a variety of plugins like Dataview, Excalibrain and others. Smart Connections is the only plugin I have encountered  with such problems. Since I have a paid account with Chat GPT, I can live without Smart Connections. As far as I am concerned, I like using software; I absolutely hate having to debug software.  Best wishes David
