### ISSUE TITLE
Smart Connections but NO HELP

### ISSUE THREAD

**Issue by Bail1241** [brianpetro/obsidian-smart-connections#316]
After 4 days waiting for some help, I have heard nothing and my case has had no one assigned to it

I am therefore de-installing this plugin which promised much but has so far delivered little.

It is a shame but support was offered via Github. Suggest these help post sneed monitoring not ignoring.

David

**Comment by brianpetro** [comment]
Hey @Bail1241 

I wish I had time to answer every question! (Maybe AI will help with that soon 😜)

But since I can't, I try to focus on the questions that haven't been answered before. That said, sometimes I might miss new questions, too. 

Thanks for your interest in Smart Connections!

🌴 Brian
