### ISSUE TITLE
Checking mobile iOS

### ISSUE THREAD

**Issue by horacioeps** [brianpetro/obsidian-smart-connections#318]
Hi
I know it is not designed for mobile but I just went and changed 

  "isDesktopOnly": false,

in the manifest file.

Then I go to iPad or iPhone, it opens the plugin but it shows "embeddings file not found". 

I checked it is there. I use Obsidian sync.

Can this somehow be fixed?

**Comment by brianpetro** [comment]
Mobile is in beta-testing in v2.2 https://twitter.com/wfhbrian/status/1788293763892191528 👀
