### ISSUE TITLE
Link color invisible against blue text bubble

### ISSUE THREAD

**Issue by CodexVeritas** [brianpetro/obsidian-smart-connections#325]
I am using the Blue Topaz Theme. When I've been using the chat, sometimes it creates links to notes and colors them blue (like the normal hyperlink blue). This makes them almost impossible to read against the blue background that the responses are put in for the chat.

**Comment by brianpetro** [comment]
@CodexVeritas can you send a screenshot? I'll see if I can send you a CSS snippet.

🌴

**Comment by brianpetro** [comment]
Something like:

```css
.sc-chat-container a.internal-link {
  color: INSERT COLOR;
}
```

You can read more about adding CSS snippets here https://help.obsidian.md/Extending+Obsidian/CSS+snippets

🌴

**Comment by brianpetro** [comment]
The latest version fixes this by using the installed theme for Smart Chat styles 🌴😊
