### ISSUE TITLE
Connection with Chatgpt4 does not work with error "API Error. See console logs for details."

### ISSUE THREAD

**Issue by haiyan-Wei** [brianpetro/obsidian-smart-connections#331]
Smart Connection is indeed a very smart app. Thanks for developing and sharing it. 

I just upgraded to 4, and I keep getting "API Error. See console logs for details." I tried it with a few new API Key. If I switch back to 3.5, it will work appropriately. 

Do you know how to fix this? Thanks!

**Comment by brianpetro** [comment]
@haiyan-Wei it could be that you don't have access to GPT-4 in your API account.

You can check in the playground at this link https://platform.openai.com/playground?model=gpt-4

If you have access to GPT-4, you should be able to see it like this 
![Screenshot_20230908-180621](https://github.com/brianpetro/obsidian-smart-connections/assets/1886014/9a53ff31-b2fe-466a-8ecb-d3c1fb086751)

🌴

**Comment by haiyan-Wei** [comment]
Thank you for the reply. I checked and I don't have access to GPT-4 yet. 

It appears that access requires a minimum payment of $1. I hope there's a way to make this deposit.
