### ISSUE TITLE
blacklist unclear, whitelist needed

### ISSUE THREAD

**Issue by pictoys** [brianpetro/obsidian-smart-connections#334]
it seems a little unclear to me what's actually included and excluded from the vault. we are dealing with a lot of sensetive content and i think its quite essential when using this to know EXACTLY which files are being processed. until then i can only use this in a sandbox vault. nice work thought, i like it!

**Comment by simonmeggle** [comment]
May I jump in with a related side question: I am completely new to this plugin and wondering if/how data are exposed at all? 
Will my whole vault be sent outside? 
The idea is great, but I could only use such a plugin if I can be sure that I am the only one who has the vault.

**Comment by brianpetro** [comment]
OpenAI is used to process your data. They claim to not store your data or train models on your data sent to the API, but that's all I can say wrt data exposure.

While I intend to make local models available in the future, I also intend on keeping OpenAI, and/or models from similar providers, available as these allow access to SOTA AI, while the local variants remain quite limited.

> until then i can only use this in a sandbox vault

This would be the best option for highly sensitive vaults. 

🌴 Brian

**Comment by brianpetro** [comment]
Closed in favor of https://github.com/brianpetro/obsidian-smart-connections/issues/121 🌴
