### ISSUE TITLE
Include/exclude note form the actual note

### ISSUE THREAD

**Issue by franciscoabenza** [brianpetro/obsidian-smart-connections#346]
Using the command pallet or button in the right side column

**Comment by huachuman** [comment]
I just noticed this problem today. I don't want relevant results from the same note I'm in. It's obviously redundant and cumbersome as it's always the top result.

**Comment by brianpetro** [comment]
@franciscoabenza @huachuman thanks for bringing this to my attention.

I just checked my Obsidian and the current notes is *not* included in the Smart Connections pane.

So this must be some sort of bug but I have no idea what might be causing it.

If there's a note that I might use to test this, and also your current settings, might be helpful in figuring this one out.

🌴
