### ISSUE TITLE
Don't generate connections for empty files or for 'Untitled.md'

### ISSUE THREAD

**Issue by olbrich** [brianpetro/obsidian-smart-connections#347]
When creating a new file I sometimes have an `Untitled.md` file.  Smart connections tries to find related pages, but this is not useful.

Also, when giving the new file a name, the smart connections side panel doesn't detect the change and will continue to show the now outdated connections for the 'Untitled.md' file that no longer exists.

**Comment by quicly** [comment]
I'm bumping this thread because I'm experiencing a similar issue with the instant generation of the embedding for a blank Untitled note.

**Comment by quicly** [comment]
I just realized that I could put Untitled filename to the exceptions. Actually, i think it would be good to make this default setting.

**Comment by brianpetro** [comment]
@quicly 

> I just realized that I could put Untitled filename to the exceptions. Actually, i think it would be good to make this default setting.

Brilliant!

I already updated the defaults with the new exclusion https://github.com/brianpetro/obsidian-smart-connections/commit/fd6e01a2825f878f4eefc8374c9cb1a72f9930f8 https://github.com/brianpetro/obsidian-smart-connections/commit/5fabb1199fd418da80eeaa0e98e4be3817d6d088 https://github.com/brianpetro/obsidian-smart-connections/commit/7ce80bacbfed4a5e27879bb8cedcfe7ca2cbd8e5

The new default will be included in the next update.

Thanks for the tip
🌴
