### ISSUE TITLE
[Feature request] Support Claude API

### ISSUE THREAD

**Issue by DelmarHuang** [brianpetro/obsidian-smart-connections#364]
Hi Brian, thank you very much for this amazing plugin! Is it possible to support Claude API too? Thanks again!

**Comment by clening** [comment]
I see that Claude support is now added -- I was wondering if there's a way to change which model is specifically being called? Currently it defaults to Opus (which is lovely, but omg expensive) and I was wondering if an option for sonnet/haiku could also be added? Manual editing in the data.json file doesn't seem to have any effect and just creates an error.

**Comment by brianpetro** [comment]
Hey @clening 

There's a `models.json` compiled into the `main.js` that needs to be edited. 

Since all the groundwork was laid for opus, I should be able to get those other two models added quickly. I'm away from my desk right now, but I'll get those added within the next few days. 

🌴

**Comment by brianpetro** [comment]
@clening `sonnet` and `haiku` have been added in `v2.1.6`.

 I like the quickness of `haiku`.

Next time you restart Obsidian/Smart Connections, the `v2.1` early access/beta should automatically update to the new version.

🌴

**Comment by clening** [comment]
Wow! Thanks Brian, that was incredibly quick work. Thanks so much.

C

**Comment by brianpetro** [comment]
Closing since Claude models, including Sonnet 3.2 are now available in v2.1 🌴😊
