### ISSUE TITLE
API key is not working as expected

### ISSUE THREAD

**Issue by liuling73** [brianpetro/obsidian-smart-connections#366]
一直无法正常使用，点击测试API，反回结果：API key is not working as expected，API key是在官网获取的，是正确有效的KEY

**Comment by EvoAlg** [comment]
I get the same thing.

**Comment by brianpetro** [comment]
@EvoAlg @liuling73 check out https://github.com/brianpetro/obsidian-smart-connections/discussions/155#discussioncomment-7632050

**Comment by EvoAlg** [comment]
Thanks, I set up the second billing, deleted and old API key, then waited half an hour, then it worked.

**Comment by MiroStW** [comment]
Hi @brianpetro,
I have read all the issues about API keys not working properly ("API Key is not working as expected" when testing API key) and the 

```
failed embedding batch
plugin:smart-connections:1029 undefined
plugin:smart-connections:1030 Error: Request failed, status 429
```

I have both of those errors, even though I have set up the openAI key properly and have set up billing with accepted credit card for the API. Nothing has ever been charged, but the API key does get hit according to the openAI API key page.

What else might I be missing to make this work? Your help is truly appreciated!! 🙇
