### ISSUE TITLE
Error: New embeddings file size is significantly smaller than existing embeddings file size. Aborting to prevent possible loss of embeddings data.

### ISSUE THREAD

**Issue by huachuman** [brianpetro/obsidian-smart-connections#369]
```
Error: New embeddings file size is significantly smaller than existing embeddings file size. Aborting to prevent possible loss of embeddings data.
    at VecLite2.save (plugin:smart-connections:159:19)
    at async SmartConnectionsPlugin.save_embeddings_to_file (plugin:smart-connections:806:7)
```

I'd like to override this. 

I recently deleted a folder with thousands of notes from my vault. 

Is the only way to fix this to completely re-do the embeddings?

**Comment by huachuman** [comment]
It looks like smart-connections has been abandoned since there have been no updates for a while now.

So I fixed this myself and managed to delete some old embeddings files in the .obsidian/.smart-connections directory. The plugin took care of the rest.

**Comment by quelsemme** [comment]
Not sure how you got the impression that @brianpetro has moved on. Possibly he just missed your post.

**Comment by brianpetro** [comment]
> Possibly he just missed your post

Exactly, thanks for the support @quelsemme 

I am currently working my way through all the ~200 GitHub issues. Should be completed, with a WIP roadmap sent to supporters to gather feedback, sometime in February.

Regarding the issue in this post, the error is an exception that's thrown to prevent erroneously erasing embeddings. A force-refresh could help. But it's tough to say with the available information.

I've also completely rewritten the storage methods in v2, so I'm not as familiar anymore with what was going on in VecLite.

Lastly, regarding my other projects, I like to keep what I call a "circle of focus." A lot of improvements that are coming to Smart Connections are direct results of my other projects, for example, underlying code that I'm open-sourcing and sharing between both, code that originated in the other project.

🌴
