### ISSUE TITLE
Smart Connections disappear after update to 1.6.37

### ISSUE THREAD

**Issue by Deefdeka** [brianpetro/obsidian-smart-connections#376]
Any ideas?

Thank you.

**Comment by Deefdeka** [comment]
![image](https://github.com/brianpetro/obsidian-smart-connections/assets/131713061/ba4d671d-8d26-409c-b814-e75fe92d8c4a)

It simply disappears! 

I am not sure why.

**Comment by brianpetro** [comment]
@Deefdeka can you confirm the plugin is enabled in your community plugin settings?

🌴

**Comment by Deefdeka** [comment]
It appears to the right but not on the left. I still have the folder with the embeddings file from last update.

![image](https://github.com/brianpetro/obsidian-smart-connections/assets/131713061/ed8d98ab-2cc5-4a3b-b6ca-43166983d170)

**Comment by brianpetro** [comment]
@Deefdeka something looks off, particularly the "settings" button is missing. Try uninstalling and re-installing. Not sure how that could've happened, though.

🌴

**Comment by Deefdeka** [comment]
Asking the question out loudly was enough to figure out...

I updated the pronouns to my own language - and with that folder copy-paste I overwrite the system version to the old. Then it probably gets confused and just shuts down.

Thank you for a great, great plugin!

**Comment by brianpetro** [comment]
Happy to hear you got it figured out! 

🌴
