### ISSUE TITLE
Cors Error

### ISSUE THREAD

**Issue by loivp13** [brianpetro/obsidian-smart-connections#391]
I'm using version 1.6.37 of smart-connections and getting CORS errors when testing responses from the API. Anyone else getting this?
![image](https://github.com/brianpetro/obsidian-smart-connections/assets/38137267/9798a7ef-4b54-4095-9b94-cafe2cf476a3)

**Comment by brianpetro** [comment]
Weird! Just tested it out, and I'm seeing this, too.

Investigating...

My version 2 in development is still working, so should have a fix out shortly.

Thanks for bringing this to my attention @loivp13 !

🌴

**Comment by brianpetro** [comment]
@loivp13 Make sure your API key is in the correct input field. 

In my test above, I had used my test-vault and didn't realize it was missing an API key. After re-adding the API key it worked as expected.

🌴

**Comment by brianpetro** [comment]
@loivp13 if you keep getting the error, toggle on debug startup time (screenshot of the setting below) and then re-screenshot the errors. This will give a more accurate insight into which lines of code are running into the issue.

![Screenshot 2023-12-20 at 3 03 42 PM](https://github.com/brianpetro/obsidian-smart-connections/assets/1886014/eefafc5a-8cef-440a-95e4-b571005ef8e4)

Thanks for your help in solving this!

🌴

**Comment by loivp13** [comment]
@brianpetro Thanks for the quick response. I just started testing again today and it now working. I'm not sure what's difference other than restarting Obsidian. I'm gonna close this issue.
