### ISSUE TITLE
Solved issue with Smart View

### ISSUE THREAD

**Issue by Bravesound2023** [brianpetro/obsidian-smart-connections#394]
My Smart Connections plugin works fine with the chat view but not the associated view

**Comment by brianpetro** [comment]
@Bravesound2023 thanks for making a report.

Is this still an issue?

Would you be able to provide a screenshot so I can better troubleshoot the issue?

Thanks
Brian 🌴

**Comment by christianngarcia** [comment]
Resolved in #474
