### ISSUE TITLE
FR: Feed results into GPT3 prompt

### ISSUE THREAD

**Issue by arminta7** [brianpetro/obsidian-smart-connections#4]
I posted an idea here: https://twitter.com/Sarah_A_Bentley/status/1606338249529561088?s=20&t=XTp7SsyB1_pYt9Hy3khiGg
based off of this: https://twitter.com/rileytomasek/status/1603854647575384067?s=20&t=XTp7SsyB1_pYt9Hy3khiGg

Here's what I said: "I want to be able to GPT3-query my own notes and receive answers that are fine-tuned to my style and voice. Semantically search my content for relevant passages and feed them in with the prompt. That's the first step."

Looks like you've gotten the first part. Is the rest doable?

**Comment by brianpetro** [comment]
I'm going to say this is out of the scope of the "Smart Connections" plugin, but "Smart Completions" is already in the works!

Projects like [GPT Index](https://github.com/jerryjliu/gpt_index) enable what you're trying to do, but they require custom code to design workflows. 

The "Smart Completions" Obsidian plugin should enable many of those workflow configurations without any coding. But, that still requires a motivated user to make use of the plugin. On the other hand, this "Smart Connections" plugin should be easy to use out-of-the-box, without any configuration at all.

**Comment by arminta7** [comment]
Understood! Looking forward to Smart Completions and I will check out the resource you mentioned.
