### ISSUE TITLE
Plugin guidelines : Don't detach leave in onunload

### ISSUE THREAD

**Issue by Lisandra-dev** [brianpetro/obsidian-smart-connections#404]
This plugin doesn't respect the plugin guidelines : https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Don't+detach+leaves+in+%60onunload%60

**Comment by brianpetro** [comment]
@Lisandra-dev

Good catch, thanks!

If you don't already have access to v2, please send me an email brian@smartconnections.app 

It would be great to get your thoughts on the new version.

Thanks for all of your help with Smart Connections!
Brian 🌴
