### ISSUE TITLE
FR improve notification UX for past failed embeddings

### ISSUE THREAD

**Issue by brianpetro** [brianpetro/obsidian-smart-connections#41]
1) only one notification is necessary.
2) the notification should not appear if it has appeared with some time or based on some action. 

Re: https://github.com/brianpetro/obsidian-smart-connections/issues/13#issuecomment-1428676826

**Comment by omarali-koy** [comment]
Gotta agree, I'm getting the streams of notifications every time I'm opening a new note.

**Comment by fedderw** [comment]
Same, this is a bit excessive. :/
![image](https://user-images.githubusercontent.com/16396180/223214355-ce5d0619-0e17-4523-998d-7852224e2b2b.png)

Is there a way to suppress them?

**Comment by brianpetro** [comment]
@fedderw @omarali-koy 

This is patched in `v1.2.10` (just released)
