### ISSUE TITLE
Developer policies violation - Advertisement

### ISSUE THREAD

**Issue by joethei** [brianpetro/obsidian-smart-connections#419]
Hi @brianpetro,

We have received reports from several users that this plugin opens an unsolicited advertising popup. This goes against [Obsidian Developer Policies](https://docs.obsidian.md/Developer+policies) which forbid displaying such ads. The following popup should be removed.

> Show your support by sending a screenshot of your vote to brian@smartconnections.app and get early access to V2.0! Voting requires joinng the Obsidian Discord server, going to the 'Announcements' section and clicking the 'S' to vote. Note: The link above only works if you are already logged in to the Discord server.

Using popups outside of the plugin's interface is an unpleasant experience for users, and does not match the ethos of Obsidian.

Please remove the popup from your plugin within 2 days. If your plugin is not updated within this timeframe it will be removed from the community plugins directory. If the plugin is removed you can re-submit once it is in compliance with the Developer Policies.

**Comment by brianpetro** [comment]
@joethei First off, thank you for bringing this to my attention.

I've taken immediate action and removed the notification in the latest update, version `1.6.55`. My intention was never to disrupt the user experience or to go against the Obsidian ethos, which I deeply respect and admire.

The notification was designed with the best of intentions, but I understand how it might have been perceived differently. I apologize for any inconvenience caused and have made sure it won't happen again.

Could you kindly confirm that Smart Connections is now aligned with the Obsidian Developer policies? I'm eager to continue contributing positively to the community. Thanks again for your understanding and support.

**Comment by brianpetro** [comment]
@joethei just wanted to check in on this since the 2-day deadline is approaching.

Thanks for your help
🌴

**Comment by joethei** [comment]
Thanks.
