### ISSUE TITLE
FR: split embeddings file into smaller parts

### ISSUE THREAD

**Issue by dbobak** [brianpetro/obsidian-smart-connections#42]
When the embeddings file is tool large, it is problematic to sync it with github, which has a size limit of 100 MB. And it warns, if the file exceeds 50 MB. My embeddings file is 65MB. Maybe it would be possible to split large files into a smaller ones?

**Comment by brianpetro** [comment]
Hi @dbobak 

Yes, I've also considered splitting the files for other use cases.

In the meantime, if you have a `.gitignore` file, then the plugin should add the embeddings file to the ignore list by default. But if there isn't already a `.gitignore` file, it skips this step. 

I think you should ignore the file for now, if possible, to prevent issues like the one you're having.

Lastly, thanks for using the plugin and providing helpful feedback!

**Comment by ElanHasson** [comment]
You may want to try git-lfs: https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-large-files-on-github

Has a limit of 2+ GB: https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-git-large-file-storage

**Comment by brianpetro** [comment]
The latest versions of Smart Connect now save embeddings in a file for each note 🌴

**Comment by brianpetro** [comment]
Recorded response https://youtu.be/nK6oAUiz8w0
