### ISSUE TITLE
FR API key field should be hidden

### ISSUE THREAD

**Issue by ShravanSunder** [brianpetro/obsidian-smart-connections#43]
you should hide the text of the api key field.  

Below is an example

<img width="842" alt="2023-02-17 0239 Obsidian README - shravan-pkm - Obsidian v1 1 14" src="https://user-images.githubusercontent.com/5294949/219698684-19c6a131-3aec-49c3-ad23-ad6abd9dea26.png">

**Comment by brianpetro** [comment]
Indeed. Thanks for pointing this out!

**Comment by smartguy1196** [comment]
@ShravanSunder what plugin is that in the screenshot? Could you post the Github Link?

**Comment by ShravanSunder** [comment]
> @ShravanSunder what plugin is that in the screenshot? Could you post the Github Link?

its the text generator obsidian plugin.

**Comment by brianpetro** [comment]
![Screenshot 2024-06-27 100803](https://github.com/brianpetro/obsidian-smart-connections/assets/1886014/6b0c3949-4e1b-49c2-8fea-ea34f04a00d4)

Replaced API key text inputs with password inputs. This will be shipped in the next release 🌴

**Comment by brianpetro** [comment]
Recorded response https://youtu.be/y-HwBAmgZ0Q
