### ISSUE TITLE
Cannot login with Plugin (and I became a supporter and have the license key)

### ISSUE THREAD

**Issue by sradics** [brianpetro/obsidian-smart-connections#434]
I purchased a supporter today morning and purchased the license key. Unfortunately I cannot login to the plugin in ChatGPT via eMail address and license key. It say's - can't login to the plugin.

Also the button in Obsidian to sync notes seems not yet to be active. When I click the button nothing happens. 

The local embedding after upgrading to version 2.x worked.

**Comment by sradics** [comment]
I found the problem. I had in ChatGPT my language settings set to German and this cause the Can't login to the plugin. I switched now to US-english and it works

**Comment by brianpetro** [comment]
@sradics I'm happy to see that you figured it out!

In the future, please feel free to reply directly to the email with your supporter key for the fastest response.

Thanks for your support 😊

🌴
