### ISSUE TITLE
Exclude current note from related notes pane

### ISSUE THREAD

**Issue by oscaromsn** [brianpetro/obsidian-smart-connections#436]
Hi, Brian!

Thanks for your hard work — v2.0.95 is doing great here :)

Therefore, I've noticed that sometimes the sidebar suggests the currently open note, highlighting the headers. This is useful for large documents, but less so for workflows involving multiple small notes, where the goal is to find relationships between them:

<img width="590" alt="image" src="https://github.com/brianpetro/obsidian-smart-connections/assets/29803184/e01f788b-72bc-4ae8-afbb-d0d64b628f06"> **_(edited original request)_**

Could we have an option to configure this sidebar behavior in the future? Tailoring how notes are suggested, especially in smaller documents, would greatly enhance usability.

Thank you once again for your dedication to improving this awesome plugin!

**Comment by brianpetro** [comment]
Hey @oscaromsn 

Looking at your screenshot, are those two different notes? The "current note" appears to have a similar title as the results but with a preceding `(1) ` in the file name. 

> Could we have an option to configure this sidebar behavior in the future? Tailoring how notes are suggested, especially in smaller documents, would greatly enhance usability.

This is something I'm working on. Soon, there will be "filter options" in the view that will let you adjust how the results are generated. There are some feature requests labeled https://github.com/brianpetro/obsidian-smart-connections/labels/Smart%20View that fit in this category, and more feature requests will be added to that list shortly as I continue to review/manage all the feedback in the GitHub issues.

Any additional thoughts on what configuring the behavior might look like would be helpful.

Thanks for your help in making Smart Connections the best it can be!

🌴

**Comment by oscaromsn** [comment]
You're right — for some reason some notes of my vault was duplicated.

I just read the smart view request and seems really interesting.

Thank you!
