### ISSUE TITLE
Can smart connections be made to read images

### ISSUE THREAD

**Issue by punksterlabs** [brianpetro/obsidian-smart-connections#437]
It would be interesting if smart connections via OpenAI's API could read images.  Since the obsidian is a 'second brain' as such, it would make sense to store even images, research reports, statistics pages  etc.. would be amazing if Smart Connections could read those images and respond knowing the full context of all the notes in the vault

**Comment by brianpetro** [comment]
This is something I've been thinking about.

I'm still brainstorming what the UI/UX might look like.

Maybe something like treating images as blocks, and replacing images inside notes with the text returned by the AI?

I was also thinking that maybe Smart Connections could rename images, but this would be limited based on the length of a reasonable file name.

Any feedback on this would be appreciated!

Thanks for getting this discussion started @punksterlabs !

🌴

**Comment by punksterlabs** [comment]
Face detection, even people detection might be possible in a couple of years. Would be good to have family pics inside obsidian and tagging people in them. But for now, I even have use cases where I want to paste some of my trade logs/screenshots from Trading .. and then have GPT analyze them for mistakes, and patterns. Replacing image with text could be another use case that you have suggested. Renaming a picture too could be cool - something descriptive always helps.  

The UI could be one where once an image is posted and hovered on, there are a couple of options (Rename image based on AI, Convert image to text)  When someone wants to analyze the image separately like I want to do, it can be via the chat prompt

**Comment by laestrella26** [comment]
I would love for SC to OCR images. I use chatGPT for this all the time so it feels like the next logical step for it to also be able to search my handwritten notes.

**Comment by brianpetro** [comment]
@laestrella26 agreed.

I lot of what I've been working on in v2 from a backend/architecture standpoint will make implementing capabilities like this much more seamless.

Something I'm thinking about is deciding whether to go the traditional OCR route or to just jump right into using the multi-modal capabilities of the AI models.

I'm also thinking that enabling images to be processed by the chat will come sooner than a full embedding integration. This way you would be able to link to an image in the chat input similarly to linking to a note to use as context. I'm aiming for this in v2.2. 

🌴

**Comment by laestrella26** [comment]
I think just using the AI model's multimodal capabilities could be the way to go. It's basically already there in ChatGPT. Whenever I need to get my handwritten notes turned into text, I just ask ChatGPT and it does the job pretty well. So, it might be the simpler option right off the bat.

Glad to know this is something you’d like to see happen.

**Comment by brianpetro** [comment]
> Whenever I need to get my handwritten notes turned into text, I just ask ChatGPT and it does the job pretty well

Same! I used to pay assistants to help me with this, and ChatGPT tends to be more accurate than people who were familiar with my handwriting.

Multimodality will happen. At this point, my biggest question is about the UI/UX. How should multimodality be implemented beyond the Smart Chat?

🌴

**Comment by christianngarcia** [comment]
Image input is available in the v2.2 Smart Chat 🌸
