### ISSUE TITLE
Problems with API keys

### ISSUE THREAD

**Issue by lucadanu** [brianpetro/obsidian-smart-connections#44]
Hello , what's could be the problem if the plugin is not accepting any OpenAI APIs I add on the settings?

**Comment by brianpetro** [comment]
Are you in a region where OpenAI is available?

**Comment by Ikealightbulb** [comment]
Hi I have this error : "API key is not working as expected". 

I have access to Open AI, and ChatGPT.

**Comment by lucadanu** [comment]
Yes OpenAI is available where I am.. I get the same issue

**Comment by smartguy1196** [comment]
Be sure to spell check the key.

You can also use your key anywhere that takes one, so you may find another tool that takes open AI keys and try it there.

Also, check you rates/limits. The free Open AI key has a pretty low limit that you can hit pretty quickly, especially if you have a large vault

**Comment by lucadanu** [comment]
Ok thank you for you advice

**Comment by jakemkc** [comment]
Hi all,

I just tried to installed the plugin yesterday, and it works in a very random way for the first few minutes. Then it keeps saying "error getting embeddings for xxx". Smart Connections counts to around 3000 before showing me "error getting embeddings for xxx" and I believe my vault is not too large.

I tried to click the "test API key" button in plugin setting, and it said "API key is not working as expected".

Is there any solution to this?

**Comment by brianpetro** [comment]
The API key being expired would explain it. Can you try a new key?

**Comment by jakemkc** [comment]
I just tried a new key, and still the same, telling me "API key is not working as expected" after clicking the "test API key".

I have the free trial usage: $0.27 / $18.00, and it will expire on April 1, 2023.

**Comment by brianpetro** [comment]
Based on the free trial account, I'm thinking that it's probably a
rate-limit issue. Upgrading to a paid account should fix the problem (and
you will still be able to use the $18 credit).

Let me know if that works. If so, I'll have to look into it better
detecting this and providing clearer instructions to future users.

Thanks for your help in solving this issue!

**Comment by lucadanu** [comment]
I got the same problem with every plugin in Obsidian that use OpenAI API key.
I actually solve it by making a new OpenAI account associated to a different phone number.. It could be because the 18$ free plan doesn't exist anymore...now it's 5$

**Comment by brianpetro** [comment]
Good to know, thanks for the update @lucadanu

**Comment by jakemkc** [comment]
I see... As I don't have another phone number, so going to a paid account might be the only way to fix it.

**Comment by Teighe** [comment]
> Hi all,
> 
> I just tried to installed the plugin yesterday, and it works in a very random way for the first few minutes. Then it keeps saying "error getting embeddings for xxx". Smart Connections counts to around 3000 before showing me "error getting embeddings for xxx" and I believe my vault is not too large.
> 
> I tried to click the "test API key" button in plugin setting, and it said "API key is not working as expected".
> 
> Is there any solution to this?

I get this problem when it reviews my Tracker plugin code so I wonder if that's a possible hiccup.

**Comment by jakemkc** [comment]
I didn't do anything new and left it aside (still the same account, same API), and yesterday I discovered the list of failed file is much shorter than 4 days ago. I clicked "retry failed files only" and only 2 files were still in the list.

I don't exactly sure why this happened but it seems that if you just leave it there for a few days, the problem might be solved.

Jake

**Comment by brianpetro** [comment]
@jakemkc thanks for the update!

**Comment by FrankNJohnson** [comment]
Hi. I'm getting the "API key is not working as expected" message when I click the Test API Key button. The Smart control panel has a message that others have mentioned: "Smart Connections: API key is not working as expected!" And there a large number of my notes that failed to process when I tried to run the initial processing. If it matters, I'm a paid ChatGPT customer and I created the API key today before copying and pasting it into the Smart Connections settings panel. Thanks in advance for any help you can offer - much appreciated!

**Comment by brianpetro** [comment]
@FrankNJohnson thanks for letting me know.

I think the issue is that you still need to setup billing in your OpenAI account to raise the rate-limit. This is a separate billing system from the ChatGPT Plus subscription.

Also, it may take some time for the rate limits to be lifted once you setup that billing. But it seems to usually happen within a few hours.

Thanks for trying out the plugin and let me know if that ends up helping you get started.

**Comment by FrankNJohnson** [comment]
Thanks @brianpetro - that was the problem. I have it working now. Pretty cool!

**Comment by brianpetro** [comment]
@FrankNJohnson great!

Also, I've been making lots of updates and will continue to, so be sure to check for updates frequently.

Thanks for using the plugin!

**Comment by freqyfreqy** [comment]
I get the same error. Is there anyway to find out if I have hit the rate limit? I don't have paid access.

**Comment by brianpetro** [comment]
@freqyfreqy if you don't have paid access then it's almost definitely the rate limit.

**Comment by freqyfreqy** [comment]
Thank you! I'll do that!

**Comment by liuling73** [comment]
Can you please tell me the specific steps to set up billing in my OpenAI account? Do I need to be a paying user to do this? Currently, I am using a free account with a remaining balance of $4. Thank you.

**Comment by brianpetro** [comment]
@liuling73 a credit needs to be added to the billing section of your account to be considered a paid account.

🌴

**Comment by liuling73** [comment]
@brianpetro ,I didn't find specific methods and steps for adding, could you please provide detailed instructions? Thank you.

**Comment by liuling73** [comment]
![图片](https://github.com/brianpetro/obsidian-smart-connections/assets/147953750/73fe96b6-2b51-4097-9b73-09897ffd294b)
@brianpetro

**Comment by brianpetro** [comment]
Go-to payment methods on the screen you shared @liuling73
