### ISSUE TITLE
Empty `embeddings-2.json` (1KB)

### ISSUE THREAD

**Issue by hewcaw** [brianpetro/obsidian-smart-connections#45]
Probably similar to #32, #33, I'm currently using Windows 11. Luckily I don't have a lot of notes (~50) with average around 10000 characters (majority are Journals), so I only lost average around 200K tokens every time it re-indexing, LOL 😅

**Comment by brianpetro** [comment]
Hi @hewcaw 

In version `1.2.1` I added a "test writing file" feature to the settings. If the writing fails, that button should return an error you can report here so that I can further debug this. 

Thanks for your help in figuring this out!

**Comment by brianpetro** [comment]
Version `1.2.2` includes a "Manual Save" button in the settings. If it fails, it should return an error that can be used for further debugging.

**Comment by brianpetro** [comment]
This should be fixed as of version `1.2.4`. Thanks for your help!
