### ISSUE TITLE
always embeding again and again

### ISSUE THREAD

**Issue by KuecukMimarBey** [brianpetro/obsidian-smart-connections#455]
always when i open up obsidian, it is embeding the same notes or blocks again and again and again
without me even creating new notes and in the case it should only sync/embed what is newly created or edited ?

i turned of smart connections because it blocks me from working in obsidian - my pc is not the newest or the best, i will wait till you solved this issue

**Comment by brianpetro** [comment]
Hi @KuecukMimarBey 

Thanks for bringing this to my attention.

Can you check the developer console and send me a screenshot?

My guess is that there is an issue with saving, and the logs should show why.

Thanks for your help in solving this!

🌴

**Comment by KuecukMimarBey** [comment]
how can i contact you and send you the screenshots ?

**Comment by brianpetro** [comment]
@KuecukMimarBey you could upload them here or send to Brian at smartconnections.app

**Comment by KuecukMimarBey** [comment]
![IMG_20240207_194017.jpg](https://github.com/brianpetro/obsidian-smart-connections/assets/113188984/bfe0d52a-9d41-4dfa-b5c8-8e487e6d8bdb)

![IMG_20240207_193955.jpg](https://github.com/brianpetro/obsidian-smart-connections/assets/113188984/570d8991-ab86-431b-a553-f01015b7bf5a)

ok here

**Comment by KuecukMimarBey** [comment]
i will look into it and give you feedback here, sorry for the mistake, i had definitely problems with smart connections

**Comment by brianpetro** [comment]
@KuecukMimarBey thanks, I'm going to close this issue for now.
