### ISSUE TITLE
Request. Is there a way to add Gemini-API?

### ISSUE THREAD

**Issue by bbecausereasonss** [brianpetro/obsidian-smart-connections#456]
Not even sure if it's possible yet... but I just tested Gemini Ultra for 2 hours, and it absolutely BLEW my mind. It knocks ChatGPT out of the water on analysis, writing, and cognition.

**Comment by brianpetro** [comment]
@bbecausereasonss good to know! I'll have to look into it. 

What were you using to test it?

🌴

**Comment by bbecausereasonss** [comment]
Just the web interface, a long with a bunch of reasoning questions. Work on
branding, copy, and complex problems. Looking for creativity, comprehensive
outlines, concept formulation, structure and cognition.

I came in skeptical but was very impressed.

**Comment by antonioaraujo664** [comment]
I was also skeptical...it's better than gpt chat. I would also like to see Gemini in action.

**Comment by alexmhoward3** [comment]
Second this. I’d love to see gemini’s 1 million token context window put to the test in my vault.

**Comment by brianpetro** [comment]
@alexmhoward3 the million context model still isn't generally available, but I'd also love to test it once it is!

**Comment by brianpetro** [comment]
@bbecausereasonss `v2.1` will go into beta/early release with supporters this week; it includes Claude and Gemini.

**Comment by bbecausereasonss** [comment]
> @bbecausereasonss `v2.1` will go into beta/early release with supporters this week; it includes Claude and Gemini.

Oooh, exciting!

**Comment by brianpetro** [comment]
@alexmhoward3 thanks for the bug report! In a major release like `v2.1`, there are simply too many edge cases for me to test. So, I rely on reports like this 😊

The bug should now be fixed 🛠️

Next time you restart the plugin or Obsidian, the Smart Connections early-release version should automatically update to `v2.1.3`.

🌴
