### ISSUE TITLE
"Make Smart Connections" command results are not sorted

### ISSUE THREAD

**Issue by fredb1106** [brianpetro/obsidian-smart-connections#457]
Since v2, when editing a note and running the "Smart Connections: Find: Make Smart Connections" command to refresh related notes, the results in the "Smart Connection Files" pane are not sorted down by score as they should. They are showing in random order. I would expect them to be sorted descending, the same way the are when we load a note.

I'm guessing the code is just missing a sort() before displaying results?

Thanks!

![results](https://github.com/brianpetro/obsidian-smart-connections/assets/57445292/261ed569-effd-4d87-aab5-3aa6a87df47a)

**Comment by brianpetro** [comment]
Hi @fredb1106 

I believe this issue has been fixed in a later version.

Is it working for you now?

🌴

**Comment by fredb1106** [comment]
Yes it works now, thanks.
