### ISSUE TITLE
I like the idea!

### ISSUE THREAD

**Issue by Ikealightbulb** [brianpetro/obsidian-smart-connections#47]
Thanks for doing this. I love the idea to have OpenAI help look through my notes to find connections. 

So, I'm a noob. I don't know why my notes are "excluded". 

What is happening? haha
Regards

**Comment by brianpetro** [comment]
Hi @Ikealightbulb 

Re: https://github.com/brianpetro/obsidian-smart-connections/issues/44#issuecomment-1454729161 I wonder why your API key isn't working. But that's why the plugin is stuck on "Making smart connections...N" (I see you edited your post so I hope you got that solved!)

The excluded message occurs when the current note matches any patterns configured in the "Exclusions" section of the settings.

**Comment by Ikealightbulb** [comment]
Thanks Brian. 

Yes, the first issues has been resolved because I have ran out of credit :)

Excluded error. 
- Under "file_exclusions" I entered _morning pages,_. because I use obsidian as my morning pages journal. I title those notes as "Morning pages for xxxxx" Is that the way?

**Comment by brianpetro** [comment]
Your whole vault will be processed once when you first install the plugin. individual notes will also be re-embedded when you make substantial changes to them. While the logic is a bit more nuanced than this, essentially, your notes shouldn't be processed more than once unless you make substantial changes to them. 

Changing the note folder will re-embed the note. And if you rename a folder, all notes contained in the folder will be re-embedded. 

Changing a sentence in a note will re-embed a part of the note, but the note as a whole will only be re-embedded if the size of the note changes by >10%.

I'm still working on improving the speed of the plugin, particularly when you open a new note. Currently, to prevent outdated results, the whole vault is checked for changes each time a note is opened. This is mostly what's happening when you see "Making Smart Connections..."

If you want to learn more about what's happening in your vault, you can toggle on the "render logs" settings and keep the console log open. This will display your token usage, which notes are being embedded, and some other usage stats.

**Comment by Ikealightbulb** [comment]
I think it’s fantastic that you are doing this. It’s hard work to code and create stuff. I’m not a programmer. not too technical. Haha I appreciate what you are doing here. Thanks for building this plug in to make obsidian even more useful. Thank youOn 4 Mar 2023, at 10:48 PM, Brian Petro ***@***.***> wrote:﻿
Your whole vault will be processed once when you first install the plugin. individual notes will also be re-embedded when you make substantial changes to them. While the logic is a bit more nuanced than this, essentially, your notes shouldn't be processed more than once unless you make substantial changes to them.
Changing the note folder will re-embed the note. And if you rename a folder, all notes contained in the folder will be re-embedded.
Changing a sentence in a note will re-embed a part of the note, but the note as a whole will only be re-embedded if the size of the note changes by >10%.
I'm still working on improving the speed of the plugin, particularly when you open a new note. Currently, to prevent outdated results, the whole vault is checked for changes each time a note is opened. This is mostly what's happening when you see "Making Smart Connections..."
If you want to learn more about what's happening in your vault, you can toggle on the "render logs" settings and keep the console log open. This will display your token usage, which notes are being embedded, and some other usage stats.

**Comment by sam1am** [comment]
Hopping on to also say thanks. I have been wanting this feature in something ever since reading about tad starners remembrance agent in the 90s! And this is even better.

**Comment by smartguy1196** [comment]
@brianpetro do you have a supporter link? This plugin is fantastic

**Comment by brianpetro** [comment]
@smartguy1196 thank you 🙏 

The best way to support me is by referring anyone who might be interested in hiring me as a consultant to this page https://wfhbrian.com/build-with-ai/
