### ISSUE TITLE
Connection Pane Not Displaying Text of the Connections

### ISSUE THREAD

**Issue by pacificera** [brianpetro/obsidian-smart-connections#474]
Hi.  I'm using 2.0.115.  I've installed the plugin, generated embeddings, and I can get the converse with notes feature to work.  The smart connections functionality is not working.  The connections pane is visible and the words and character count at the bottom is updating status as I type in my note.  However, no text is appearing in the connection pane interior:

![image](https://github.com/brianpetro/obsidian-smart-connections/assets/1159820/2b80537b-7ed9-4f1f-b9f5-bb4205e0d1f1)

Looks like a great plugin.  Thank you for you help getting set up.  Please let me know if I can provide any additional details.

**Comment by brianpetro** [comment]
@pacificera thanks for the report.

Can you open the developer console and screenshot any errors that might be there? 

🌴

**Comment by g1021895463** [comment]
I also have the same problem
![屏幕截图 2024-05-10 055129](https://github.com/brianpetro/obsidian-smart-connections/assets/48684308/43a96372-c850-4c5e-bca5-cbe07183ffe3)

**Comment by brianpetro** [comment]
Hi @g1021895463 

Thanks for the screenshot.

Was this working for you before?

And which version are you using?

Thanks for your help in getting this solved
🌴

**Comment by g1021895463** [comment]
正常工作在1.6版本
在升级到2.0版本后出现问题
截图中我使用的是2.1.59版本

**Comment by brianpetro** [comment]
@g1021895463 did you recently upgrade from `v1`?

**Comment by g1021895463** [comment]
Today, after upgrading from v1.6 to v2.1.59, I encountered this issue.

**Comment by brianpetro** [comment]
@g1021895463 try uninstalling Smart Connections, then re-installing.

Since that version was from so long ago, there could be old configurations that cause issues. 

Let me know if that works
🌴

**Comment by g1021895463** [comment]
在将obsidian更新到1.5.12后解决了该问题，我之前使用的obsidian版本是1.4.16
现在正常工作
