### ISSUE TITLE
iPad support

### ISSUE THREAD

**Issue by sam1am** [brianpetro/obsidian-smart-connections#49]
I see an error saying my platform is not supported. I'm on  an iPad.

**Comment by dvansoye** [comment]
Will Android also be supported? I do all of my work on Android.

**Comment by brianpetro** [comment]
@dvansoye yes!

**Comment by brianpetro** [comment]
Mobile (iPad & Android) is in beta-testing in v2.2 https://twitter.com/wfhbrian/status/1788293763892191528 👀
