### ISSUE TITLE
Smart Chats does not seem to be working + keeps asking are you ready for embeddings 

### ISSUE THREAD

**Issue by DantesHub** [brianpetro/obsidian-smart-connections#501]
![CleanShot 2024-03-03 at 16 06 47@2x](https://github.com/brianpetro/obsidian-smart-connections/assets/51376601/8bd6f9af-600b-4183-bd8a-78ada7da7f94)

Chat simply doesn't respond no matter what I ask it.
It keeps asking are you ready for embeddings even though I loaded them in from before.

**Comment by brianpetro** [comment]
Hey @DantesHub 
That error is weird because the "new worlds" plugin is erroring within a Smart Connections function. So turning it off might solve the issue if it's one of comparability.

Can you test if it works after turning off the "new worlds" plugin?

🌴

**Comment by DantesHub** [comment]
Thank worked! Thanks @brianpetro
