### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by supertom44** [brianpetro/obsidian-smart-connections#506]
Hey,

I've just installed the plugin, set up my api key, however whenever I try to open any of the views nothing happens.

Checked out the cosole and saw this error:
`"Uncaught TypeError: Cannot read properties of null (reading 'on')"`

Full error attached, sorry for some reason the console would not let me take a copy of the error.
![Error](https://github.com/brianpetro/obsidian-smart-connections/assets/6057877/c45d3a1e-0573-49bc-abd1-2bbc06ed335d)

Let me know if you need any further information.

Cheers.

**Comment by brianpetro** [comment]
Hi @supertom44 

Thanks for the report. And thanks for the screenshot, it makes things a lot easier for me to debug.

All of those errors should be OK.

Most are for the local embedding model, which uses transformers.js. But those errors don't prevent anything for working as expected. 

The websocket error is something I need to clean up but similarly shouldn't impact anything.

If you changed any of the models in the settings, then restarting the plugin or Obsidian is often necessary for them to take effect (will be fixed soon so no restart is required).

When you say "nothing happens", does a blank window appear in the sidebar? Or is not view being created at all? If it's the latter, then some new error should appear when you try to open the view.

If it is a blank window, then it may be that the embeddings aren't ready yet. The "Refresh Notes" button in the settings will start the embedding process wherever it may have left off. Be aware that when using local models Obsidian will likely become unusable during the process (something I'm currently remedying by offloading to the Smart Connect software that's currently in beta testing with supporters). 

If none of the above gets things moving, a screenshot of the Smart Connections settings is often helpful so I can test your specific configuration on my side, and often times errors are specific to one of the many possible variations.

Thanks for trying Smart Connections and your help in solving this issue
🌴

**Comment by supertom44** [comment]
Oh wow, turns out I'm not smart enough to use smart connections (joke).

I forgot I'd minimised the sidebar to give me more room while making some notes.

Sorry, thanks for the detailed response, much appreciated.
