### ISSUE TITLE
"Maximum context length is 4097 tokens"

### ISSUE THREAD

**Issue by leips** [brianpetro/obsidian-smart-connections#51]
Hello, 

I have this error. I understand that is a limit about ChatGPT API. There's something we can do about the limit? Try to use FASS as an index and split the chunks?

Thanks!

**Comment by brianpetro** [comment]
Hey @leips , thank you for taking the time to bring this to my attention!

Are you able to take a screenshot of the error in the console?

Is this happening after the first, or many, messages?

Thanks for your help in solving this issue :)

**Comment by leips** [comment]
The screenshot,

![imagen](https://user-images.githubusercontent.com/10269268/225685054-43baa04b-d741-4749-8ad0-d30e60625b9c.png)

I try with a few notes, everything works, but after I put the of the notes in my vault (500 notes) this error appears every time I'm asking something about the notes.

**Comment by leips** [comment]
Same error after click the plus sign. 

> Can you clarify what you mean by this?

I made two test. First, with a few notes, everything works. Second, with a 500 notes. After refresh the embeddings, this message appears when I ask something.

**Comment by brianpetro** [comment]
Is the 500 note vault something you'd be comfortable sending me so I can test it out? Otherwise I'll have to think on it a bit, not sure what's up. brian@plexm.com

**Comment by brianpetro** [comment]
@leips I think I might have an idea what's up.

Do you have some really long notes? Maybe ones that don't use a lot of headings? Like, large text blocks (>1000 chars) without and headings?

If so, the logic for limiting lengths of notes in the context window is probably the problem. 

This is something that I can improve to better handle cases like I mentioned above. 

Thanks for your help in figuring this out!

**Comment by rotello** [comment]
I am doing more test. it seems that the kindle clipping are working, while the mobi / loooong form MD i imported (it s basically a full book i ve ) is not indexed. I ve not got any error.
I updated the plugin. closed the Vault and it seems to work. I am excited
<img width="913" alt="Screenshot 2023-03-17 at 20 17 27" src="https://user-images.githubusercontent.com/2255620/225999187-40243025-16fd-4a93-b987-e7840f236cfe.png">

**Comment by brianpetro** [comment]
> I am doing more test. it seems that the kindle clipping are working, while the mobi / loooong form MD i imported (it s basically a full book i ve ) is not indexed.

Great to know, thanks! This type of feedback is really helpful.

In the background, "parsing," breaking the notes into logical chunks, plays a big role in the plugin's effectiveness. So less common formatting is more likely to run into issues.

I do have a lot of improvements I want to make to the parser. A lot of them are designed to handle long-form content better. So, in time, the plugin will improve at handling these cases.

Lastly, I know it's incredibly frustrating when software doesn't work as expected, and it's easier to walk away than to contribute to its improvements. So thanks again for your continued assistance!

Brian 🌴

**Comment by rotello** [comment]
Thank for bearing my obnoxiousness :-)

**Comment by smartguy1196** [comment]
@rotello _should we start a club? maybe a support group..._ __"Brian Petro's Annoying Fans Anonymous"__

**Comment by rotello** [comment]
i think we could :-P

**Comment by brianpetro** [comment]
I really appreciate it, but also couldn't imagine keeping this thing going if it weren't for such enthusiastic and helpful people like yourselves. Thank you 👏

**Comment by smartguy1196** [comment]
Issue reported again in comment: https://github.com/brianpetro/obsidian-smart-connections/issues/88#issuecomment-1483841621

**Comment by dartungar** [comment]
Yeah, for sake of convenience here is my comment:
![image](https://user-images.githubusercontent.com/36126057/227779562-27b37855-f18b-4de3-a504-440ce653d644.png)

**Comment by brianpetro** [comment]
@dartungar which language is this occuring with?

I have two ideas for changes that will both contribute to solving this:

There is now a language setting in Smart Connections, and with that, we can adjust how the tokens are estimated. Some languages use characters that make the "divide by 4" estimate unreliable. This calculation should be easy to adjust based on the language selected in the settings. 

Additionally, I plan on implementing a method to catch this error, reduce the amount of context, and resubmit the request automatically. This should prevent bad estimates from causing a fatal error like this.

After making those two changes, I think this issue will be solved.

**Comment by dartungar** [comment]
@brianpetro well, most of my notes are in Russian (hope that doesn't put you off! 😶 ). That does seem like a potential cause, will check the new setting. Cheers!

**Comment by brianpetro** [comment]
Closing in favor of this FR  #126
