### ISSUE TITLE
Issues with Claude

### ISSUE THREAD

**Issue by bbecausereasonss** [brianpetro/obsidian-smart-connections#529]
Been using Claude for it's increased context and better ability to analyze, but also been getting a lot of API errors. For instance, asking it a question about (all of my notes).

Often get 'overloaded'

![image](https://github.com/brianpetro/obsidian-smart-connections/assets/20264016/752466f8-7331-468a-93fc-2f7d1f703fc9)

**Comment by brianpetro** [comment]
That done handler error is interesting.

Unfortunately, the overloaded error is something on Anthropic's side. I was expecting it to happen less frequently as they improve their servers. If it keeps happening though, we can implement a catching mechanism that would automatically retry the request. 

Once `v2.1` is public, the code will be open-source and handling that error would be an easy contribution. 

🌴

**Comment by bbecausereasonss** [comment]
Seems it could be related to context length, as longer queries and querying (all my notes) seems to do this more often. Right now it's giving me that error 99% of the time on querying my entire notes.

**Comment by brianpetro** [comment]
@bbecausereasonss given the "overloaded" part, it would make sense that the error occurs more frequently when larger context/input is used.

🌴

**Comment by bbecausereasonss** [comment]
Seems I only had $5 in my account left... Claude is incredible, and its also HELLA expensive. I spent $25 USD within 2 weeks doing some podcast summaries/take-aways. wtf?

**Comment by brianpetro** [comment]
@bbecausereasonss wow, that's a lot.

My favorite Claude model is haiku, which is also the cheapest. It may not be best for strict summarizing, but since it still has the 200K content window I find that it's great when exploring with the Smart Chat. 

🌴
