### ISSUE TITLE
Something that would be very helpful 

### ISSUE THREAD

**Issue by dvansoye** [brianpetro/obsidian-smart-connections#54]
I recommend doing a video for this plugin. I'm sure you're busy. Perhaps we could find an Obsidian evangelist to help. If you would like help finding one, let me know. This is a terrific idea, Brian. I would like to help you find some additional traction.

**Comment by rotello** [comment]
If i succeed and have it working. i ll gladly do once, which will be ugly but will maybe help newbie like me. This plugins could be a  Game changer!

**Comment by brianpetro** [comment]
Thank you both @dvansoye and @rotello

I could absolutely 1000% use all the help I can get.

Please don't hesitate to make them and post them here on GitHub, and from there I will do my best to make sure the right people see them, from posting to social medias and even including here in the README.

And @rotello we will get this working for you soon! I have some ideas from other threads/issues that might be causing the problem. I will be following up shortly!

**Comment by rotello** [comment]
@brianpetro - with the latest update it s working! and the "indexing" is super fast, too. I will test a couple of days with proper notes and I will make a video about it (in Italian to start)

**Comment by brianpetro** [comment]
> I will test a couple of days with proper notes and I will make a video about it (in Italian to start)

@rotello That would be incredible. Thank you🙏

Brian🌴

**Comment by dvansoye** [comment]
Ok. I just added a comment to the following YouTube video to see if it results in a video. I'll let you know if I get a response. https://youtu.be/Lq33gNpeDkE

Hi Nicole. Great video and perfect for anyone interested in obsidian. The quality of your work product is amazing. I truly look forward to your videos.

Question: how do you see things changing with the addition of AI? I'm currently using Text Generator to access GPT-3.5 from within Obsidian. But now with the introduction of obsidian-smart-connections, I'm seeing the ability to "Chat"  with my vault as a real possibility. Any chance we'll see a video on this in the near future?

**Comment by ObsidianTTRPGProject** [comment]
FYI - This guy is currently planning a video. 
https://www.youtube.com/channel/UCoW2sPmrevk9eiJKcQXeHUQ

**Comment by brianpetro** [comment]
Recorded response https://youtu.be/wYB37QluwGg
