### ISSUE TITLE
The setting page is blank in the 2.1.47 version

### ISSUE THREAD

**Issue by Ziilongg** [brianpetro/obsidian-smart-connections#555]
I attempted to switch the interface language to English, yet the screen remains blank. Additionally, I’ve tried reinstalling this plugin and disabling other plugins without success.

![image](https://github.com/brianpetro/obsidian-smart-connections/assets/45441835/c4df3d6e-3163-40e7-8ed8-c238211d9a95)

Can't wait to use gemini in the newest version 🤩🤩

**Comment by brianpetro** [comment]
Hi @Ziilongg 

I'm happy that you're excited about the update and I look forward to getting things fixed so you can try Gemini.

It would be helpful if you could open the developer console, disable and re-enable Smart Connections, then try to access the settings again, and screenshot the logs, which should show us some errors.

Before doing this, please turn on the "Debug at startup time" setting in the Obsidian Community plugin settings. This will help make sure the logs are as detailed as possible.

Thanks for your help in figuring this out,
🌴

**Comment by Ziilongg** [comment]
Thank you for the fast response.

Here is the screen shot of the errors. I didn't find how to export these logs into TXT.   Hope these screenshots will help.

![image](https://github.com/brianpetro/obsidian-smart-connections/assets/45441835/e0a45b3a-5f2f-452d-9b11-d21703a071e6)
![image](https://github.com/brianpetro/obsidian-smart-connections/assets/45441835/9c65cdfd-c992-4987-8591-f676e25cf279)
![image](https://github.com/brianpetro/obsidian-smart-connections/assets/45441835/b404645a-44cb-4fe9-b30e-b49a3b31df13)

---

![image](https://github.com/brianpetro/obsidian-smart-connections/assets/45441835/f8b96e62-8d13-40f6-97eb-6cde2be305b9)

**Comment by jiashengnote** [comment]
Same problem:
<img width="567" alt="image" src="https://github.com/brianpetro/obsidian-smart-connections/assets/165744986/83e94d4f-fe25-4ef4-a861-a10a3c69c0f4">

**Comment by jiasheng55** [comment]
Same issue:

![image](https://github.com/brianpetro/obsidian-smart-connections/assets/11782480/55228e03-0d83-40a8-b697-d7f927c6e1e5)

**Comment by brianpetro** [comment]
@Ziilongg 

> I didn't find how to export these logs into TXT. Hope these screenshots will help.

Screenshots are best, thank you.

@jiasheng55 As mentioned by @CharMingF, if you click the settings tab again after a few seconds, it should load properly. This is because some of the settings depend on the plugin being loaded. I'll have to look into this further. But it should work if you just wait a few seconds and then try to open the settings again.

@Ziilongg do the settings start working for you after waiting and then trying to open them again?

**Comment by jiasheng55** [comment]
@brianpetro 
Seems not working for me :(
I tried switch back and forth, but the console kept logging error message:
"Cannot read properties of undefined (reading 'platforms')"

**Comment by brianpetro** [comment]
@jiasheng55 the latest version `2.1.49` should fix this.

If you're still having issues after updating:

> It would be helpful if you could open the developer console, disable and re-enable Smart Connections, then try to access the settings again, and screenshot the logs, which should show us some errors.

> Before doing this, please turn on the "Debug at startup time" setting in the Obsidian Community plugin settings. This will help make sure the logs are as detailed as possible.

Thanks for your help in figuring this out,
🌴

**Comment by CharMingF** [comment]
Supplement, that is, when opening for the first time, it may be due to automatic calculation of notes, resulting in stuck interface, after the plug-in can be started, the user can set up and then manually calculate (I am an old user, I do not know if new users will have any difference)

**Comment by Ziilongg** [comment]
> @jiasheng55 the latest version `2.1.49` should fix this.
> 
> If you're still having issues after updating:
> 
> > It would be helpful if you could open the developer console, disable and re-enable Smart Connections, then try to access the settings again, and screenshot the logs, which should show us some errors.
> 
> > Before doing this, please turn on the "Debug at startup time" setting in the Obsidian Community plugin settings. This will help make sure the logs are as detailed as possible.
> 
> Thanks for your help in figuring this out, 🌴

It works! Thank you!

**Comment by jiasheng55** [comment]
@brianpetro it's working now, great!

**Comment by Ziilongg** [comment]
I found that the 2.1.50 version doesn't work on my PC in the lab, but it works on my PC at home.
Right now, I deleted the ".smart connections" folder (whose time was a week ago) under the Vault folder and reinstalled the plugin.
It finally works.  🤣🤣😘
