### ISSUE TITLE
In custom Server , No api_key field?

### ISSUE THREAD

**Issue by CharMingF** [brianpetro/obsidian-smart-connections#557]
![image](https://github.com/brianpetro/obsidian-smart-connections/assets/7530342/fa841e65-21c7-4c8f-9a0a-141a572e02b3)
Where can I enter api fields ？

**Comment by brianpetro** [comment]
Hi @CharMingF 

The latest version, `2.1.48` adds the API key setting.

🌴

**Comment by CharMingF** [comment]
> Hi @CharMingF
> 
> The latest version, `2.1.48` adds the API key setting.
> 
> 🌴

Thank you ,but the url is not  correct.
![image](https://github.com/brianpetro/obsidian-smart-connections/assets/7530342/84a326b1-30b5-41d3-92e3-f76e32ffd57f)

![image](https://github.com/brianpetro/obsidian-smart-connections/assets/7530342/d204efbb-b9ac-4c1f-a8e0-b8c73793a9c4)

**Comment by brianpetro** [comment]
@CharMingF thanks for the update. I'll have a fix shortly 🌴

**Comment by brianpetro** [comment]
@CharMingF this should be fixed in `v2.1.50`. Let me know if it works! 🌴

**Comment by CharMingF** [comment]
> @CharMingF this should be fixed in `v2.1.50`. Let me know if it works!🌴

It works!!
Thank you very much, I can use it, you are really too fast！！

**Comment by brianpetro** [comment]
😊🌴
