### ISSUE TITLE
Using gpt-4-0314

### ISSUE THREAD

**Issue by morethanx** [brianpetro/obsidian-smart-connections#56]
Hi there, I love the idea. Thank you. For someone who is not a coder, but luckily got access to the API, this helps a lot. Would it be possible to also be able to use the other GPT-4 models with my GPT-4 API like 'gpt-4-0314'?

**Comment by mickmel** [comment]
> Hi there, I love the idea. Thank you. For someone who is not a coder, but luckily got access to the API, this helps a lot. Would it be possible to also be able to use the other GPT-4 models with my GPT-4 API like 'gpt-4-0314'?

I'm using GPT-4 on ChatGPT, and I have the API connected to Smart Connections, but I can only get it to work with 3.5 on there. If I change it to 4 I always get "the model 'gpt-4' does not exist". Any idea what I might be missing there?

**Comment by brianpetro** [comment]
@morethanx In the settings, there is the option to use GPT-4. 

It uses the latest available GPT-4 model. Currently, that is `gpt-4-0314`.

**Comment by brianpetro** [comment]
@mickmel There's a waitlist for API access to GPT-4. Here's [the link](https://openai.com/waitlist/gpt-4-api).

**Comment by mickmel** [comment]
> @mickmel There's a waitlist for API access to GPT-4. Here's [the link](https://openai.com/waitlist/gpt-4-api).

Cool, thanks! I figured I was missing something, but didn't know what. I'm on the list now.
