### ISSUE TITLE
Getting a 429 error when trying chat

### ISSUE THREAD

**Issue by hay** [brianpetro/obsidian-smart-connections#565]
Hey,
i've just installed version 2.1.50 on a vault with about 2000 notes. Files works fine, but when i'm trying the chat i'm getting an "API Error. See console logs for details.". In the console i'm seeing a 429 error from openrouter, indicating "Rate limit exceeded: free-models-per-day". I'm not sure what to do, do i need to make an API key first at Openrouter to use this feature? Or is there something else i need to configure to make this work? I tried searching for this issue here and in the README, but it seems this wasn't mentioned yet.

**Comment by brianpetro** [comment]
Hey @hay 

Yes, you'll need to make an API key with Open Router to continue using their models if you're seeing that rate limit error.

🌴

**Comment by hay** [comment]
Great, thanks!
