### ISSUE TITLE
allow to open links in new tab

### ISSUE THREAD

**Issue by axaluss** [brianpetro/obsidian-smart-connections#569]
smart connection files always opens the link in the current tab.

It would be nice to be able to use middle mouse button as well as  cmd/ctrl+click to open the link in a new tab.

That's how browsers commonly let users interact with links as well.

**Comment by brianpetro** [comment]
Hey @axaluss 

Thanks for letting me know that you're having trouble with this.

Are you referring to the Smart View or the Smart Chat?

That functionality seems to be working for me in both.

I wonder what might be happening 🤔

🌴

**Comment by axaluss** [comment]
"smart connections Files"

lmb and ctrl+lmb work (open the file) only when the entry is expanded. other wise it only expands the entry. mmb does not work at all.

**Comment by axaluss** [comment]
my plugins: 
[
  "obsidian-advanced-uri",
  "auto-classifier",
  "auto-glossary",
  "canvas-filter",
  "obsidian-checklist-plugin",
  "code-styler",
  "copilot",
  "obsidian-custom-frames",
  "dataview",
  "obsidian-day-planner",
  "obsidian-dictionary-plugin",
  "cm-editor-syntax-highlight-obsidian",
  "obsidian-find-and-replace-in-selection",
  "obsidian-full-calendar",
  "homepage",
  "obsidian-kanban",
  "obsidian-linter",
  "mermaid-tools",
  "obsidian-mind-map",
  "nldates-obsidian",
  "oz-image-plugin",
  "periodic-notes",
  "obsidian-read-it-later",
  "obsidian-reminder-plugin",
  "obsidian-rollover-daily-todos",
  "tag-wrangler",
  "obsidian-tagfolder",
  "obsidian-tasks-plugin",
  "obsidian-version-history-diff",
  "obsidian-task-archiver",
  "obsidian-pandoc",
  "obsidian-regex-replace",
  "quickadd",
  "omnisearch",
  "obisidian-note-linker",
  "obsidian-latex",
  "obsidian-emoji-toolbar",
  "dbfolder",
  "table-editor-obsidian",
  "obsidian-auto-link-title",
  "workspaces-plus",
  "numerals",
  "meld-calc",
  "smart-connections",
  "darlal-switcher-plus"
]

**Comment by axaluss** [comment]
core:
[
  "file-explorer",
  "global-search",
  "switcher",
  "graph",
  "backlink",
  "canvas",
  "outgoing-link",
  "tag-pane",
  "page-preview",
  "templates",
  "note-composer",
  "command-palette",
  "editor-status",
  "bookmarks",
  "outline",
  "word-count",
  "workspaces",
  "file-recovery",
  "sync"
]

**Comment by brianpetro** [comment]
Hey @axaluss 

It looks like I over looked the CTRL+click UX for when the result was collapsed. 

It's been implemented in `v2.1.53`

🌴

**Comment by Hunter-Bobeck** [comment]
I'm in `v.2.1.72` on Windows 10 but middle clicking on the Smart View items results in the mouse scroll cursor changing on my mouse, rather than opening the titled note in a new tab. I would prefer to use middle clicking over CTRL clicking.

**Comment by brianpetro** [comment]
Closing this as complete since CTRL+Click works.

@Hunter-Bobeck I thought middle click should work because https://docs.obsidian.md/Reference/TypeScript+API/Keymap/isModEvent is used to detect the CTRL/CMD + Click, and it mentions detecting middle click. However, since it's not working, you may want to make a feature request for the middle button click, and also a feature request for any other ideas you might have to improve the UI 🌴
