### ISSUE TITLE
Keeps prompting to delete 60% of embeddings

### ISSUE THREAD

**Issue by andreicozma1** [brianpetro/obsidian-smart-connections#571]
Every time I open Obsidian, Smart Connections keeps prompting me if I'm sure I want to delete 60% of embeddings, but I didn't ask it to delete anything.

<img width="648" alt="image" src="https://github.com/brianpetro/obsidian-smart-connections/assets/14914491/2ea0f217-2c9c-4384-a009-46d38bdf2af1">

**Comment by andreicozma1** [comment]
Thank you! I already am on the latest version where I still experience those
I will try out the experimental option to see if it changes anything and report back

**Comment by andreicozma1** [comment]
The issue seems fixed after the newest update, v2.1.54 (at least it seems fixed on my MacBook).
I'll double-check on my PC as well and re-open if the issue comes back.

**Comment by brianpetro** [comment]
@andreicozma1 thanks for the update 😊🌴
