### ISSUE TITLE
Re-embed smart notes every time I change machine.

### ISSUE THREAD

**Issue by DarioRugg** [brianpetro/obsidian-smart-connections#578]
Hello,

First of all, thank you a lot for your effort and time in making this great product; I really love it!

I have opened this issue since every time I switch laptops (I have two) or switch Windows accounts on the same laptop (I have two on each computer), the plugin asks me to embed the notes, even though the embedding was already done and it's present in the `.smart-connections` folder.
To sync the vault across the different machines/accounts I have it on OneDrive, I tried to use the options to have the `.smart-connections` folders always downloaded with the option "Always keep on this device", but there was no way; I also tried to sync the embedding manually from the cloud before opening Obsidian, but didn't work. By the way, this issue shows up only when I first open the software on the new machine/account; when I do the embeddings then, the problem is solved until I don't switch to another machine/account, and even if on the second environment I don't re-embed the notes with the aim of keep the embedding integer where I made them when I switch back it asks me to redo them anyway.

Let me know if I can give you more information to help you with this issue.

All the best,
Dario

**Comment by brianpetro** [comment]
Hi @DarioRugg 

Thanks for letting me know about this.

1) I recommend excluding the `.smart-connections` folder from any syncing. Unfortunately, the differences between machines can trick Smart Connections into thinking files have changed when they haven't. Furthermore, the syncing processes can also prevent Smart Connections from being able to access the files, once again tricking the software into thinking that there are no embeddings since they could not be loaded.

2) Try the "Embedding file per note (EXPERIMENTAL)" setting. While this is still a work in progress, it may resolve any latent issues that may exist after following the above recommendations.

Let me know if that helps,
🌴

**Comment by DarioRugg** [comment]
Hello @brianpetro,

Thanks for your qick answare,
I have recently noticed that there was an issue with my forlder sync service for android, I wasn't filtering out affectivelly the `.smart-connection` folder from the sync srevice, maybe now that the files there are excluded from the sync with my android devices the problem will be solved, let's see.

I'll keep you updated,
Dario

**Comment by DarioRugg** [comment]
Hello,

Unfortunately, it seems that the problem originated from the OneDrive sync since fixing the exclusion of the Android sync app didn't fix the issue.
So now I tried to do as you suggested, excluding the `.smart-connections` folder from the cloud with the "Smart connections folder" option in the plugin settings. However, when I add the absolute path to the folder I have just created on my desktop, it gives me the message "No Smart Connections found." Instead, when using a relative path, I could go to a different folder (though still confined in the OneDrive space).
Now I have just updated the plugin, so let's see if with the new update things work better.

By the way I also tried to find the "Embedding file per note (EXPERIMENTAL)" setting but I couldn't find it, I don't know if it isn't in the plugin settings (since I have just updated the plugin I should have a recent version).

Best wishes.

**Comment by DarioRugg** [comment]
Hello!

With the new version all problems are solved!
The current version I have is 2.1.66.

Only think is that I need to wait the few seconds that are needed from the OneDrive application to sync everything in the background, otherwise ofcourse the latest embedding aren't present locally on disk.

So thanks a lot again for the amazing plugin @brianpetro,
All the best,
Dario
