### ISSUE TITLE
[improvement] when selecting a (part) of an  answer i cannot see what i ve highlighted...

### ISSUE THREAD

**Issue by rotello** [brianpetro/obsidian-smart-connections#58]
It s super low priority but Having a visual cue would be great to copy-paste.

**Comment by brianpetro** [comment]
Thanks for pointing this out. I haven't been able to put much time into the UI design yet. I hope to get that low-visibility highlighting solved soon.

Additionally, I think the "Click to copy" feature is very useful, and I plan to add that.

Having these feature requests is very helpful, especially so I can better prioritize my time. So thanks for making this, and please, keep them coming!

Thanks for your help
Brian🌴

**Comment by brianpetro** [comment]
This should be improved in the latest versions. Let me know if it's still an issue 🌴

**Comment by brianpetro** [comment]
Recorded response https://youtu.be/_ALiXXFn368
