### ISSUE TITLE
Support for Groq

### ISSUE THREAD

**Issue by avcode-exe** [brianpetro/obsidian-smart-connections#580]
Any plans on integrating Groq? It is very fast and can save a lot of time when comparing with other options.
Groq link: https://console.groq.com/docs/quickstart

**Comment by brianpetro** [comment]
@avcode-exe I have wanted to, it's very impressive. 

It's just a hard balance between this sort of marginal improvement and shipping new features that I think could be 10X improvements.

That's why I made contributing adapters for these additional services as easy as possible, see https://github.com/brianpetro/jsbrains/issues/1#issuecomment-2071271220 for some details.

I'd like to say I'll get to it myself eventually, but it would of course be much faster if someone could contribute the adapter. 

Thanks for participating in the Smart Connections community 
😊🌴

**Comment by seanrose** [comment]
It looks like Groq has an OpenAI endpoint: https://console.groq.com/docs/openai 

However, when I try it with the Custom API (OpenAl format) option, Smart Connections throws an invalid API key error. Am I doing something wrong, or is this expected?

![2024-05-04 at 10 50 39@2x](https://github.com/brianpetro/obsidian-smart-connections/assets/449454/6d4f3906-4d51-44c4-ba0c-fb6c821e3a36)

**Comment by brianpetro** [comment]
@seanrose it's probably that the API key is handled different, even if the rest of the API format is the same.

It might be possible to already override this via the `platforms.json` config, but I'll have to check it out.

**Comment by linmaobang** [comment]
> @seanrose I've just tested & got it to work - I believe the "path" needs to be:我刚刚测试并让它工作 - 我相信“路径”需要： /openai/v1/chat/completions
> 
> e.g. 例如： <img alt="image" width="767" src="https://private-user-images.githubusercontent.com/93633404/327983440-a5805522-a8db-4890-887a-29bb34b8ca70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NjM5OTgsIm5iZiI6MTcxNTY2MzY5OCwicGF0aCI6Ii85MzYzMzQwNC8zMjc5ODM0NDAtYTU4MDU1MjItYThkYi00ODkwLTg4N2EtMjliYjM0YjhjYTcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDA1MTQ1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3MzZjYWRmNGUyZDZlNGQ1NzdjMmMzNzgwYjA3OTE1YWRlN2VhM2IwOTI1ZTY0NDQ2ZGU0MzAwMjJkNWZlMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R2TM02-__yn4Fr_BYueA7IrVyQqSAEp3ignFnnP0QQ8">

It doesn't work either.

**Comment by linmaobang** [comment]
> Definitely working for me @linmaobang .绝对为我工作. Version: 2.1.63 版本： 2.1.63
> 
> Confirming settings: 确认设置： Model Platform = Custom API (OpenAl format)模型平台 = 自定义 API（OpenAl 格式） Model Name = llama3-70b-8192型号名称 = llama3-70b-8192 Protocol = https 协议 = https Hostname = api.groq.com 主机名 = api.groq.com Path = /openai/v1/chat/completions路径 = /openai/v1/chat/completions Streaming = OFF 流 = 关闭 Max input tokens = 8192最大输入令牌数 = 8192 API Key = [starts with gsk...]API 密钥 = [以 gsk 开头...]
> 
> Here's my console: 这是我的控制台： ![image](https://private-user-images.githubusercontent.com/93633404/330291301-fe2c945a-36d2-469b-b440-10546cec6e54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NjY0MDgsIm5iZiI6MTcxNTY2NjEwOCwicGF0aCI6Ii85MzYzMzQwNC8zMzAyOTEzMDEtZmUyYzk0NWEtMzZkMi00NjliLWI0NDAtMTA1NDZjZWM2ZTU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDA1NTUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjNjY4ZDE2NGE5MjIxOWUyNTVjNjM3NTgwZjIxOGNmNGJiZjBmNDAwNjU5MjA2OGQ2NTY3YmZmMzc3M2VkNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T58arT-l0lmIXgt8GQndPy_l_q2OvumOXTowC1CVDB4)
> 
> What does your console say?你的控制台怎么说？

This is so cool!Successful, after restarting Obsidian.thanks a lot!

**Comment by xixia123** [comment]
> @seanrose I've just tested & got it to work - I believe the "path" needs to be: /openai/v1/chat/completions
> 
> e.g. <img alt="image" width="767" src="https://private-user-images.githubusercontent.com/93633404/327983440-a5805522-a8db-4890-887a-29bb34b8ca70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMTE0OTksIm5iZiI6MTcyMTExMTE5OSwicGF0aCI6Ii85MzYzMzQwNC8zMjc5ODM0NDAtYTU4MDU1MjItYThkYi00ODkwLTg4N2EtMjliYjM0YjhjYTcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDA2MjYzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3NTMzZDI0OTZkOGQzNzhkN2M3MzNlZDNiMTdkMjMxOWQwMGM3MmE3MjQzZWZlMjc2YmQxZDAxMjk2NDgzNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9QKYEwV0VQS-y4c6oYX7hCR1qNOl1o5CaHtQ9HkJV0g">

It works for me!

**Comment by mayeenulislam** [comment]
The issue can be closed. The solution provided by [OnfrICiA](https://github.com/OnfrICiA) is working just fine.

**Comment by christianngarcia** [comment]
Thanks for following up. 😊
