### ISSUE TITLE
Errors due to rate limiting when embedding

### ISSUE THREAD

**Issue by ramarivera** [brianpetro/obsidian-smart-connections#585]
When I start Obsidian, smart connections claims there are notes to embed again, which it tries to do. But it just freezes there.

Checking the console, I can see the following errors:

![2024-05-05_11-55-32_Screenshot_Obsidian](https://github.com/brianpetro/obsidian-smart-connections/assets/7547875/7dc43949-3012-4d2c-8b91-bba54083a3d9)
![2024-05-05_11-54-50_Screenshot_Obsidian](https://github.com/brianpetro/obsidian-smart-connections/assets/7547875/8928c1c9-d8d0-47a5-8f69-71cc640210f9)

I checked my open AI api org, and it is not that one, so I am not sure where that org comes from 🤔

**Comment by ramarivera** [comment]
If I try to refresh all my notes, it also doesn't work :(

**Comment by brianpetro** [comment]
Hey @ramarivera 

Before checking anything else, we need to figure out why you don't recognize the `org-` key, since the issue likely stems from that.

The OpenAI embedding models do have a separate API key input. 

So, I recommend checking that it is using the API key you expect it to use.

Let me know if that helps
🌴

**Comment by ramarivera** [comment]
I just tried to create a new project api key for both the embeddings model and the smart chat, just to be super sure they come from my own org.
It worked fine with the smart chat, but it says it is invalid for the embeddings settings.

**Comment by ramarivera** [comment]
Console error is 
![image](https://github.com/brianpetro/obsidian-smart-connections/assets/7547875/b0a2bd40-3494-4f40-93cc-869aaa867118)

**Comment by ramarivera** [comment]
Hey @brianpetro , sorry for the late reply.

After a combination of updating and resetting the plugin plus getting new API keys, now I can embed notes again. 

Thanks for the quick updates :)
