### ISSUE TITLE
Model name changes to custom_api

### ISSUE THREAD

**Issue by amihos** [brianpetro/obsidian-smart-connections#588]
In Smart Chat settings, when attempting to use a custom API (OpenAI format), entering the model name results in it automatically changing to 'custom_api' after one or two seconds.

https://github.com/brianpetro/obsidian-smart-connections/assets/35190548/df6f3d90-0dd1-426c-af1f-e4dfd0bfff09

it happens also when i want to use local models, in this case it changes to custom_local

**Comment by WebSniper** [comment]
same problem for llama3
![image](https://github.com/brianpetro/obsidian-smart-connections/assets/105744853/270d6d92-caf9-44bd-8883-83d1ce625a1b)

**Comment by brianpetro** [comment]
Hey @amihos & @WebSniper 

Thanks for bringing this to my attention and the helpful screencast/screenshot.

This should now be fixed in `v2.1.61`.

🌴
