### ISSUE TITLE
claude API Error. See console logs for details.

### ISSUE THREAD

**Issue by JoeHo2710** [brianpetro/obsidian-smart-connections#591]
![image](https://github.com/brianpetro/obsidian-smart-connections/assets/139705200/770e001e-8bd7-42ce-b67c-3529525e298e)

**Comment by gregbarbosa** [comment]
Running into the same issue. Looks like x-api-key header is missing.

![Obsidian](https://github.com/brianpetro/obsidian-smart-connections/assets/1592502/a852c09d-8a7e-4c8f-b51e-969e057ee4ab)

**Comment by brianpetro** [comment]
Hi @gregbarbosa  & @JoeHo2710 

And thanks for the screenshots!

Do you know if the error continues after disabling and re-enabling Smart Connections?

Also, try changing models and then changing back. Does that change anything?

Thanks for your help in getting to the bottom of this issue
🌴

**Comment by brianpetro** [comment]
@gregbarbosa if you restart Obsidian or Disable then Enable smart connections the `x-api-key` error should resolve itself. 

I made a note to fix this.

**Comment by gregbarbosa** [comment]
@brianpetro That and the update solved things for me! Thank you.
