### ISSUE TITLE
Smart Connections + Kobold or TextGen

### ISSUE THREAD

**Issue by Webslug** [brianpetro/obsidian-smart-connections#598]
Hi there, I am using a program called Kobold.cpp to run a model locally.  I decided to try Smart Connections today and I tried to connect the plugin to kobold.

Model Name: Flam
Protocol: http
hostname: localhost
Path: http://127.0.0.1:5001/v1/

I have tried various Paths but not seem to work.
127.0.0.1/api/latest/generate
http://127.0.0.1:5001/v1/
/api/v1

However when ever I try to connect it says No Smart connections found.

Does Obsidian Smart Connections work with programs like Text-Gen-UI or Kobold.CPP on locally run models?

I can't seem to get it to work and I'd rather not use OpenAI or online third party services.  

![kobold](https://github.com/brianpetro/obsidian-smart-connections/assets/7551638/ec3d9982-787d-4fbf-93fd-2364041a68e5)

**Comment by christianngarcia** [comment]
Similar https://github.com/brianpetro/obsidian-smart-connections/issues/556

**Comment by brianpetro** [comment]
Closing in favor of https://github.com/brianpetro/obsidian-smart-connections/issues/556
