### ISSUE TITLE
Bug: Having trouble with embedding

### ISSUE THREAD

**Issue by arminta7** [brianpetro/obsidian-smart-connections#6]
Process keeps stalling with the below errors:

<img width="387" alt="Screenshot 2022-12-27 at 22 31 31" src="https://user-images.githubusercontent.com/7927356/209752987-ac8ef313-6219-48bd-94d0-30277460d7df.png">

**Comment by brianpetro** [comment]
Thanks! I see what's happening and am working on a patch now.

**Comment by brianpetro** [comment]
The code wasn't previously prepared to handle notes with over 8000 tokens and zero headings. The last update fixes this. Thanks for pointing this out!

**Comment by brianpetro** [comment]
The code wasn't previously prepared to handle notes with over 8000 tokens and zero headings. The last update fixes this. Thanks for pointing this out!
