### ISSUE TITLE
FR Smart View filter to exclude results that are already linked in note

### ISSUE THREAD

**Issue by cheeseonamonkey** [brianpetro/obsidian-smart-connections#614]
# Boolean user option: To exclude links that are already present on the page?

For example, these links already exist on the page; it would be useful to exclude them:
![image](https://github.com/brianpetro/obsidian-smart-connections/assets/54555500/c9511af5-3e19-4c57-bc47-183f1ce4c50a)

**Comment by christianngarcia** [comment]
Great idea. Thanks for the feature request 🌼

**Comment by AW2307** [comment]
This would be really, really useful! +1

**Comment by brianpetro** [comment]
Now available for testing in `v2.2.35`
![Screenshot 2024-07-09 at 10 51 20 AM](https://github.com/brianpetro/obsidian-smart-connections/assets/1886014/c5dce4db-9345-4f25-8bb7-ac70a8494f82)

Closing this issue in favor of https://github.com/brianpetro/obsidian-smart-connections/issues/11#issuecomment-2217938702  🌴
