### ISSUE TITLE
Can the answers be based on tags?

### ISSUE THREAD

**Issue by kkkdkk** [brianpetro/obsidian-smart-connections#625]
Many of my notes are categorized by tags rather than folders. Is it possible to provide answers based on the notes related to tags? This would be very helpful to me. Thank you very much.

**Comment by Ornicar85** [comment]
Exclusion by properties is a must have for me as well, as I categorize my files by properties rather than folders.

**Comment by brianpetro** [comment]
@kkkdkk, see:

![Screenshot 2024-06-06 at 8 17 06 AM](https://github.com/brianpetro/obsidian-smart-connections/assets/1886014/a15886c4-bc9b-42be-adfe-038a21b340bf)

@Ornicar85 it seems like you are asking something different. I am interested in better supporting your method of organization via properties (frontmatter, right?). If you don't mind, please open a new issue and let me know what might work for you. For example, would specifying certain properties to be included in all blocks, similar to how the folder structure is included in all blocks, be helpful?

Thanks to both of you for participating in the Smart Connections community 😊

🌴

**Comment by Ornicar85** [comment]
Hello Brian,

Thank you for considering my request.
I will open a new issue right away.

Kind regards,

-Jules
