### ISSUE TITLE
Doesn't Connect to Smart Connect

### ISSUE THREAD

**Issue by localjo** [brianpetro/obsidian-smart-connections#629]
I installed the Smart Connect desktop app, and the Smart Connections plugin, but I can't get the "Connect to Smart Connect" button to work. I don't see any errors either. Is there some voodoo I need to do to make it work?

https://github.com/brianpetro/obsidian-smart-connections/assets/516388/d9a4470e-a3ba-4217-81f2-3e29c4e6f49a

**Comment by brianpetro** [comment]
Hi @localjo 

No voodoo is required.

The Smart Connect app only needs to be open before connecting from the Smart Connections Obsidian plugin.

Additionally, the Smart Connect app does not need to be connected to work for the embeddings. The connect button in the Smart Connect app is specifically for connecting to the Smart Connect GPTs.

If it still isn't working, please open the developer console in Obsidian to check for errors and provide screenshots.

And thanks for your help in seeing what is going on with the screen recording.

I'm going to close this for now, but please re-open it if you continue to be unable to connect.
🌴

**Comment by localjo** [comment]
The Smart Connect app and the developer console are open in the video I shared and you can see that there are no error messages. The plugin simply fails to connect. The Smart Connect app also fails to connect for Smart Connect GPTs. I'd love to pay for that feature, but I'm not going to pay until I'm confident that the feature works.
