### ISSUE TITLE
cannot load similar blocks for text selections

### ISSUE THREAD

**Issue by winne617** [brianpetro/obsidian-smart-connections#630]
hey brian, no matter which llm i use for the embeddings, ich connot load the block embeddings for text selctions. note embeddings are fine, but the "Smart Connections: Find: Make Smart Connections"-command has no effect in version 2.1.66.
thus when i select text and run this command, smart connections does nothing, the sidebar keeps showing related blocks for the whole note.

**Comment by brianpetro** [comment]
Hey @winne617 

It sounds like you are looking to "refresh" the results. This is something that's addressed in v2.2. 

In 2.1, you can also try the "Refresh & Make Connections" command. That might achieve what you're looking to do.

🌴

**Comment by winne617** [comment]
tried it. when i run "refresh", it refreshes - but the results stay the same: they show similar notes/blocks to the whole note i am in, not to the selected text.

**Comment by brianpetro** [comment]
@winne617 I see.

So, to get connections based on the highlighted text, you need to use the "Smart Connections: Find: Make Smart Connections" command.

I just tested it and it works in `v2.1.69`.

Let me know if it works for you after updating.

If it still doesn't work as expected, there is probably some error in the developer console logs. Please screenshot this error and re-open this issue so I can review it further.

Thanks for your help😊
🌴
