### ISSUE TITLE
Slow embedding and freezing

### ISSUE THREAD

**Issue by t-if** [brianpetro/obsidian-smart-connections#633]
Ever since the update, it takes forever for me to be able to load my Vault. For some reason, the embeddings are taking a very long time, and my Obsidian freezes whenever I add or edit notes before taking its time to embed.

**Comment by brianpetro** [comment]
@t-if there were a few fixes to bugs that were introduced in `2.1.67`. The latest is now `2.1.69`.

After updating, you will need to re-embed. This should only happen once after updating.

If you continue having issues after that, let me know 🌴
