### ISSUE TITLE
Notifications popping up

### ISSUE THREAD

**Issue by jowitte** [brianpetro/obsidian-smart-connections#635]
**What is the problem:** Smart Connections Notifications keep popping up.

**What do I want to achieve:** No distractions while working. Can I somehow switch off notifications for Smart Connections?

**Comment by jowitte** [comment]
Strange, somehow oversaw that. Thanks

**Comment by luckman212** [comment]
What if the notice disappears too quickly before we can smash that bell button? Is there a list of notice IDs somewhere so we can edit the `data.json` by hand to hide them?

e.g.
```js
  "muted_notices": {
    "done initial scan": true,
    "done embedding": true
  }
```

**Comment by SpicyRicecaker** [comment]
@luckman212 Best luck I've had is grepping `.obsidian/plugins/smart-connections/main.js` for `this.notices`...

The one that shows up too fast for me is the elusive "Starting initial scan..." notification
![image](https://github.com/user-attachments/assets/ae24fd17-37d1-48ac-ab42-e0be7dcdca4b)

But found that the key for that one is `initial scan`

For future reference:
Goto `.obsidian/plugins/smart-connections/data.json` and add `"initial_scan": true` to the following hierarchy of keys:
```json
{
  "smart_notices": {
    "muted": {
      "initial_scan": true
    }
  }
}
```

**Comment by brentkearney** [comment]
Is there a parameter we can give it to mute *all* notices, all of the time?

**Comment by brianpetro** [comment]
@brentkearney 
I'm in the process of updating the notifications system, in short, all notices will be mutable easily by muting the "levels" of notifications (info, warning, error, etc.) 🌴
