### ISSUE TITLE
Embedding smart_notes with every note I open 

### ISSUE THREAD

**Issue by WillyBrem** [brianpetro/obsidian-smart-connections#636]
I've been using smart connections for a couple of months now and am really loving the plug-in. 

A couple of days ago I tried connect the openAI API and since then the behaviour of the plug-in has been very strange. 

Whenever the plug-in embeds my notes and I want to see the smart connections in the smart connections in View Smart Connections it prompts me that the note has not been embedded and restarts the process of embedding my entire vault. I also never get to see the actual smart connections. 

At first I thought it might be connected to the openAI API but the same thing happens with local models. 

I have tried opening a sandbox vault and the issue does not seem to occur there. 

Any thoughts on what might be happening? 

<img width="452" alt="Screenshot 2024-06-06 at 08 46 45" src="https://github.com/brianpetro/obsidian-smart-connections/assets/168086968/0c2d9d01-da4e-479b-9837-703e15d6146a">

SYSTEM INFO:
	Obsidian version: v1.5.12
	Installer version: v1.4.16
	Operating system: Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000 23.4.0
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Base theme: light
	Community theme: Minimal v6.0.11
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 26
	Plugins enabled: 25
		1: Minimal Theme Settings v7.5.0
		2: Fullscreen mode plugin v0.1.2
		3: Calendar v1.5.10
		4: Homepage v3.8.0
		5: Dataview v0.5.66
		6: Natural Language Dates v0.6.2
		7: Periodic Notes v0.0.17
		8: Templater v2.3.3
		9: Paste URL into selection v1.7.0
		10: Tracker v1.14.0
		11: Incremental Writing v0.4.1
		12: Kanban v2.0.51
		13: Daily Stats v1.0.4
		14: Novel word count v3.9.0
		15: Iconize v2.12.1
		16: Tag Wrangler v0.6.1
		17: Colored Tags Wrangler v0.19.3
		18: Importer v1.6.2
		19: Journal Review v2.3.2
		20: File Color v1.1.0
		21: Auto Note Mover v1.2.0
		22: Toggl Track v0.11.0
		23: Copilot v2.5.2
		24: Scrybble v2.11.0
		25: Smart Connections v2.1.67

**Comment by jack2game** [comment]
I'm experiencing the same issue after updating to the latest.

After a full embedding, closing down obsidian, opening up obsidian, the plug in will force me to do another full embedding.

Turning off this plug in for now as such behaviour is too disruptive.

**Comment by brianpetro** [comment]
@WillyBrem @jack2game, thanks for bringing this to my attention.

A bug introduced in `v2.1.67` prevented proper saving. That was fixed in `v2.1.68`.

After updating, you may still need to re-embed your notes since the latest update (which improved the file format) requires re-embedding. 

After the first re-embedding process (which will be required after you update), let me know if the seemingly erroneous re-embedding continues to happen.

Thanks for your help in making Smart Connections better by bringing issues like this to my attention 😊

🌴
