### ISSUE TITLE
smart connection files don't update

### ISSUE THREAD

**Issue by palwoo** [brianpetro/obsidian-smart-connections#638]
The version of obsidian-smart-connections I'm using is 2.1.71. When I delete a note, the smart connection files don't automatically update, it's still there, refreshing embeddings doesn't work, and restarting Obsidian doesn't work either.

![PixPin_2024-06-07_14-37-46](https://github.com/brianpetro/obsidian-smart-connections/assets/83803265/3f0579cf-df73-48c6-b3c5-e4f1800cdff2)

I deleted the file "Notice 2024-06-02-22-23-29.md" from directory "+\Readitlater", but "+_Readitlater_Notice_2024-06-02_22-23-29_md.ajson" is still in ".smart-connections\multi".

**Comment by brianpetro** [comment]
Hi @palwoo 

While I know this probably sounds ridiculous... it might require _two_ restarts until the deleted files are cleared.

You can prevent doing a full restart by simply disabling and re-enabling the plugin.

The "Making connections process" at start-up should flag any deleted files. However, the saved record may not be deleted until the subsequent restart.

It's also quite possible that you are encountering a bug. If so, errors should be in the developer console logs when you start the plugin. Screenshotting these errors and uploading them here will help me investigate the issue.

Thanks for bringing this to my attention and your help in figuring it out
🌴

**Comment by palwoo** [comment]
I deleted a file named "test for smart connections", then I disabled and re-enabled the plugin three times.  Here is the log:
[obsidian.md-1718095957335.log](https://github.com/user-attachments/files/15785371/obsidian.md-1718095957335.log)

---

Thank you for your work, it's a very useful plugin. 👍

**Comment by palwoo** [comment]
I updated the plugin to version 2.1.72 and it workes fine now.  👍

**Comment by palwoo** [comment]
Obsidian Version：1.74
Smart Connection Version：2.2.85
It happens again。

![image](https://github.com/user-attachments/assets/a1caef83-0d08-47c8-9bf6-eb203f44e08e)

**Comment by brianpetro** [comment]
Try the prune button in the settings to bulk remove old records 🌴

**Comment by palwoo** [comment]
Thanks. @brianpetro 👍 I tried the prune button before, it looked like working, but the corresponding smart connection files were still in the directory ( .smart-env\multi ).

**Comment by brianpetro** [comment]
Currently data files in the multi directory aren't deleted.

Smart Connections loads the files based on the notes available. So if a note is deleted, the corresponding data file in multi won't be loaded at the start even if it exists.

Blocks are similarly loaded based on the available notes but, since they each don't have a dedicated data file, they more frequently appear erroneously after deleting. The prune button is supposed to help with this .

🌴

**Comment by palwoo** [comment]
That's OK. 👍 Thank you  very much.
