### ISSUE TITLE
Is it feasible to use these self-referential pronouns in other languages?

### ISSUE THREAD

**Issue by wwjCMP** [brianpetro/obsidian-smart-connections#64]

**Comment by smartguy1196** [comment]
Possibly relevant: https://seo.ai/blog/how-many-languages-does-chatgpt-support @brianpetro

I think _feasible_ is a possibility, but _supportable?_ Probably not. At least not now, and probably not for a long while.

Reason being is that all of the contributors on this repo are open source developers that speak English. We may speak a handful of other languages, but this isn't a fortune 500 company with resources to support localization.

**Comment by smartguy1196** [comment]
Not saying that we _shouldn't_ support this. Just that I don't think we can, and I don't think we can for a long while

**Comment by smartguy1196** [comment]
Custom words may be a great place to start. This would move the support for multiple localizations to the community.

I recommend writing the infrastructure for custom words/localizations in a way that supports importing more than one custom word at a time (like a manifest of custom words). Perhaps writing an import function that parses a json file to load all these new words at once.

This would give the end-user community the option to write their own localization files. An end-user could even then host these localization files on GH, so that even more open-source contributors can help with supporting multiple languages/localizations.

Sample word_manifest.json for adding support for the Spanish language:
```json
[
   "yo",
   "mi",
   "mio"
]
```

**Comment by smartguy1196** [comment]
That would require a local manifest for caching all of the currently added/imported words.

**Comment by Lisandra-dev** [comment]
My idea : 
- Add a new settings "self referential pronouns" as a list of string ; 
- Edit this line https://github.com/brianpetro/obsidian-smart-connections/blob/44608222f5178361fc49a8a8401f72baf779b6e9/main.js#L2728 to add the list as a regex. 
I can try on my side if you want!

**Comment by Lisandra-dev** [comment]
![image](https://user-images.githubusercontent.com/30244939/227603900-a7b73ae0-9177-4063-becc-ca41ee4278cc.png)

The translation is not in french but it's work. I will make a PR with my adding.

**Comment by smartguy1196** [comment]
@brianpetro recommend renaming with `FR:` prefix

**Comment by brianpetro** [comment]
The following object adds support for additional languages.

https://github.com/brianpetro/obsidian-smart-connections/blob/b5155536e600ddf9f26745d58c47c32e55318e1b/main.js#L28

This should make it easy to contribute additional and improve the existing languages.

**Comment by Lisandra-dev** [comment]
Problem, in french, you forgot "m', j'" 

Also, my way to implement this allow any language...
Each time you want to add a language you need to edit the main.js, fork and wait to merge.

I recommend to use a json for the translation, if you don't want to use a text area.

**Comment by mickahouan** [comment]
Thanks for adding support for new languages in smart chat.
Could you add the pronoun "me" for the fr line?
"fr": ["mon", "ma", "mes", "moi", "nous", "notre", "nos", "notres"]

Indeed, the expression "que peux-tu me dire sur" is an element that is often used in French.
English translation of this expression : what can you tell me about

I'm also making for Elliot Meunier (a French content creator, and Obsidian expert) a whole series of teaching videos about the most interesting Obsidian plugins. The course will be released in 2 days.
Smart connections is easily in my Top 3, it changes radically the use of the Soft, many thanks for that.

Finally, for external connections, it would be great to be able to add to the embedding, Google Workspace and Microsoft 365.
or simply to be able to choose the folders that interest us the most on our computer. I wonder if Open AI's open source embedding plugin could satisfy these use cases...

I have requested access to your Beta. And I look forward to covering the developments of your work for the French speaking public.

See you soon.
Mickaël,

![image](https://user-images.githubusercontent.com/31423109/227801861-ca49f2e1-3fee-4e00-afe1-e32a2e1529e6.png)

**Comment by brianpetro** [comment]
@mickahouan added "me" to "fr" in version `1.4.9`.

I am ecstatic at getting to see Smart Connections in the upcoming videos! Thanks for that!

> Finally, for external connections, it would be great to be able to add to the embedding, Google Workspace and Microsoft 365.
or simply to be able to choose the folders that interest us the most on our computer. I wonder if Open AI's open source embedding plugin could satisfy these use cases...

I'm still reviewing [OpenAI's ChatGPT retrieval plugin](https://github.com/openai/chatgpt-retrieval-plugin). It seems like it builds the bridge from the ChatGPT plugin to vector databases. But there is still a missing link: parsing and syncing the content in your Google Workspace and Microsoft 365 with the vector database. 

However, my guess is that very soon, especially with the more popular platforms, like the two you mentioned, open-source solutions for parsing and syncing will be created. 

> I have requested access to your Beta. And I look forward to covering the developments of your work for the French speaking public.

Thanks for signing up for the beta.

And thank you for covering the plugin! I look forward to seeing how you are using it and further helping your audience make use of it themselves!

Brian🌴
