### ISSUE TITLE
Where are the embeddings/indexings/vectors stored on my local machine?

### ISSUE THREAD

**Issue by Hunter-Bobeck** [brianpetro/obsidian-smart-connections#668]
I want to make sure that my data is in safe places. And I want to exclude it from Obsidian Sync.

**Comment by brianpetro** [comment]
Hi @Hunter-Bobeck 

There is a `.smart-connections` folder in your vault that is used by default and is excluded by Obsidian Sync by default. 

This folder can be changed in the Smart Connections settings. Removing the preceding `.` will unhide the folder and make it visible to Obsidian Sync.

🌴
