### ISSUE TITLE
Pressing {Enter} to send the message to Smart Chat

### ISSUE THREAD

**Issue by Hunter-Bobeck** [brianpetro/obsidian-smart-connections#671]
This would be more convenient than having to click the send button.
I could always use {Shift}+{Enter} to newline while typing my message, so that I don't need {Enter} to do that.
Thanks for considering!

**Comment by moblangeois** [comment]
There's a workaround for now : you can press tab and it will select the send button, then enter to confirm.

**Comment by brianpetro** [comment]
Besides Tab + Enter,

`CMD+SHIFT+ENTER`(mac) or `CTRL+SHIFT+ENTER`(windows) should both work to submit the chat prompt.

I'm closing this in favor of the older https://github.com/brianpetro/obsidian-smart-connections/issues/163 , please add any additional comments to that issue 🌴
