### ISSUE TITLE
Hanging in OSX

### ISSUE THREAD

**Issue by bbecausereasonss** [brianpetro/obsidian-smart-connections#672]
Not sure why, but the plugin has started just hanging on "Loading smart connections" in OSX. No dialogue comes up with the actual embedding loading numbers like it does on my Windows machine. No code is visible in the modal dev window. I even rebuilt the embeddings today, as this caused some issues; it's just hung... 

Unfortunately, it seems it's nearly impossible to use this plugin between different machines/synched up.

<img width="664" alt="image" src="https://github.com/brianpetro/obsidian-smart-connections/assets/20264016/f67bb7f7-fea6-48eb-a0b2-e581f3083e15">

**Comment by fr3fou** [comment]
How did you fix this?
