### ISSUE TITLE
Update to latest Claude Sonnet version

### ISSUE THREAD

**Issue by seanrose** [brianpetro/obsidian-smart-connections#674]
Current version of smart connections has:
`claude-3-sonnet-20240229`

Latest is:
`claude-3-5-sonnet-20240620`

https://docs.anthropic.com/en/docs/about-claude/models

**Comment by bbecausereasonss** [comment]
Yes please

**Comment by brianpetro** [comment]
@seanrose @bbecausereasonss 

Sonnet 3.5 added in https://github.com/brianpetro/obsidian-smart-connections/releases/tag/2.1.75

🌴
