### ISSUE TITLE
Issues with retrieval in Smart Chat

### ISSUE THREAD

**Issue by bbecausereasonss** [brianpetro/obsidian-smart-connections#675]
When I press the shortcut to re-create the embedding, they kind of become corrupted. Unsure how, but the models stop being able to access them. Was not happening in the last version. Now I have to physically delete the embedding file and redo it for it to work.

**Comment by bbecausereasonss** [comment]
Another note is, it would be useful to have a shortcut to clean up rogue embeddings. Like ones where the header/name differs and are no longer pointing to a file, or what ever. So they don't confuse the system. Ideally it should do a match across file names and only keep the most recent correct embeddings.

**Comment by bbecausereasonss** [comment]
Also, getting very strange responses from Claude/Gemini in the latest version; not sure if it's SC related; but they seem to be acting far dumber, having me re-ask basic instructions. They are rarely following instructions or checking the embeddings appropriately.

**Comment by bbecausereasonss** [comment]
Just wonky behaviour lately, I tell it to look at a specific embedding it looks at a totally different one.

![image](https://github.com/brianpetro/obsidian-smart-connections/assets/20264016/12601c85-8786-42bb-b18d-e74aa6e4b0a5)

**Comment by brianpetro** [comment]
@bbecausereasonss, thanks for sharing that screenshot.

I'm aware of that bug and am working on a fix 🌴

**Comment by brianpetro** [comment]
@bbecausereasonss the issue in the screenshot should be fixed in 2.1.77/2.2.27 🌴

**Comment by bbecausereasonss** [comment]
Thanks, seems to have fixed it. Although in general I'm getting a lot of issues with Gemini models. 

"
![image](https://github.com/brianpetro/obsidian-smart-connections/assets/20264016/233acdcb-2844-40d5-a34b-f7e2891e9d62)
"

Also just in general, they seem to be having a LOT of recent trouble accurately accessing my embeddings.

**Comment by brianpetro** [comment]
This might be related https://github.com/brianpetro/obsidian-smart-connections/discussions/134#discussioncomment-9898168

I'll have to review some things, I did recently update a part of the component that initiates the embedding lookup, so might be something that needs fixing there

**Comment by brianpetro** [comment]
@bbecausereasonss 

The issue in your screenshot is fixed. The `1.0` models can't accept system prompts (though it seems like they were able to accept them previously).

I also did some further testing with gemini this morning.

I noticed that gemini does a really poor job of calling functions, which is used for embedding retrieval.

`1.5-pro` seems to call the function 80% of the time. `1.5-flash` calls the function maybe 50% of the time. 

But it's important to note that I am sending configuration to these models that should trigger the function 100% of the time. I even added additional system and user prompts to push it in the right direction.

`1.0` seems useless. [This page](https://ai.google.dev/gemini-api/docs/models/gemini#gemini-1.0-pro) says it supports function calling, but it _fails_ to call the function 100% of the time.

In my testing I was using OpenAI `gpt-3.5-turbo-16k` and it beat gemini everytime for embedding search lookup. Here's a quick comparison of the hypotheticals generated between GPT 3.5 and Gemini _1.5-pro_:

GPT 3.5:
![Screenshot 2024-06-29 at 10 17 31 AM](https://github.com/brianpetro/obsidian-smart-connections/assets/1886014/ef852d6e-e844-4379-b428-b40d3bfa4427)

Gemini 1.5-pro:
![Screenshot 2024-06-29 at 10 16 49 AM](https://github.com/brianpetro/obsidian-smart-connections/assets/1886014/6d892e41-87b7-45cd-ae63-db093e72163e)

Overall, I recommend against using Gemini at this point. This morning, I tested multiple variations for requesting useful output from the gemini models for retrieval, and my takeaway is that even their best available model is unreliable, to say the least.

🌴

**Comment by bbecausereasonss** [comment]
Thanks, that's a shame because it was working a month or two ago, not sure what they changed in their model architecture.. They just added the 2 mil context too :/

**Comment by jason-ruis** [comment]
Thanks for your work on this, Brian. Really appreciated.

**Comment by bbecausereasonss** [comment]
@brianpetro Are the Gemini models currently up to date? Because each one says up to 1 mil tokens, where as they released their 2 mil last week.

**Comment by brianpetro** [comment]
@bbecausereasonss I just checked, and both the description mentioning 1 million tokens and the limits (input and out) are retrieved via the Google models endpoint https://generativelanguage.googleapis.com/v1beta/models

So the outdated information is on Google's side 🌴
