### ISSUE TITLE
FR: OpenAI Usage Metrics

### ISSUE THREAD

**Issue by pinuke** [brianpetro/obsidian-smart-connections#68]
Can we implement a counter that tracks the amount of tokens and requests used?

This may help users analyze problems with their API keys in regards to https://github.com/brianpetro/obsidian-smart-connections/discussions/67

Originally, I was thinking of tracking it like a percent of used requests/tokens, but the problem is that the end-user can use the API key in other apps.

So I think just a simple counter of API requests used may be nice.

Perhaps use Electron/Chrome's built-in LevelDBs (Local Storage and Session Storage databases) to store the amount used in a single minute?

**Comment by brianpetro** [comment]
Yeah, this is a good idea. 

In the meantime, toggling on `log_render` in the advanced settings will show you token usage in the console.

**Comment by smartguy1196** [comment]
I forgot that Obsidian's LocalStorage LevelDB may not be the best tool to use, as Obsidian uses it for settings management, but I believe IndexedDB may be a better alternative, as you can name IndexedDBs
- sample gist for implementing IndexedDB: https://gist.github.com/JamesMessinger/a0d6389a5d0e3a24814b

### The problem with Obsidian's LevelDB:

![image](https://user-images.githubusercontent.com/12621101/226487658-778e4256-3c87-46a1-a33c-9674778c05ed.png)

As you can see, Obsidian uses LevelDB quite extensively.

**Comment by smartguy1196** [comment]
But as you can see, IndexedDB will allow you to store the metrics and data in their own database that can even have its own tables (called stores by W3C)

Here, you can see that the dataview plugin uses them
![image](https://user-images.githubusercontent.com/12621101/226487938-e1f2a730-94f5-44fd-b80b-31b90ebfc5a1.png)

**Comment by smartguy1196** [comment]
But yeah, this Gist should get you started: https://gist.github.com/JamesMessinger/a0d6389a5d0e3a24814b

**Comment by brianpetro** [comment]
Yeah, I think this is the line you're looking for https://github.com/brianpetro/obsidian-smart-connections/blob/b8e1d1acbdb43e189f3ac3e3ebf5ae7f1cb10c95/main.js#L1005

**Comment by smartguy1196** [comment]
Oh sheesh. I didn't realize the plugin was a single-file. Was there a reason that you didn't want to split main.js into multiple submodules?

**Comment by brianpetro** [comment]
@smartguy1196 I like the single file lol. 

I feel like whatever is lost with the single file is made up by the agility of a single file.

There will eventually need to be some major refactoring. But regarding the dev ops type stuff, building a test suite is top priority. Then maybe some refactoring and splitting code into other files.

**Comment by smartguy1196** [comment]
Working on a suggestion at the moment that respects your coding style as much as possible.

I may start a new issue, so that I can detail-out my changes for the PR.

**Comment by brianpetro** [comment]
Sounds good. I never imagined anyone would be considering contributing code to this, so it definitely lacks in that regards. But I solid test suite would give me the confidence to make more changes and add new features, so that's where that priority comes from.

**Comment by brianpetro** [comment]
Closing this because OpenAI has added significantly more visibility into how the API keys are used 🌴

**Comment by brianpetro** [comment]
Response recording: https://www.youtube.com/watch?v=8r1DRAfq1ec
