### ISSUE TITLE
Improved UI/UX for reviewing retrieved chat context

### ISSUE THREAD

**Issue by abdcef** [brianpetro/obsidian-smart-connections#69]
One issue with the chat window in the sidebar is that it doesn't show the source notes of its responses. For instance, if somebody asks "When did I go to the gym?" and the AI says "You went to the gym on March 19th, etc." there is no indication of where that information came from.
Providing a link to the referenced note would be very helpful. Ideally, this link could be displayed in a UI that is similar to the smart connections window that is situated below the chat window. Or, the relevant notes could be opened in workspace tabs.

**Comment by brianpetro** [comment]
@abdcef I've been thinking about this. 

Some ideas:

1. Button copy the *full context* to clipboard. Then it can be pasted for reuse in ChatGPT or review in a note. (quick and easy)
2. Button to copy the *search query* used to retrieve the content. This can be used in a dynamic code block to view the context similar to the current "Smart View" (Smart Connections pane). (quick and easy)
3. Edit button opens the full prompt for the message, including context. (less quick and easy)
4. Context referenced in the message. This may be as footnotes or linking multiple segments of text directly to the relevant. (least quick and easy)

Let me know which of those you'd like to see most.

**Comment by abdcef** [comment]
Thanks, Brian. Option 2 should get the job done. Instead of copying the query, can it create a new note with the content (lesser clicks)? Or can it display it in a vertically spit sidebar window?
Also attaching some sample UIs from other apps in case this help spark some ideas:
<img width="2164" alt="CleanShot 2023-03-21 at 10 45 50@2x" src="https://user-images.githubusercontent.com/56148250/226506862-2fdcff51-4732-49ba-918b-638c8d5f20b2.png">
<img width="1366" alt="CleanShot 2023-03-21 at 10 46 49@2x" src="https://user-images.githubusercontent.com/56148250/226506938-f6d7d99d-093a-4987-85e8-980c6f5a085e.png">

**Comment by smartguy1196** [comment]
I think 4 will be the most accurate, but most difficult to implement.

To be honest, I'm not even aware of any method to get the context used from the message created by GPT. How would you do 4 @brianpetro?

**Comment by abdcef** [comment]
To me, option 4 sounded like Bing chat of which I am not a fan

**Comment by brianpetro** [comment]
@smartguy1196 it's a prompt engineering problem. I played with the idea during the first round of implementation, but it wasn't reliable enough so I moved it to nice-to-have. Definitely possible, but it needs a bunch of time to tinker with the prompts. 

@abdcef Yes, bing chat was the UI I was imagining. And thanks for the feedback on 2.

@TimFikes welcome to the conversation! Perfect, I'm currently leaning towards implementing both 1 & 2.

Thanks everyone for the helpful feedback 😊
Brian🌴

**Comment by smartguy1196** [comment]
If you are experimenting with UIs, you could always try you.com's chat as an alt to bing chat. I believe you.com uses an entirely different pre-trained AI, but I think it's references section is pretty well done.

**Comment by brianpetro** [comment]
@smartguy1196 good to know! I'll have to check it out.

I also like Perplexity.ai for AI-assisted research since it too provides references.

**Comment by abdcef** [comment]
Another workflow, this one from Liquidtext. The note searches for citations. 
Unlike a chat, this one is be used to bring demand call for references/links to related notes in the vault for say the selected text.
https://twitter.com/liquidtextcorp/status/1638239175051714562?s=46&t=lNWO4Uk_BKxhkwri1L5dNw

**Comment by brianpetro** [comment]
@abdcef the latest update includes Options 1 & 2. Let me know what you think.

**Comment by abdcef** [comment]
You my ser are shipping faster than the speed of thought 💭 
Thank you for the heads up and will do!

**Comment by TimFikes** [comment]
Just tested, works great and gives really valuable insight into what's going on under-the-hood

**Comment by brianpetro** [comment]
@TimFikes thanks for the feedback!

Let me know what you discover. I hope to make what's under the hood more and more accessible for customizing/improving.

**Comment by brianpetro** [comment]
> The context code block is what I was looking for. The other two options are also good to have. I am so impressed with this! Simple, and it just works :)

😊

> Can the results from context code block be interchanged with smart connection files window on the sidebar?

@abdcef I'm not sure I understand what you mean by this. Do you mind clarifying?

Thanks for your help!

**Comment by abdcef** [comment]
`I'm not sure I understand what you mean by this. `

I guess I was trying to check if there was a way to see this in the right sidebar instead of the note content.

**Comment by shepner** [comment]
Much of what Im doing in Obsidian requires direct citation(s) to support a given statement.  There is a large amount of source material that is fully contained in Obsidian but there is always the possibility that some hasnt been brought in yet.  As digging through this material is fairly time consuming, Ive been playing with Smart Connections to see how it could operate as a research assistant.  It seems promising :)

This FR represents a big problem area for me.  I can obtain answers but the 'copy context' option doesnt seem to provide full text.  Rather, they seem to be cut off and the portion shown doesnt even contain the result.  The `prompt-context` is better in that it provides the sources but there is no direct connection between each document and the portion of the answer it related to.

Would it be possible to have an output which includes *everything* all together?  Lol, preferably with the citations linked in as markdown footnotes? :D

**Comment by KuecukMimarBey** [comment]
Is this only available in v2, because i cant see the buttons you mention @brianpetro

**Comment by brianpetro** [comment]
@KuecukMimarBey, the buttons should be available when notes are used as context, even in v1.

🌴

**Comment by frankcsliu** [comment]
> @smartguy1196 good to know! I'll have to check it out.
> 
> I also like Perplexity.ai for AI-assisted research since it too provides references.

I like to have Perplexity.ai support, too!

**Comment by brianpetro** [comment]
The UI/UX has been improved in the latest versions 🌴

![Screenshot 2024-06-27 105342](https://github.com/brianpetro/obsidian-smart-connections/assets/1886014/54ba0512-70f5-40e1-a7cf-1bdfc99ed836)
![Screenshot 2024-06-27 105358](https://github.com/brianpetro/obsidian-smart-connections/assets/1886014/fc091508-ce03-45a1-803a-3cbea35f5b02)

**Comment by brianpetro** [comment]
recorded response https://youtu.be/8X0lnEjr1cA
