### ISSUE TITLE
Your chats are currently using a community account..."

### ISSUE THREAD

**Issue by richardstevenhack** [brianpetro/obsidian-smart-connections#693]
OK, I got SC connected to Ollama and it is using the Qwen2 model I have installed. When I ask it explicitly what model it is, it explicitly says Qwen2.

However, whenever I send a prompt, I get a message saving that I am using a "community account with limited resources" and that I should enter an API key to get unlimited usage.

If I am strictly using Ollama and a local LLM, how can I be accessing anything external in Smart Connections?

See the screenshot:
![Community Account Message](https://github.com/brianpetro/obsidian-smart-connections/assets/44449170/c3d88f6d-2165-460f-a8ce-9722f09bf057)

**Comment by richardstevenhack** [comment]
I went back and installed SC in my original vault. This time it index most of the files at around 3500 tokens per second.

However, now it won't connect to the model at all when I send a prompt.

I just opened the Developer's Console, and I see this repeated over and over:
`Smart Connect is not running, will try to connect again later
plugin:smart-connections:1602 Attempting to reconnect in 8 seconds...
plugin:smart-connections:1560 Smart Connect is not running, will try to connect again later
plugin:smart-connections:1602 Attempting to reconnect in 16 seconds...
plugin:smart-connections:1560 Smart Connect is not running, will try to connect again later
plugin:smart-connections:1602 Attempting to reconnect in 32 seconds...
plugin:smart-connections:1560 Smart Connect is not running, will try to connect again later
plugin:smart-connections:1602 Attempting to reconnect in 60 seconds...
plugin:smart-connections:819 embedding timeout
plugin:smart-connections:1560 Smart Connect is not running, will try to connect again later
plugin:smart-connections:1602 Attempting to reconnect in 60 seconds...

Why is it trying to connect to Smart Connect? Is that by default? Could that be why it can't connect to the model - it's assuming I'm sending the prompt to Smart Connect which isn't running?

I'm a bit unclear on what "Smart Connect" actually  is. Can you explain what it does? I saw the Web page on it but I'm still not clear. Does it connect to ChatGPT or some other model?

**Comment by richardstevenhack** [comment]
Looking more closely at the Developer's Console, it also seems to have done a number of these:
`skipping large file:  Fiction/New Fiction Notes - 2013-03.md
plugin:smart-connections:1002 skipping large file:  Fiction/Mack Bolan Fiction Notes.md
plugin:smart-connections:1002 skipping large file:  Computer Security/Hacking Notes/InfoSec Career Hacking Notes.md`

I do have a number of large files. What controls whether they are skipped or not?

**Comment by richardstevenhack** [comment]
So after it stopped trying to connect to Smart-Connect, I closed the chat window, then opened it up again, and tried sending a "hi" prompt to the model. I then opened the Developer's Console to see this:
`7plugin:smart-connections:9476 View inactive, skipping render nearest
plugin:smart-connections:6591 Objectcurrent: ScChatadapter: MarkdownAdapter {smart_chat: ScChat}chats: ScChats {env: ScEnv2, folder: 'smart-chats', items: {…}, default_file_type: 'md', chat_class: ƒ, …}data: "##### user\nHi"env: ScEnv2 {plugin: SmartConnectionsPlugin, main: SmartConnectionsPlugin, config: {…}, sc_adapter_class: ƒ, ltm_adapter: ƒ, …}key: "UNTITLED CHAT 2024-07-09 12 55 02"scope: {}file_path: (...)file_type: (...)name: (...)[[Prototype]]: SmartChat[[Prototype]]: Object
plugin:smart-connections:4949 init SmartChatRenderer
plugin:smart-connections:4950 <div class=​"view-content">​…​</div>​flex
plugin:smart-connections:4952 ScChat
plugin:smart-connections:5834 chat_ml
plugin:smart-connections:5835 Object
**plugin:smart-connections:4736 No API key found for custom_local. Cannot retrieve models.**
get_models @ plugin:smart-connections:4736
plugin:smart-connections:4865 Array(1)
plugin:smart-connections:7256 Object
plugin:smart-connections:4468 Object`

Why would it be looking for an API key for the ollamd Qwen2 local model?

Note this didn't happen on my test vault.

**Comment by richardstevenhack** [comment]
Well, I solved the problem of it not finding the model! Turns out I had spelled "qwen2" with a "G" instead of a "Q"!

It's been a long night. I'm going to bed.

It is still trying repeatedly to connect to Smart Connect, though...

**Comment by brianpetro** [comment]
Hi @richardstevenhack and thanks for the detailed feedback.

The attempts to connect to Smart Connect should stop after a few minutes.

If you could share future logs using screenshots, it would be a big help, as they are a lot easier for me to read and recognize issues 🌴
