### ISSUE TITLE
In beta "/" does not bring up a modal-dialogue like it used to.

### ISSUE THREAD

**Issue by bbecausereasonss** [brianpetro/obsidian-smart-connections#695]
[[ brings up a selection model, however / no longer does. I believe this may also be happening in the full release.

**Comment by bbecausereasonss** [comment]
Never mind, seems its only if other characters such as : are present in a  line before (which is still odd?)

**Comment by brianpetro** [comment]
Should be improved in `v2.1.86`/`v2.2.40` 🌴
