### ISSUE TITLE
Bug: Update not appearing on BRAT

### ISSUE THREAD

**Issue by arminta7** [brianpetro/obsidian-smart-connections#7]
I don't think your latest plugin updates are getting picked up by BRAT for some reason. Am I doing something wrong?

**Comment by brianpetro** [comment]
I just updated the `manifest.json` version number to be consistent with the latest "release" version. 

That might fix it, but I'm not familiar with BRAT, so I can't say for sure. Let me know if that works.

**Comment by arminta7** [comment]
Yes, it updated this time!
