### ISSUE TITLE
Issues with Ollama local model output

### ISSUE THREAD

**Issue by leahstirling** [brianpetro/obsidian-smart-connections#702]
Hi there! I'm new to Smart Connections and local LLM usage in general. I'm very interested in local LLMs for my Obsidian notes because I don't want them uploaded or parsed by a server I can't control - and Smart Connections seems like a great option for sorting through my unorganised mass of notes. I'm attempting to use gemma2:9b via Ollama.

When attempting to use Smart Chat, I'm left with endless loading dots.

I believe I have it configured it correctly, at least based on [this screenshot](https://www.reddit.com/r/LocalLLaMA/comments/1cm6u9f/comment/l3l7gy3/) from /u/TheOwlHypothesis on reddit. Ollama's server output in PowerShell is showing correct POST requests when triggered by Smart Connections. Investigating Obsidian's console I can see a large number of **SyntaxError: Unexpected end of JSON input**, as well as warnings for **No API key found for custom_local. Cannot retrieve models.**

Have I configured something wrong? Any help would be greatly appreciated! 😊

Ollama console and Obsidian console:
![Screenshot (23)](https://github.com/user-attachments/assets/ace491b8-c647-4de8-a713-3a1dd9dec5ca)

Smart Chat config:
![Screenshot (25)](https://github.com/user-attachments/assets/d94afd42-0ed5-445a-8970-b8f6cb1aa11f)

**Comment by AbbasSrour** [comment]
Having this issue also

**Comment by noobmldude** [comment]
I am facing this issue too.
This happens when streaming is enabled.

**If you turn off Streaming for the Custom Local Model in the settings, it seems to work fine.**

I guess the issue is with how this plugin processes the streaming response from Ollama server

**Comment by leahstirling** [comment]
Oh, duh! I thought I tried that already! Thanks so much!
