### ISSUE TITLE
how do I know if it's working or if it's a bug?

### ISSUE THREAD

**Issue by isaac3203** [brianpetro/obsidian-smart-connections#71]
How can I be sure that embeddings.json is being generated correctly. I ask this question because I have a library of 500 notes. After I run the plugin, it keeps showing making smart connections... I try to ask it, but it doesn't seem to be able to read the content of my notes. So how do I know if it's working or if it's a bug?

**Comment by smartguy1196** [comment]
F12 > Console > Check for errors.

Specifically, check for error code 429

**Comment by smartguy1196** [comment]
I've moved this conversation to discussions https://github.com/brianpetro/obsidian-smart-connections/discussions/72
