### ISSUE TITLE
2.1.90 starts full re-embedding every time on start

### ISSUE THREAD

**Issue by alk0** [brianpetro/obsidian-smart-connections#729]
2.1.90 starts full re-embedding every time on start. Embeddings are saved to files, identical ones (as far as floating point values can be indentical) are **added** to the file over and over again, but never used. Hash values for duplicate records are the same. On the next start new embeddings for notes are computed and saved again. This leads to huge time and/or cost expenses.

Steps to reproduce:

1. Create a clean new vault (containing the default Welcome.md note)
2. Install smart-connections (with the default BGE-micro-v2 embedding model)
3. Close and open the vault a few times

Results:

- Embeddings are re-calculated on each load, AJSON files get new "SmartSource:" records added every time. No errors reported in the console.

Expected behavior:

- Embeddings for the same (content hash, model, settings) are never re-calculated

Example of such AJSON attached, zipped.
[Welcome_md.zip](https://github.com/user-attachments/files/16647702/Welcome_md.zip)

**Comment by palwoo** [comment]
Me too.

**Comment by brianpetro** [comment]
Looking into it 👀🌴

**Comment by brianpetro** [comment]
I narrowed down the issue, working on a fix.

Removing the preceding `.` in the `Smart Connection Folder` setting should prevent subsequent re-embeddings, as the issue only affects hidden folders. (Note: this will likely make the embeddings sync via Obsidian Sync and will also show the folder in your vault file explorer).

🌴

**Comment by brianpetro** [comment]
I implemented and shipped a fix in `v2.1.92`. Thanks @alk0 @palwoo & @3-ark for bringing this to my attention 😊🌴

**Comment by alk0** [comment]
(After some testing) 2.1.92 seems to work for me. @brianpetro I don't mind if you close the issue, if there are no other objections.
