### ISSUE TITLE
[draft] refactor: Split main.js into subfiles

### ISSUE THREAD

**Issue by smartguy1196** [brianpetro/obsidian-smart-connections#73]
_This issue is in a draft status, so it may not get implemented_

**Comment by smartguy1196** [comment]
Potential method for splitting the class into subfiles: https://stackoverflow.com/questions/40104004/split-a-javascript-class-es6-over-multiple-files

**Comment by smartguy1196** [comment]
Method for splitting JSON-ifyable objects like DEFAULT_SETTINGS into their own files:

node.js has support for importing JSON files as Object Literals using the `require( "path/to/file.json" )` method

**Comment by brianpetro** [comment]
There are already a few classes to help keep things organized. I don't see the need to split files though because it's easier to just "fold" the classes/functions into a single line.

**Comment by smartguy1196** [comment]
Still going to work on it, so that you could see what it would look like if it was split into subfiles.

The main issue with single-file programs is that they have poor inversion-of-control (IoC). You'll be missing out on features that come with good IoC like dependency injection (DI) or feature isolation.

For unit-testing, DI is definitely something you'll want to have.

I'll show you in the PR once I get it finished up today.

**Comment by brianpetro** [comment]
Sounds good, thanks for the help.

**Comment by brianpetro** [comment]
@smartguy1196 just fyi, I'm still preferential to keeping it single file. This allows super tight feedback loop so I can edit the code and see changes almost immediately in my obsidian, without any build process. And that's important for shipping fast!

**Comment by brianpetro** [comment]
I know it's atypical, but my ideal test suite would be just another class in the same file, and it would be able to be run from within the settings. 

This would give anyone the ability to tinker with the code directly within their vault, no dev ops or anything else would be required at all.

**Comment by smartguy1196** [comment]
> @smartguy1196 just fyi, I'm still preferential to keeping it single file. This allows super tight feedback loop so I can edit the code and see changes almost immediately in my obsidian, without any build process. And that's important for shipping fast!

Assuming that you just copy and paste the code back into developer console, the methods that I'm using to split the file can also be reused the same way, because they use DI.

here's an example submodule:

```js
function injectSomeMethod( someDependentClassToModify ) { // achieves dependency injection
   someDependentClassToModify.prototype.SomeMethod = async function( param ){
     this.someProperty = param
   }
}

module.exports = injectSomeMethod
```

then just copy and paste the injectSomeMethod into dev console to modify the class:

```js
// copy and paste the method injector into dev console
function injectSomeMethod( someDependentClassToModify ) { ... }

// call the method injector to update the class
injectSomeMethod( SmartConnectionsPlugin )
```

**Comment by brianpetro** [comment]
It seems relatively straightforward.

But it's still an extra step. And I'm the kind of person that buys 20 of the same shirts to wear when I work, so it's one less decision I have to make each day.

That said, there will be a time when this type of dev ops makes sense. Preferably when it enables others to make significant contributions. But for now, as long as I'm going full force into feature additions and improvements on my own, anything that slows me down will have to be a pass.

**Comment by brianpetro** [comment]
#blueshirtguy

**Comment by smartguy1196** [comment]
> That said, there will be a time when this type of dev ops makes sense. Preferably when it enables others to make significant contributions. But for now, as long as I'm going full force into feature additions and improvements on my own, anything that slows me down will have to be a pass.

Gotha, still going to submit the PR, so that you have something to reference down the road. We can always deny the PR.

**Comment by smartguy1196** [comment]
From the PR:

> I appreciate the effort @smartguy1196 .
> 
> I understand the tradeoffs and I don't think this is the right time for this project. As the sole developer, the single file fits my style and allows me to maximize productivity.
> 
> However, whenever I start stepping back from this project, I think it will make a lot more sense to consider a change like this to encourage contributions.
- Brian Petro

Closing!
