### ISSUE TITLE
Ctrl + Enter should send a message in Chat

### ISSUE THREAD

**Issue by thesilence123** [brianpetro/obsidian-smart-connections#730]
![image](https://github.com/user-attachments/assets/0f9ae0f7-3ec5-475b-93fb-8459f14662aa)

Can I prepare a pull request that adds this?

**Comment by mkasajim** [comment]
I have installed this plugin today and was surprised to find that neither Ctrl+Enter nor just Enter sends the message! This is a bit frustrating, as I am used to sending messages using the Enter key and making a new line with Shift+Enter in AI chats. I hope this feature gets added soon.

**Comment by christianngarcia** [comment]
Thanks for participating in the Smart Connections community. This issue is brought up frequently. You can find more information about it and add any additional comments you may have here https://github.com/brianpetro/obsidian-smart-connections/issues/163
