### ISSUE TITLE
Error: This model's maximum context length is 8191 tokens, however you requested 10482 tokens

### ISSUE THREAD

**Issue by SkyJinXX** [brianpetro/obsidian-smart-connections#74]
![image](https://user-images.githubusercontent.com/29913127/226683551-bb371785-0001-436b-a051-d91cd2846271.png)
![image](https://user-images.githubusercontent.com/29913127/226683698-cc122a7e-7a96-4dc8-857c-817b40331e77.png)
![image](https://user-images.githubusercontent.com/29913127/226683934-762455ef-5073-4b19-a86e-f8d1f90bd540.png)
version: 1.3.16
Could you help me? Thank you.

**Comment by brianpetro** [comment]
@SkyJinXX thanks for sharing the errors in the log, very helpful!

Somehow a file is getting around the limits put in place for embedding size.

Do you see a list of failed files in the settings? Is there anything about those failed files that might give me a clue to why they're failing?

Thanks for your help solving this!
Brian 🌴

**Comment by brianpetro** [comment]
> Thank you for your prompt reply.
> 
> I have copied the content of the article below to Obsidian, which includes both Chinese characters and some images. I suspect that the reason for exceeding the limit may be due to the difference in token calculation for Chinese characters compared to English by OpenAI since I have heard that a single Chinese character is counted as two tokens. https://zhuanlan.zhihu.com/p/613112156

@SkyJinXX it seems like you figured it out.

I don't think there's an easy fix without including an outside library and rewriting a bunch. The current token calculation used by the plugin is very rudimentary (character count divided by 4).

It might just be best to use the exclusion settings to exclude files like this if you want to keep your logs clean of errors.

But I'm also open to suggestions if you have any.

Thanks for figuring this out!

**Comment by brianpetro** [comment]
Closing in favor of this FR #126
