### ISSUE TITLE
API Error. See console logs for details.

### ISSUE THREAD

**Issue by hans123m12m1** [brianpetro/obsidian-smart-connections#743]
Hi, i need some help right now. i was using the smart connection a day ago, and when i updated it to the latest verison. it seems to be in an error thingy. when i use the word like "my" or "mine" the pronounce of the words of the trigger, it gave me an error. is there a way to fix this?
![image_2024-08-28_140821701](https://github.com/user-attachments/assets/f2cbe6ab-6c27-4080-a7b0-dcbc6b089b57)

and uhh sorry if this is the wrong place to put it.

**Comment by HyperSigilMedia** [comment]
I'm having this same problem!

**Comment by brianpetro** [comment]
Hi @hans123m12m1 

Which chat model are you using? There should also be an associated error in the developer console logs. If you can screenshot that, then I should be able to better help you out 🌴

**Comment by hans123m12m1** [comment]
> Hi @hans123m12m1
> 
> Which chat model are you using? There should also be an associated error in the developer console logs. If you can screenshot that, then I should be able to better help you out 🌴

hi, thank you for responding. i am using the Gemini model. and well i dont actually know what's cause the error. but i do notice this.

![image_2024-08-30_132601619](https://github.com/user-attachments/assets/4a6a88b4-537c-43f8-b587-6bbeb890d543)

though, when i updated to the latest verison of the rep. it gave me an error when i mention the world "My, mine" and any pronoun to trigger it.

**Comment by brianpetro** [comment]
@hans123m12m1 I see, that's an issue specific to the flash model. If you use the pro model it should work 🌴

**Comment by hans123m12m1** [comment]
> @hans123m12m1 I see, that's an issue specific to the flash model. If you use the pro model it should work 🌴

Dear Brian

IT works, thank you for helping me. i hope you had a great day and a great life. 🙏

**Comment by christianngarcia** [comment]
Thanks for following up. 😊
