### ISSUE TITLE
Jina v2 embedding error.

### ISSUE THREAD

**Issue by bbecausereasonss** [brianpetro/obsidian-smart-connections#753]
Since last update, I cannot seem to make embeddings in either any OpenAI model (freezes/errors) or Jina. Also freezes/errors. I've got a 4090 with 64GB of Ram.

![image](https://github.com/user-attachments/assets/41aa42a2-b7b0-4503-bbf4-4d6a2fe20ba6)

**Comment by bbecausereasonss** [comment]
I have tried using Smart Connect. 

Smart Connections is now constantly freezing Obsidian. Taking for ever to load and basically has made it impossible for me to use it. Sad because it was by far my favorite workflow and app :/

**Comment by brianpetro** [comment]
If it was working before `v2.1.96` then see https://github.com/brianpetro/obsidian-smart-connections/issues/749#issuecomment-2324472086 🌴
