### ISSUE TITLE
The plugin is not working correctly

### ISSUE THREAD

**Issue by Froggerr10** [brianpetro/obsidian-smart-connections#758]
Hi guys, 

Hello everyone, I installed the plugin but it is not loading, the Smart chat field for the platform model is not enabled in the settings.
Could someone help me?  thanks..

![image](https://github.com/user-attachments/assets/74020af7-d8b6-4c16-89e2-27c2d254f674)
![image](https://github.com/user-attachments/assets/90bfa58c-5424-4e3a-80d8-f6ab43a75d28)
![image](https://github.com/user-attachments/assets/0015ebae-6036-4022-820d-35de5ee74e22)

**Comment by brianpetro** [comment]
Hi @Froggerr10 and thanks for the screenshot.

Try this https://github.com/brianpetro/obsidian-smart-connections/issues/749#issuecomment-2324472086

And try clicking the Smart Connections settings tab again after a few moments to see if the chat model settings appear, see https://github.com/brianpetro/obsidian-smart-connections/issues/750#issuecomment-2324466546 for more

🌴

**Comment by Froggerr10** [comment]
Perfect @brianpetro working perfectly right now... thanks man... 💯
