### ISSUE TITLE
Issues after updates local API/Ollama/llama 3.1 Mac M2. 

### ISSUE THREAD

**Issue by CznCrk** [brianpetro/obsidian-smart-connections#761]
Hi, 

Thanks for Smart Connections/Chat! Both amazing add ons to the obsidian experience. 

I'm experiencing a local API issue claiming that it can't find notes that do exist and that the Smart Connections chat even hyperlinks to. 

This wasn't happening a few days ago before the update but unsure if they're related. 
I've attached console log during the search as well as the local API Smart Chat settings. 

![Screenshot 2024-09-04 at 15 27 19](https://github.com/user-attachments/assets/031376d4-511e-4f0d-ad89-631e6547a3f9)

![Screenshot 2024-09-04 at 15 34 22](https://github.com/user-attachments/assets/74f6007a-b5b1-412f-946c-c4e3ce5b5d9e)

**Comment by CznCrk** [comment]
As an update, smart connections will parse the data of the notes within YT transcript and provide similar notes, but chat won't register it as existing. 
![Screenshot 2024-09-04 at 16 08 17](https://github.com/user-attachments/assets/b78a49f8-3117-4758-9076-ed7704a0d167)

![Screenshot 2024-09-04 at 16 08 28](https://github.com/user-attachments/assets/23d14190-5bbe-4fb9-b093-360e719b6000)

**Comment by CznCrk** [comment]
Latest update to Smart Connections causes chat to endlessly search. Doesn't reply.
![Screenshot 2024-09-05 at 07 33 47](https://github.com/user-attachments/assets/259898ef-db0e-4841-bf9f-f6130a3ecba4)
Could this be to do with a change in the huggingface transformers?

**Comment by christianngarcia** [comment]
> Latest update to Smart Connections causes chat to endlessly search. Doesn't reply. ![Screenshot 2024-09-05 at 07 33 47](https://private-user-images.githubusercontent.com/180430963/364652720-259898ef-db0e-4841-bf9f-f6130a3ecba4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1NTI3ODMsIm5iZiI6MTcyNTU1MjQ4MywicGF0aCI6Ii8xODA0MzA5NjMvMzY0NjUyNzIwLTI1OTg5OGVmLWRiMGUtNDg0MS1iZjlmLWY2MTMwYTNlY2JhNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNVQxNjA4MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYTc0ODZmOTZhM2FlMzBkZGNmZTU3NjkzZTE2YzY5NmNhZGY3OGNmMzYxYTFjNzYzY2ZiMjExMjdkMDkzOGVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Y5UGRB4YnhvOVCqaGlByETPTh3cEXFHfUDz4SwcSv-0) Could this be to do with a change in the huggingface transformers?

There is a toggle in the settings to use the old version of huggingface transformers.

**Comment by CznCrk** [comment]
Neither setting works.

**Comment by CznCrk** [comment]
As an update, I downloaded Bark (https://huggingface.co/docs/transformers/en/model_doc/bark), and had tried implementing the optimisation techniques. It was only after reverting these changes that Smart Connections could connect back with llama3.1. Smart Chat works as an interface for llama3.1 but now is producing the same error message found in  issue [#767](https://github.com/brianpetro/obsidian-smart-connections/issues/767). Smart connections is working so has access to my notes but Smart Chat is only finding 1 file to embed, even after reinstallation of Smart Connections and a forced refresh. 

![Screenshot 2024-09-06 at 18 04 50](https://github.com/user-attachments/assets/65848212-63f3-43a9-8cd0-3457c9716f5d)
