### ISSUE TITLE
Problems using Smart Connect as backend to Smart Connections Extension

### ISSUE THREAD

**Issue by 3e9b** [brianpetro/obsidian-smart-connections#769]
It seems the process for connecting Smart Connect app (v. 1.3.2) to Smart Connections (2.1.100) to use as a local-only backend for embedding has changed somewhat? The button "Connect to Smart Connect" is gone now. I'm noticing more hangups while "Making Smart Connections" than it used to.

What should my settings in Smart Connect be now? Should I "turn off security features" and then setup an environment connected to an obsidian folder? Just seems like this isn't as clear as it used to be.

**Comment by brianpetro** [comment]
You can turn-off the Smart Connect app for now as it is not currently being used for embedding by the plugin. This will be reintroduced at a later date 🌴
