### ISSUE TITLE
Smart connections disappeared a few days ago

### ISSUE THREAD

**Issue by Txindoki666** [brianpetro/obsidian-smart-connections#771]
For the last 4 days Smart Connections does not appear in the registration panel, nor does the chat. A warning appears stating “The pluging that created this panel is not active”. I don't know what it refers to, since the plug-in is obviously active and updated. 
The only solution I have found is to take the files from an installation a few months ago and replace them in the smart connetions folder. The files are these:
data.json
ma In.js
manifest.json
styles.css

I leave the debugging information:
SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.6.5
	Operating system: Windows 10 Pro 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: dark
	Community theme: Minimal v7.7.18
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 40
	Plugins enabled: 40
		1: Annotator v0.2.11
		2: Auto Link Title v1.5.4
		3: Calibre v1.0.8
		4: Highlightr v1.2.2
		5: Kobo Highlights Importer v2.0.0
		6: LanguageTool Integration v0.3.7
		7: Omnisearch v1.24.1
		8: Recent Files v1.5.0
		9: Simple Embeds v1.15.0
		10: Templater v2.7.1
		11: Text Extractor v0.5.2
		12: Timelines v0.3.2
		13: Zotero Integration v3.2.1
		14: Book Search v0.7.4
		15: File Tree Alternative v2.6.0
		16: Copilot v2.6.4
		17: Editing Toolbar v2.4.16
		18: Tag Wrangler v0.6.1
		19: Note Linker v1.2.4
		20: Extract Highlights v0.0.18
		21: Settings Search v1.3.10
		22: Kanban v2.0.51
		23: Hover Editor v0.11.20
		24: Media DB v0.7.2
		25: YTranscript v0.9.2
		26: Enhancing Export v1.10.7
		27: Advanced Canvas v3.1.0
		28: Markmind v3.0.2
		29: Importer v1.6.4
		30: Footnote Shortcut v0.1.3
		31: Remember cursor position v1.0.9
		32: Style Settings v1.0.9
		33: PDF++ v0.40.9
		34: Link Exploder v0.3.0
		35: Copy Block Link v1.0.4
		36: Translate v1.4.9
		37: Smart Connections Visualizer v1.0.17
		38: Reference Map v1.8.1
		39: Minimal Theme Settings v8.1.1
		40: Smart Connections v2.1.71

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

So it works normally again, but smart connections visualizer does not work.
Please help.

**Comment by brianpetro** [comment]
See https://github.com/Mossy1022/Smart-Connections-Visualizer/issues 🌴

**Comment by Txindoki666** [comment]
Thank you for your reply. I don't think what your link indicates is my problem. I uninstalled Visualizer when the problem started.
On another pc Visualizer was never installed.
After what I indicated in my 1st post other things have happened. 
On my main pc I reinstalled Obsidian from 0. I deleted the registry residues that Obsidian left behind. I just installed smart connections and the problem appeared again. As you can see in the screenshot the models do not appear in the Smart Chat.
However, for no apparent reason, after two days the blocks started to appear and it seemed that everything was fine. But today I tried to update the add-on without success. And again the failure reappeared.
I attach the Obsidian log. I don't know if smart connections has a log I can provide you with. 
Thank you.

SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.6.7
	Operating system: Windows 10 Pro 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: dark
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 25
	Plugins enabled: 25
		1: Kobo Highlights Importer v2.0.0
		2: Omnisearch v1.24.1
		3: Recent Files v1.5.0
		4: File Tree Alternative v2.6.0
		5: Editing Toolbar v2.4.16
		6: Tag Wrangler v0.6.1
		7: Kanban v2.0.51
		8: Advanced Canvas v3.1.0
		9: LanguageTool Integration v0.3.7
		10: Text Extractor v0.5.2
		11: Markmind v3.0.3
		12: Auto Link Title v1.5.4
		13: Calibre v1.0.8
		14: Copilot v2.6.6
		15: Copy Block Link v1.0.4
		16: Extract Highlights v0.0.18
		17: Hover Editor v0.11.20
		18: Link Exploder v0.3.0
		19: PDF++ v0.40.9
		20: Reference Map v1.8.1
		21: Settings Search v1.3.10
		22: Style Settings v1.0.9
		23: AI image analyzer v0.1.10
		24: Translate v1.4.9
		25: Smart Connections v2.1.101

![Captura de pantalla 2024-09-17 141825](https://github.com/user-attachments/assets/563e59e5-58d6-494d-a678-cd4bda114d82)
