### ISSUE TITLE
How can other formats, such as txt, css, html, .py, and other types of file, be read and used for word embedding?

### ISSUE THREAD

**Issue by Edwener** [brianpetro/obsidian-smart-connections#779]
Which part of the code should I modify to support more formats?

**Comment by brianpetro** [comment]
You would want to create adapters in this module https://github.com/brianpetro/jsbrains/tree/main/smart-chunks#readme

The readme is a bit outdated, but smart_chunks.js is the main entry point and adapters do the heavy lifting.

🌴

**Comment by Edwener** [comment]
Thanks for telling me the direction 👍 

With the help of gpt ,I insert both below: 
![image](https://github.com/user-attachments/assets/79d98421-d05d-4f3f-986c-96e7ad233366)
![image](https://github.com/user-attachments/assets/f9d14187-7213-4620-9c92-c8b4d1771a0b)

However
![image](https://github.com/user-attachments/assets/0acff24e-819c-4ab9-9b6e-6c16204b534a)
