### ISSUE TITLE
Why there are 'Not found:undefined' in my smart-chat response's sc-context 

### ISSUE THREAD

**Issue by Ocean-Tang** [brianpetro/obsidian-smart-connections#783]
Look this screenshot：
![image](https://github.com/user-attachments/assets/c79ca9af-7b07-4bc0-8dc4-74f97dfcffbe)

and this is the codeblock:
##### system
```sc-context
undefined
undefined
undefined
undefined
undefined
undefined
undefined
undefined
undefined
undefined
```

**Comment by EVasiloudes** [comment]
This also has started occurring to me since the last update

**Comment by brianpetro** [comment]
Thanks for bringing this to my attention.

I'm closing this in favor of the existing https://github.com/brianpetro/obsidian-smart-connections/issues/776 🌴
