### ISSUE TITLE
Smart connections crashes even on a clean install of Obsidian.  #Bug 

### ISSUE THREAD

**Issue by Txindoki666** [brianpetro/obsidian-smart-connections#790]
Greetings, since three weeks smart connections fails on my 3 computers. It gets stuck with a message “Loading Smart Connections...”. Sometimes it makes like it is indexing the notes, which is noticeable in the pc resource usage. 
_This is not a problem with smart connections visualizer, as it is not installed on two of the computers._ 
I reinstalled smart connections many times, deleted the installation folder, deactivated the rest of the plugins without solving the problem.
As the failure continued on my main pc, I reinstalled Obsidian from 0. I deleted the registry residues that Obsidian left. I just installed smart connections and the problem appeared again. As you can see in the screenshot, the models do not appear in Smart Chat.
However, for no apparent reason, after two days the blocks started to appear and it seemed that everything was fine, although a bit slow. But today I tried to update the plug-in without success. And again the failure reappeared.
I attach the Obsidian log. I don't know if smart connections has a log I can provide you with. 
Thanks in advance for your reply.
SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.6.7
	Operating system: Windows 10 Pro 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: dark
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 25
	Plugins enabled: 25
		1: Kobo Highlights Importer v2.0.0
		2: Omnisearch v1.24.1
		3: Recent Files v1.5.0
		4: File Tree Alternative v2.6.0
		5: Editing Toolbar v2.4.16
		6: Tag Wrangler v0.6.1
		7: Kanban v2.0.51
		8: Advanced Canvas v3.1.0
		9: LanguageTool Integration v0.3.7
		10: Text Extractor v0.5.2
		11: Markmind v3.0.3
		12: Auto Link Title v1.5.4
		13: Calibre v1.0.8
		14: Copilot v2.6.6
		15: Copy Block Link v1.0.4
		16: Extract Highlights v0.0.18
		17: Hover Editor v0.11.20
		18: Link Exploder v0.3.0
		19: PDF++ v0.40.9
		20: Reference Map v1.8.1
		21: Settings Search v1.3.10
		22: Style Settings v1.0.9
		23: AI image analyzer v0.1.10
		24: Translate v1.4.9
		25: Smart Connections v2.1.101

![Captura de pantalla 2024-09-17 141825](https://github.com/user-attachments/assets/60dee9a6-7f1e-422e-85a1-f3ea38ac6530)

I show you the rest of the configuration:

![Captura de pantalla 2024-09-17 211727](https://github.com/user-attachments/assets/dad226f5-4a48-445e-a9e1-0a3a6ee4a691)
![Captura de pantalla 2024-09-17 212110](https://github.com/user-attachments/assets/3dacdcf3-6f28-45f1-8b53-3b0f2019a5f1)
![Captura de pantalla 2024-09-17 212148](https://github.com/user-attachments/assets/360d7012-e5e5-4275-b5d1-e9725659167a)

**Comment by Txindoki666** [comment]
Greetings, I paste screenshots of the console in case they are useful. I do not know how to use this tool, so I apologize if I do not know how to deliver better information:
![Captura de pantalla 2024-09-18 160539](https://github.com/user-attachments/assets/28c960ed-9753-42ba-96c7-ee7a4438d136)
![Captura de pantalla 2024-09-18 160610](https://github.com/user-attachments/assets/b20d152e-2c0f-475d-9028-2c2ed4aac3bd)
![3](https://github.com/user-attachments/assets/453559b5-6ae7-4118-b721-72841b9fcf98)
![4](https://github.com/user-attachments/assets/f01de89c-30b9-4856-bea4-db83c47498c9)
![5](https://github.com/user-attachments/assets/6df3174a-26b5-4b20-b814-b45836c18655)
![6](https://github.com/user-attachments/assets/d29460c1-de19-45c7-bbbf-a35e104eb489)
![7](https://github.com/user-attachments/assets/60b39e7c-eff1-40ae-acad-e60dbd84ff9f)
![8](https://github.com/user-attachments/assets/1b8471ee-c2d8-4fa8-9d7e-5588e72d79bd)
![9](https://github.com/user-attachments/assets/15153e92-2a7f-4fae-a4b2-74acf4655db9)
![10](https://github.com/user-attachments/assets/ecfe97fc-c1ca-43b5-ad36-68f35cc2589c)
![11](https://github.com/user-attachments/assets/d3f13f89-c4d0-454f-a520-15bf0b45959c)
![12](https://github.com/user-attachments/assets/6f57d298-3f2d-40d1-8c62-c8e59cd8ccd4)
![13](https://github.com/user-attachments/assets/f0d5bb69-b49c-4d32-a90f-8fb9a677ae12)

**Comment by brianpetro** [comment]
@Txindoki666 try setting the GPU batch size to `0` 🌴

**Comment by Txindoki666** [comment]
Thank you for your quick response. I upgraded to v2.2.7.6 and set the GPU to 0, but the problem persists. 
![14](https://github.com/user-attachments/assets/d2f4745e-f959-4e71-8fa6-7b23799beeb2)

**Comment by brianpetro** [comment]
There are two GPU batch sizes in the screenshot 🌴

**Comment by Txindoki666** [comment]
Sorry, I set both to 0 but it doesn't work.
![15](https://github.com/user-attachments/assets/54f8d19d-19ee-4570-a896-373eea190815)

**Comment by brianpetro** [comment]
Also turn on the legacy transformers toggle

**Comment by Txindoki666** [comment]
Now the blocks have appeared. I will export this configuration to my other computers. 
Thanks a lot.

![17](https://github.com/user-attachments/assets/c05ea8b0-cfec-494f-afcc-d914802f4928)
![16](https://github.com/user-attachments/assets/671066a2-69b3-4466-9147-5de3ce610286)
