### ISSUE TITLE
2.2.72 Cannot Find System Prompts

### ISSUE THREAD

**Issue by EasternPA** [brianpetro/obsidian-smart-connections#792]
Rehash of #568 for me. I type @ or '[space]@' to select a system prompt in the Smart Chat pane, and the list of available system prompts is always empty.

![image](https://github.com/user-attachments/assets/46f64460-a86c-4aff-a437-10954eb54852)
![image](https://github.com/user-attachments/assets/d8fa1db6-d3ba-47fb-897b-4fb411b584c7)
![image](https://github.com/user-attachments/assets/9c925e1b-4fa7-47fb-8c61-b852c3cc7f20)

The 'smart prompts' folder is in the root of my vault. I have tried renaming the folder (and kept the rename in sync in the settings), but that didn't help.

**Comment by brianpetro** [comment]
Thanks for bringing this to my attention. Working on a fix 🌴

**Comment by brianpetro** [comment]
@EasternPA should be fixed in `2.2.73`

**Comment by EasternPA** [comment]
> @EasternPA should be fixed in `2.2.73`

Works! Thanks!

**Comment by Mithadon** [comment]
I have the same problem, but in my case I believe it's because I'm not formatting a prompt file properly in the prompts folder. Could someone please share what a file is supposed to look like?
Thank you

**Comment by EasternPA** [comment]
I wanted an expert writing coach, so I asked it to write a system prompt that I could use to configure an LLM as precisely that: a successful novelist who is now mentoring others looking to try their hand at writing. I specified what features and capabilities are central to its skillset. The resulting system prompt is what I then loaded into a file called 'writing-coach.md' stored in the 'system-prompts' folder. So in the sidebar, I'll write:

Using @"writing-coach" please give me a character profile based on [[ (and then choose a file from the file list)

And it spits out a character profile based on the character's behavior in the file I asked it to use as a reference. It's like having the perfect writing coach 24x7 right in the side bar standing ready to take your questions and give you feedback.

[writing-coach.md](https://github.com/user-attachments/files/17970147/writing-coach.md)

**Comment by Mithadon** [comment]
Thanks @EasternPA . It seems the problem was that I had the full path to my prompts folder (in the root of vault), instead of just the name of the folder itself. 
That being said, the prompt (in this case writing-coach.md) only actually gets sent maybe 20% of the time, and I have no clue why.
