### ISSUE TITLE
BR: Unexpected Token "d" errors while parsing JSON

### ISSUE THREAD

**Issue by pinuke** [brianpetro/obsidian-smart-connections#80]
![image](https://user-images.githubusercontent.com/12621101/227333400-cad45a7d-a0d8-4970-b555-5253780d91e9.png)

**Comment by smartguy1196** [comment]
Possibly related to stopping the chat. Going to try to reload the Obsidian to rule that out.

**Comment by smartguy1196** [comment]
This looks like this small code block is the problematic bit:

![image](https://user-images.githubusercontent.com/12621101/227334488-2d52f2a7-65c3-49d1-ac55-65dccfb8a5ef.png)

What it looks like is that JSON.parse call is failing which is potentially causing the render_message function call to fail

**Comment by smartguy1196** [comment]
I also found these errors in console:

![image](https://user-images.githubusercontent.com/12621101/227335837-c483478b-8171-40ec-9ab8-0f213ca878bd.png)

**Comment by smartguy1196** [comment]
From the looks of it, I've hit ChatGPT while it's too busy (based off of the 503 error)

**Comment by brianpetro** [comment]
I was looking into this earlier. The "d" error doesn't seem to stop the plugin from working, so I decided to move on from it after being unable to reproduce it.

The 503 indicates a server-side failure. The logging could be cleaned up a bit, though.

**Comment by brianpetro** [comment]
Overall, we will have to keep an eye on this to see if it continues to happen.

**Comment by smartguy1196** [comment]
> I was looking into this earlier. The "d" error doesn't seem to stop the plugin from working, so I decided to move on from it after being unable to reproduce it.

If I had to guess, I think it has to do with how that ScStreamer class manages the response. I think it may be trying to parse the entire response message instead of just the response body.

**Comment by smartguy1196** [comment]
> I was looking into this earlier. The "d" error doesn't seem to stop the plugin from working, so I decided to move on from it after being unable to reproduce it.

## I have 3 theories

If I had to guess, I think it has to do with how that ScStreamer class manages the response. I think it may be trying to parse the entire response message instead of just the response body.

My second guess is that 503 errors and the like aren't returning a JSON response, but that doesn't make sense, because the info for that 503 response in Devtools > Network has as an empty response...

...So my third guess is that ScStreamer is not properly handling responses that have an empty response body.

**Comment by brianpetro** [comment]
Yeah, I'd bet on either 1 or 3. 

The good thing is it doesn't seem to cause any major issues other than polluting the console log.

Thanks for looking into it!

**Comment by brianpetro** [comment]
Recorded response https://youtu.be/qHTZ4Ph1kI8
