### ISSUE TITLE
Unable to select OpenAI models in Smart Chat (v2.2.76)

### ISSUE THREAD

**Issue by MPA10** [brianpetro/obsidian-smart-connections#802]
Smart Chat stopped working since last update (v2.2.76) 
OS = Windows 11

OpenAI key = valid
Submenu for selecting OpenAI models not opening correctly.

Screenshot UI:
![Screenshot 2024-09-25 203223](https://github.com/user-attachments/assets/e16d580c-5ae0-4f75-a16e-0bad9867d49b)

Console error = Failed to fetch model data: 
![Screenshot 2024-09-25 203150](https://github.com/user-attachments/assets/3d319d10-3ce5-4b55-a3fd-68a7080ce2f8)

**Comment by brianpetro** [comment]
401 error means authentication error. API key is required to retrieve the available models. Scroll down and add an API key 🌴

**Comment by MPA10** [comment]
Re-entered the API key and seems to be working again.
Thanks for the fast response!
