### ISSUE TITLE
Erroneously including same note in Smart Connections results

### ISSUE THREAD

**Issue by huachuman** [brianpetro/obsidian-smart-connections#804]
If I'm looking for notes similar to the note I'm on, why is the content from the note I'm using as the basis for the search always at the top? Obviously I'm not looking for the same note I'm on. Shouldn't the file being used be left out from the search?

Just because the best match is the same note doesn't mean the same note should litter the search panel, let alone appear in it.

Is this a bug? Is it intended behavior? Am I the only one getting this? I'm not understanding how other people are using this plugin if that's how it behaves.

**Comment by bbecausereasonss** [comment]
Happens once in a while to me, but not every time.

**Comment by brianpetro** [comment]
There is explicit logic to prevent this. If you can identify the circumstances it happens (if not always) that would be helpful in figuring out the bug 🌴
