### ISSUE TITLE
I want to believe but...

### ISSUE THREAD

**Issue by writtenfool** [brianpetro/obsidian-smart-connections#807]
Given this lofty statement: Spend less time linking, tagging and organizing because Smart Connections finds relevant notes so you don't have to!

I am at a complete loss how to use this plugin and I am not stupid. 

SC did the embeddings and I'm left with "what now"? 

I ask a question in the sidebar and I'm directed to the Obsidian console, really?

I'll come back again in several months and see if you have plugin that is understandable. There is a HUGE gap between your tool and how to use it.

**Comment by christianngarcia** [comment]
You might want to check out some of the YouTube videos Brian has created. They can be really helpful & insightful.

https://youtube.com/@wfhbrian?si=lrekB8ArH68dpcLW

**Comment by writtenfool** [comment]
Forgive me, but they are useless. If you folks want to be successful, you need to address how to use software by people that are not as technically literate as you are. I'll come back in a couple of months; looking at the console for clues when you should be more up front and detailed in simple terms how to configure a new plugin in the Obsidian environment. I want to believe, but I don't have time for this. Appreciate the reply.
