### ISSUE TITLE
It's stuck here. It's not moving

### ISSUE THREAD

**Issue by liuling73** [brianpetro/obsidian-smart-connections#808]
![image](https://github.com/user-attachments/assets/8f54dd0b-2559-4612-aea0-1c47b918c068)

The latest version is the same, please help me check, thank you

**Comment by brianpetro** [comment]
Hi @liuling73 

Thanks for bringing this to my attention.

A possible workaround is mentioned in https://github.com/brianpetro/obsidian-smart-connections/issues/797#issuecomment-2377561613

And https://github.com/brianpetro/obsidian-smart-connections/issues/801 is tracking this specific error.

I'm going to close this as a duplicate 🌴
