### ISSUE TITLE
Smart connect plugin seems to see only 10 random notes at the time

### ISSUE THREAD

**Issue by eimantasurbonas** [brianpetro/obsidian-smart-connections#815]
Hey guys,

When using chat (with gemini-flash model  and bge-micro-v2 embedding model) I noticed that gemini was not aware of some parts of context, so I started testing and it seems that Gemini is able to see only 10 notes at once. 

So basically I have here 19 notes as shown in the explorer and in "Smart connections files" I can see them but gemini can see only 10 at once, even when using "Based on my notes" prompt.

How to fix this? Do I need a paid API or to become a supporter or something else? 

This is very frustrating. I tried various models/prompts...

![list](https://github.com/user-attachments/assets/5357a997-061f-4c59-8e5d-beeba74e03a8)
![list2](https://github.com/user-attachments/assets/38a06c7f-565d-4ccf-ba7d-f8c513096cd4)
![chat](https://github.com/user-attachments/assets/e328e3d9-74eb-4014-bddf-211bcdfc37a4)

**Comment by brianpetro** [comment]
Currently there is an arbitrary limit of 10, this is something that will be improved 🌴

**Comment by eimantasurbonas** [comment]
> Currently there is an arbitrary limit of 10, this is something that will be improved 🌴

That's very dissapointing. Is there some sort of workaround atleast for now or some other obsidian plugin?

**Comment by brianpetro** [comment]
Supporters will get early access to the next version of Smart Chat in the near future. Unfortunately the existing version is too cumbersome to build/improve, so I've been working on a rewrite that will allow many improvements.

While I can't recommend alternatives to Smart Connections, primarily because I'm too focused on building what I see as the future of software rather than evaluating alternatives, I'm sure that is something ChatGPT could help you with 😉 🌴

**Comment by eimantasurbonas** [comment]
> Supporters will get early access to the next version of Smart Chat in the near future. Unfortunately the existing version is too cumbersome to build/improve, so I've been working on a rewrite that will allow many improvements.
> 
> While I can't recommend alternatives to Smart Connections, primarily because I'm too focused on building what I see as the future of software rather than evaluating alternatives, I'm sure that is something ChatGPT could help you with 😉 🌴

You mean its possible to build a custom bot in chatgpt and feed a few k of notes into it?

**Comment by brianpetro** [comment]
This GitHub issues section discusses software issues. While I wish I could advise everyone on how to empower themselves with AI, I am doing the best I can by developing open-source tools design for individuals and open-source components that other developers can use to build, too. 

Also, there is no need to full quote my previous message in a one-on-one thread like this. What you're responding to is pretty clear without the quote.

Lastly, there is a link to join our Community Lean Coffee meetings in the Smart Connections settings. Bring your questions, and everyone has a chance to vote on what topics we discuss (next one is tomorrow ☕️)

🌴

**Comment by eimantasurbonas** [comment]
Thanks for information. 

Anyways if you're like me and need a workaround to use AI for all your notes, try Google NotebookLM (supports 50 data sources per notebook, with up to 500k words each and fast AI) or fabric.so.
