### ISSUE TITLE
[2.2.77] no settings shown to choose models or switch to legacy transformers

### ISSUE THREAD

**Issue by alk0** [brianpetro/obsidian-smart-connections#816]
![image](https://github.com/user-attachments/assets/46c5dc5d-17b6-4c75-8d64-f45d726f0696)

![image](https://github.com/user-attachments/assets/78d67b2d-1e02-48c1-a10c-3a4e7f5c3c7a)

**Comment by brianpetro** [comment]
@alk0 do more settings appear when you click the Smart Connections tab in the Obsidian settings again?

Those settings should include the toggle for legacy transformers which should solve that error.

🌴

**Comment by brianpetro** [comment]
THis should be fixed in `2.2.78`, thanks for bringing this issue to my attention 🌴

**Comment by alk0** [comment]
Thanks! Everything is working now on a test vault (not without minor glitches, but working). Will report if any problems occur on a real vault.

**Comment by notuntoward** [comment]
After this update, smart connections finishes its initialization, and I can click the settings button in the smart connections pane.  But I only see a subset of the settings, and not the ones which would allow switching transformers:

# What I see when I click the settings icon

![image](https://github.com/user-attachments/assets/e6dd753b-2ae1-4c73-8174-3d7d6d310bea)

**Comment by alk0** [comment]
> After this update, smart connections finishes its initialization, and I can click the settings button in the smart connections pane. But I only see a subset of the settings, and not the ones which would allow switching transformers:

It may be a bit confusing, having two setting panes. The setting for the legacy transformers is in the "main" plugin settings (<kbd>Ctrl</kbd> + <kbd>,</kbd> or <kbd>Ctrl</kbd> + <kbd>P</kbd>, "Open settings", then scroll down on the left to "Community plugins", "Smart Connections", and _there_ you _should_ see the one you need. You _may_ not see it, if the plugin failed to load properly (or is still loading), but it _should_ not be your case.

![image](https://github.com/user-attachments/assets/85ce3d80-bf78-4f9a-8cbf-e936c67d6238)
