### ISSUE TITLE
Error When Muting Notifications

### ISSUE THREAD

**Issue by SpicyRicecaker** [brianpetro/obsidian-smart-connections#819]
Every time I start up Obsidian, I click the mute button for all notifications, but the notifications kept popping up. Today I decided to take a closer look, and seem to have found the issue: 

## Steps to Reproduce

1. goto `.obsidian/plugins/smart-connects/data.json`
2. ensure "smart_notices" key is missing
3. start up Obsidian
4. wait for notifications to pop up
5. click the mute button for each notification
6. open console (on Windows via ctrl + shift + i)
7. observe the following error: `Uncaught TypeError: Cannot read properties of undefined (reading 'muted')`
![image](https://github.com/user-attachments/assets/a3597be6-b8fb-4c6b-b4eb-3f14fbb397da)
8. restart obsidian, and all notifications should still show up

## Expected Behavior

Muting a notification once should mute the notification permanently. #641 perhaps related. 

## Speculation as to cause

I grepped the repo and noticed that the `data-setting` key for muting notifications was `smart_notices.muted`, see https://github.com/brianpetro/obsidian-smart-connections/blob/841553ae096ff1a9ed546984e611f0898c520d01/src/components/main_settings.js#L187

I'm not sure why but the `"smart_notices"` key seemed to be missing from my `data.json` in `.obsidian/plugins/smart-connects/data.json`, even though I'm pretty sure I didn't modify the file manually at all, and just installed the add-on straight from the obsidian extensions. 

I temporarily fixed the issue by simply adding 
```json
"smart_notices": {
    "muted": {
    }
  }
```
to my `data.json`. Further mutes have permanently muted the notifications. 

Perhaps this is related to https://github.com/brianpetro/obsidian-smart-connections/blob/841553ae096ff1a9ed546984e611f0898c520d01/src/index.js#L478-L483 may be related? The key might've never been initialized in the first place?

**Comment by brianpetro** [comment]
Hi @SpicyRicecaker and thanks for bringing this to my attention. It should be fixed in `v2.2.80` 🌴

**Comment by SpicyRicecaker** [comment]
Thanks!
