### ISSUE TITLE
[UI improvement] a larger text area?

### ISSUE THREAD

**Issue by rotello** [brianpetro/obsidian-smart-connections#82]
I know the most important UI issues has been solved (copy pase .. Yeahhhhh) . 
I am adding a small one - not very urgent - for future record.
in my workflow I keep the Smart connection open on the third column of the page... the "input" window" is super small and i cannot resize it.
<img width="399" alt="Screenshot 2023-03-24 at 08 39 50" src="https://user-images.githubusercontent.com/2255620/227460534-6546c3c6-7e3c-4bc9-abdc-ad184cb5a7b0.png">
The prompting experience is kinda limited. 

If the “text area” could be resizable, or a couple of line higher it would be much better

**Comment by smartguy1196** [comment]
From experience with working with custom text areas in HTML, @brianpetro this will be excessively difficult to implement from scratch.

I'm unsure if Obsidian comes with built-in expandable text areas, but if it doesn't, I heavily recommend using a library for this one.

**Comment by brianpetro** [comment]
@smartguy1196 is that a challenge?

This shouldn't be an issue. Not super high priority, but I'll probably have something that's a sufficient improvement sooner than later @rotello

**Comment by brianpetro** [comment]
Added a little padding to the bottom and made the text area grow up to 50% of the size of the chat view based on the contents of the text area.

**Comment by brianpetro** [comment]
It's the way of the shipper.

How come the name change @pinuke ?

**Comment by brianpetro** [comment]
I am marking this as done. @rotello I hope the update helped!
