### ISSUE TITLE
need help on the prompting - it does not find names

### ISSUE THREAD

**Issue by rotello** [brianpetro/obsidian-smart-connections#83]
The new 1.4.x version is GREAT i can ask stuff and get answer on long forgotten notes. i m excited!

I am facing an issue on ONE single note, 
I ve copied pasted this page ( https://www.grappling-italia.com/approfondimenti/lista-cinture-nere-bjj ) into a note (page is from a website of mine - not copywriting infrangments ) - I ve attached the .md in this message, too.

When i ask if a guy is a black belt - Smart Connection recognize the doc but does not find the name

**Based on your notes, there is no mention of Andrea Baggio being a "cintura nera" in Brazilian Jiu Jitsu in Italy.**
as you can see the name is clear in the note.
<img width="913" alt="Screenshot 2023-03-24 at 09 00 12" src="https://user-images.githubusercontent.com/2255620/227461244-f29ac9b3-802e-49c3-b97e-9b07bb0ad7ec.png">

Before opening this help request I did a test on ChatGPT (free tier):
"i am giving you a list, can you tell me if andrea baggio is a "cintura nera" ?
-- list ---
Yadda yadda yadda copy paste of A-B-C
--- end list

and the reply is:
<img width="567" alt="Screenshot 2023-03-24 at 09 10 32" src="https://user-images.githubusercontent.com/2255620/227462261-536db174-d85e-4897-b9d2-ea50c9a52b53.png">
Yes, Andrea Baggio is a "cintura nera" in Jiu-Jitsu, he received his black belt in 2008 at Milanimal Academy in Milan, Lombardy.

---

I am puzzled. Can someone help with the prompt? 
I attach the .MD of the notes, just in case
[Lista delle Cinture Nere di Brazilian Jiu Jitsu in Italia copy.md](https://github.com/brianpetro/obsidian-smart-connections/files/11059817/Lista.delle.Cinture.Nere.di.Brazilian.Jiu.Jitsu.in.Italia.copy.md)

**Comment by brianpetro** [comment]
This might be more of an issue with how the embeddings are parsed. The issues with this should become evident if you click the center document button on the message and paste the contents to see what context is being used in the prompt. 

There's also the system prompt which hasn't yet been updated since the initial release. This might be updated to instruct the AI to answer even if it is uncertain based on the notes, then it would return the similar response as to ChatGPT in your example. 

Lots of room for improvement. Thanks for sharing this so I can better understand which of those improvements might be best.

**Comment by brianpetro** [comment]
@rotello the ability to query a single note was added in `v1.5.0`.

Use the double bracket link syntax. See this https://twitter.com/wfhbrian/status/1641557902879064065?s=20

Let me know if that fixes this 

🌴

**Comment by rotello** [comment]
the update is coming is the perfect time:
- In italy ChatGPT has been banned for its use of personal data, but API are still working :-)
- I m writing the script for the video about smart connection , and this update solves one of the thorn in the side of the project.

Thanks

**Comment by brianpetro** [comment]
I recommend using the Smart Connect GPT for chats that require keyword search. This feature will be implemented in the Smart Chat in the future 🌴

**Comment by brianpetro** [comment]
Recorded response https://youtu.be/qHTZ4Ph1kI8
