### ISSUE TITLE
"An error occurred. See console logs for details." while running Local Models

### ISSUE THREAD

**Issue by UltraInstinct0x** [brianpetro/obsidian-smart-connections#830]
![image](https://github.com/user-attachments/assets/5d6ce327-4e94-4807-b6c2-57cd1f464878)
![image](https://github.com/user-attachments/assets/b4729484-460e-4f03-8c2b-0a4b1645affa)
![image](https://github.com/user-attachments/assets/09de90f0-d386-42a4-a354-7e974cb1687f)

Pretty simple, it waits for an api key even though I select local model. My configs are fine, code just returns...

**Comment by lstep** [comment]
> ![image](https://private-user-images.githubusercontent.com/63316492/374546108-5d6ce327-4e94-4807-b6c2-57cd1f464878.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NDk5MDcsIm5iZiI6MTcyODU0OTYwNywicGF0aCI6Ii82MzMxNjQ5Mi8zNzQ1NDYxMDgtNWQ2Y2UzMjctNGU5NC00ODA3LWI2YzItNTdjZDFmNDY0ODc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDA4NDAwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiOGVkNTc4NWY2OWU1ZDE4NTQ0M2RhMTFmNjgyYzI4ZDFmNmE5MjI3ZDkzZWI4MmNiZDdiM2UwZTY4NDE0NjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vTnLdWzR9_HDGBH7Id0G0_GSBfQgYueqYoV-cF_uOyI) ![image](https://private-user-images.githubusercontent.com/63316492/374546135-b4729484-460e-4f03-8c2b-0a4b1645affa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NDk5MDcsIm5iZiI6MTcyODU0OTYwNywicGF0aCI6Ii82MzMxNjQ5Mi8zNzQ1NDYxMzUtYjQ3Mjk0ODQtNDYwZS00ZjAzLThjMmItMGE0YjE2NDVhZmZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDA4NDAwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3NTJmYjZiZWIxYTgzOWU3OGJlMmU4ZjQwNzQyNDcyOWQ2NTI5ZTNmYjU4ZmQ3ODkyNTI0MGQ0ZjkwMTI0NWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mMC0A3oUVTzA3UMFCxC7sHVs9_DD3SO1wOGD3SuQtt4) ![image](https://private-user-images.githubusercontent.com/63316492/374546146-09de90f0-d386-42a4-a354-7e974cb1687f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NDk5MDcsIm5iZiI6MTcyODU0OTYwNywicGF0aCI6Ii82MzMxNjQ5Mi8zNzQ1NDYxNDYtMDlkZTkwZjAtZDM4Ni00MmE0LWEzNTQtN2U5NzRjYjE2ODdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDA4NDAwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzNTFhN2IxZjRkMTE3MDdmNDFmMmJlYmYxMDJhNWY0MzVhZWZhZDc1MjMzNGEyMDNiMWY1MTVlZTIyZDk0MDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._xluotZ2T7tqzjxtZT1igiPKsnOqGNLx-Ht1WdbGmME)
> 
> Pretty simple, it waits for an api key even though I select local model. My configs are fine, code just returns...

Shouldn't the url be `/v1/chat/completions`   ?

**Comment by UltraInstinct0x** [comment]
@lstep THIS!!! How could I missed that? Thank you so much, I should sleep more.
