### ISSUE TITLE
Requirement for a WEBGPU although I'm using a remote OLLAMA configuration (`Using Custom Local (OpenAI format)`)

### ISSUE THREAD

**Issue by lstep** [brianpetro/obsidian-smart-connections#832]
Hello, I'm using Smart Connections with a remote OLLAMA instance. I configured it as following:

**Using Custom Local (OpenAI format)**

- model name: qwen2.5:32b-instruct-q4_K_M
- protocol: http
- hostname: [my_ip_address]
- port: 11434
- path: /v1/chat/completions
- streaming: activated 
- max input tokens: 8192

It works fine for general questions:
![image](https://github.com/user-attachments/assets/f56d8391-6713-42f3-b69e-e8c41398d240)

But as soon as I ask a question that requires access to the notes, I get a popup showing an error:

```
According to my notes, what is Pixel's brithday?
````

![image](https://github.com/user-attachments/assets/e09efe75-5aea-4a1d-8f20-0c4c1252a385)

I don't understand why do I get this message, especially because I've configured a remote API query, so why would it ask for a webgpu?

**Comment by OneEyedOwl11** [comment]
have pretty much the same error. On arch linux

**Comment by brianpetro** [comment]
It's because the embedding happens using a different type of model. Try turning on the legacy transformers option in the settings 🌴

**Comment by lstep** [comment]
> It's because the embedding happens using a different type of model. Try turning on the legacy transformers option in the settings 🌴

I already had it checked. But I forced refreshed all (and reimported, using the button just above), and everything went fine! Thanks
