### ISSUE TITLE
No Context Found for rendering Smart Connections

### ISSUE THREAD

**Issue by adrienneteicher** [brianpetro/obsidian-smart-connections#834]
Getting this error message on some notes:

No Context Found for rendering Smart Connections

Been searching but can't find any information about what it means or what to do.

**Comment by Ramadas108** [comment]
Me too! Updated to new version and started to have this problem

**Comment by adeluccar** [comment]
Same.

**Comment by brianpetro** [comment]
It likely means that the notes notes is unembedded. Running the "refresh & make connections" command should fix it if that is the case. 

If it doesn't fix it then there should be an error in the console logs. Screenshot that and I will take a look 🌴

**Comment by adrienneteicher** [comment]
Seems to have worked. Thanks!
