### ISSUE TITLE
No Implement Error show when using a local LLM for RAG prompts

### ISSUE THREAD

**Issue by 3-ark** [brianpetro/obsidian-smart-connections#835]
I am currently using LM Studio, which is OpenAI format, as my backend. This works fine with my settings when it's not note-related.
 P.S. online API works great, only the local doesn't work. logs attached below.
 BTW, every time I startup obsidian the importing process takes much longer time than before, and there is a flash black screen. I don't know if this is another bug, but this doesn't affect much. 
 
![Screenshot 2024-10-12 131238](https://github.com/user-attachments/assets/34a956f7-3646-4fe2-873a-e07e9e1a2776)

**Comment by brianpetro** [comment]
Thanks for the update 🌴
