### ISSUE TITLE
No nodes or links to display after filtering. Aborting update.

### ISSUE THREAD

**Issue by 077531** [brianpetro/obsidian-smart-connections#843]
Hi
I am testing Smart Connections and it seems to work but show this error "error_in_embedding_search"
![Captura desde 2024-10-17 17-12-53](https://github.com/user-attachments/assets/d5da0d06-b555-4290-87d4-b91673e5adf9)

The Visualizer don't show nothing but I have seen it working before update with my other vault, no longer.
The console shows:
![Captura desde 2024-10-17 17-11-58](https://github.com/user-attachments/assets/4a3d8ffa-fa51-42d2-b693-3a7db1344920)

**Comment by Denunziant** [comment]
same thing here, but my smart connections works fine. It's just the error with the vuísualizer.

**Comment by crossways** [comment]
i am running into the sam issue. Smar connections is configured and works well, but the Visualizer is showing me "No nodes or links to display after filtering" as error

**Comment by brianpetro** [comment]
Thanks for the screenshots. Unfortunately, that error looks unrelated to the visualizer. If anyone sees any errors that might be related to the visualizer, screenshot and I will check it out 🌴

**Comment by 077531** [comment]
I remove the error "error_in_embedding_search" clicking in unmute button. I have remove the plugin, for the moment. After that, I come up with my graph view not working. Googling I found in reddit that I could solve it removing GPUcache folder in .config/obsidian. I did it and I think everything works fine. I also updated to last version Smart Connections.

**Comment by crossways** [comment]
@brianpetro  @077531 thanks for the response

@077531 could you share the reddit link. I tried to replicate your steps, but after removing the GPUcache folder the error persisted

**Comment by brianpetro** [comment]
Smart Connections Visualizer should be working since the latest version 1.0.19 🌴

**Comment by crossways** [comment]
Thank you. Just checked and it is indeed working now. Many thanks for this fast fix ))

**Comment by 077531** [comment]
Yes. https://www.reddit.com/r/ObsidianMD/comments/18ecjls/graph_view_suddenly_stopped_working/
Now is working. Thank you very much.
