### ISSUE TITLE
"An error occurred. See console logs for details."

### ISSUE THREAD

**Issue by gnowo** [brianpetro/obsidian-smart-connections#846]
OS: Updated Pop!_OS 22.04 LTS
Terminal: gnome-terminal
CPU: AMD Ryzen 7 7700X  @ 4.500GHz
GPU: NVIDIA GeForce RTX 4070 Ti SUPER
Memory: 32GB DDR5 6000MHz

![Screenshot from 2024-10-21 13-08-15](https://github.com/user-attachments/assets/8424cca0-5be5-46bd-8682-4dd18d90cb1c)

**Comment by gnowo** [comment]
I also should add context that I'm using Firefox and have GPU acceleration enabled (Vulkan)

**Comment by brianpetro** [comment]
Try turning on the legacy transformers option in the settings 🌴

**Comment by gnowo** [comment]
thank you, this worked - but am I not utilizing my GPU for embeddings then?

**Comment by brianpetro** [comment]
Correct, because Obsidian doesn't have GPU flag enabled on Linux 🌴

**Comment by gnowo** [comment]
): okay, well regardless I appreciate you helping me troubleshoot and explaining why it was not working! (: +1:
