### ISSUE TITLE
JSON file (?) error when opening .md file

### ISSUE THREAD

**Issue by notuntoward** [brianpetro/obsidian-smart-connections#858]
When I open today's (nearly empty) daily note, I get the error message below, but I don't know what file to fix, as it's talking about an unnamed JSON file, I think.  The daily note file itself is below the screenshot.  

Any suggestions?

![image](https://github.com/user-attachments/assets/fb4bef6e-a43b-4bc5-b9b3-e74eb0e622d0)

---------------------------------------------------------------------------------------------------------
## The file: 2024-10-29.md

---
created date: 2024-10-29T21:05:58-07:00
modified date: 2024-10-29T21:06:13-07:00
excalidraw-plugin: raw
tags: 
type: daily
---
**[[2024-10-28]]** ←→ **[[2024-10-30]]**

**Comment by brianpetro** [comment]
What makes you think this is related to Smart Connections? 🌴

**Comment by notuntoward** [comment]
Good point.  This appeared immediately after all the other popups I see when smart connections initializes.  But when I disable smart connections, this JSON message still pops up.  I'll look elsewhere now.
