### ISSUE TITLE
Update Embedding model nodes 

### ISSUE THREAD

**Issue by 3-ark** [brianpetro/obsidian-smart-connections#878]
I found the nodes from nomic-AI doesn't work anymore when I was trying to compare with the embedding.

And Xenova/bge-m3 is a better choice now from the same provider of Jina-V2 and bge-small.

**Comment by brianpetro** [comment]
Thanks for letting me know about the updated models. It's a lot to keep track of. 

I'd like to import the models dynamically from hugging face in the future, but I haven't evaluated the feasibility of that yet. 

The underlying embedding component https://github.com/brianpetro/jsbrains/tree/main/smart-embed-model is still being worked on but I will make a note to include the newer models before release 🌴
