### ISSUE TITLE
Unable to use chatgpt models in smart chat conversation view despite valid open api key

### ISSUE THREAD

**Issue by sgsvaya** [brianpetro/obsidian-smart-connections#890]
whenever I enter anything in the prompt, i get: 
*An error occurred. See console logs for details.*

And the console shows this kind of error:
<img width="465" alt="image" src="https://github.com/user-attachments/assets/7a19b644-5696-45c3-af1e-b3a7563c4503">

**Comment by zackheil** [comment]
Read the HTTP error code and the returned error message. 429 means too many requests and the error message starts with "You have exceeded...". What does it say you have exceeded?

**Comment by sgsvaya** [comment]
> Read the HTTP error code and the returned error message. 429 means too many requests and the error message starts with "You have exceeded...". What does it say you have exceeded?

ahh i see -- thanks @zackheil
