### ISSUE TITLE
Smart Connections returns entire embeds

### ISSUE THREAD

**Issue by micaelarealign** [brianpetro/obsidian-smart-connections#900]
Some notes have embeds/transclusions in them, and the results in Smart Connections seems to return the entire embedded note even if it's very long. This makes browsing smart connections very impractical.

**Comment by brianpetro** [comment]
You can turn off markdown rendering in the Smart Connections view settings (see screenshot) 🌴

![Screenshot 2024-12-03 at 10 07 45 AM](https://github.com/user-attachments/assets/40679c79-fee9-4ef6-9463-710f6e9e0039)

**Comment by micaelarealign** [comment]
I suppose that's one way to do it. Not the ideal solution as you lose the markdown. Hope this changes in future versions.

**Comment by brianpetro** [comment]
What would an ideal solution look like? 🌴

**Comment by micaelarealign** [comment]
Maybe some kind of max-heigh for really long results that can then be scrolled or "click to expand" type of thing.

Whatever the solution, if anyone has many embeds, the smart connections in its current iteration are practically unusable.

**Comment by brianpetro** [comment]
The button to the left the of the button labelled "1" in the above screenshot collapses all of the results to should the file name / block-path only 🌴

**Comment by micaelarealign** [comment]
Umm... yes... hiding all results... what kind of answer is that?

**Comment by micaelarealign** [comment]
You pretend like my suggestions don't make sense, treat me as kind of stupid suggesting that I click the button which hides all results. I mean it's kind of disrespectful to treat people like this when they're helping you develop what you're basically turning into a paid product... I am pretty sure other AI plugins will outdo yours if you keep treating reports as carelessly as this.
