### ISSUE TITLE
Unable to install version 2.3.38

### ISSUE THREAD

**Issue by ottantaventi** [brianpetro/obsidian-smart-connections#904]
I tried to update and install to version 2.3.38 from the within the Obsidian community plugin directory:
the plugin downloads but fails to install:

![image](https://github.com/user-attachments/assets/81227c43-d0f8-462d-a4b7-29858906065b)

I've tried it on my work vault (with several plugins) and on my test vault (screenshot) with only 5 notes and 2 plugins (Smart Connections and the SC Visualizer)

I attach the screenshot of the console:
![image](https://github.com/user-attachments/assets/cb58e2eb-0e91-448b-81ed-f5df7452901c)

**Comment by Sedjem** [comment]
I am also experiencing this.

**Comment by brianpetro** [comment]
@ottantaventi @Sedjem `v2.3.38` was skipped due to a bug that I noticed just after the release. 

The latest version is now `v2.3.39`. 

Let me know if updating works for the latest version 🌴

**Comment by Sedjem** [comment]
Working flawlessly, I just picked a bad time to install for the first time XD.

**Comment by ottantaventi** [comment]
Yes, it worked on both my vaults.
Thank you
