### ISSUE TITLE
Smart connections turns up highly irrelevant results 

### ISSUE THREAD

**Issue by micaelarealign** [brianpetro/obsidian-smart-connections#907]
If given the contents of the note, Smart Lookup is MUCH more effective at finding relevant notes than is Smart Connections.

**Comment by brianpetro** [comment]
Turn off `embed blocks` in the settings and you will get the same results in both. Otherwise, Smart Connections shows more granular results ("blocks"). Blocks will be more or less helpful depending on how you format your notes 😊🌴

**Comment by micaelarealign** [comment]
depending on how you format your notes 😊🌴

this is not very helpful. how exactly should one format their notes for this to actually work properly? this should be explained in the UI, not left for people to guess

**Comment by MasseR** [comment]
In case someone stumbles on this later.

Based on the this thread, if you are using a more zettelkasten style approach with short, atomic notes, the blocks can be actively harmful for the results. Disabling the blocks in the settings can drastically improve the results. In my case, I went from "best is 0.45 score" to "best is 0.81 score".

The setting is called "Hide blocks in results".

The blocks are more useful if you have longer form text, long enough to need headings.
