### ISSUE TITLE
Smart chat does not work in multilingual (French)

### ISSUE THREAD

**Issue by mickahouan** [brianpetro/obsidian-smart-connections#91]
Hello,

When I ask questions to Smart chat it only works if I ask it in English.
Example : 

![image](https://user-images.githubusercontent.com/31423109/227720014-c0fb9257-1a51-4e20-becb-26ab23b79f65.png)

Here is the translation of his answer when I ask the question in French : 
I'm sorry, but as an AI, I do not have access to your personal files or records. However, I can give you general advice on copywriting and how to improve your copywriting skills. If you have specific questions about copywriting, feel free to ask.

It works when I ask the exact same question in English: 

![image](https://user-images.githubusercontent.com/31423109/227720141-49fb573e-fec3-4c0e-bc64-99d2ab771c54.png)

I guess it must be the function that asks to use a self-referential pronoun that doesn't work in multilanguage...s).

**Comment by mickahouan** [comment]
my guess was right

![image](https://user-images.githubusercontent.com/31423109/227720764-70a80a09-3055-4704-8452-1bf4f320f360.png)

**Comment by smartguy1196** [comment]
This is being fixed with #85

**Comment by smartguy1196** [comment]
@brianpetro this is a duplicate of #64

**Comment by brianpetro** [comment]
Closing in favor of https://github.com/brianpetro/obsidian-smart-connections/issues/64#issuecomment-1483966383
