### ISSUE TITLE
Add a Warning Callout Re Cost

### ISSUE THREAD

**Issue by ObsidianTTRPGProject** [brianpetro/obsidian-smart-connections#93]
Just something I think people should be pre-warned about in a louder way. The cost of using this can really ramp up quite quickly if you have a large vault. The default limit for ChatGPT max spend per month is $120. I would be warning people that they should review these settings ahead of time so they don't accidentally find themselves facing a potentially large bill. I set mine at $20 for the month and hit that in about 30 minutes. Albeit my vault is rather massive.

**Comment by brianpetro** [comment]
> I set mine at $20 for the month and hit that in about 30 minutes. Albeit my vault is rather massive.

That's quite impressive. My bill for all of last month was ~$3.

There's definitely some room for improvement regarding visibility into costs. Do you have any suggestions?

**Comment by ashishbhateja** [comment]
I'm also curious about what caused such a high bill. Mine's usually only a few cents a day..

**Comment by ObsidianTTRPGProject** [comment]
Managed to hit : $24.51 :D

It's a TTRPG Vault that I've been creating for 10+ years so lots of notes and it was created in a tool called Realm Works so it specialised in creating links... lots and lots of links. If you would like to see how much content... well I made a video a year ago as an example. https://www.youtube.com/watch?v=newKX6mQJ9M&t=2s

I'm not using Obsidian Sync. I sync via Github but I do that manually using Obsidian Desktop every so often. 

I would have a callout in the Read Me advising people of these settings, something along these lines: 

Warning: This plugin sends your data back to OpenAI which utilises credits. The default limit for spending with OpenAI is $120 per month. It is recommended you check these settings and set it to your preferred max monthly limit prior to enabling this plugin. The larger your vault, the more it is going to cost to 'train' the AI 
https://platform.openai.com/account/billing/limits

**Comment by ObsidianTTRPGProject** [comment]
I have no idea if this is even possible. But some kind of training status would be amazing. Something like: X notes processed for example might be able to give people an idea of how many notes have been sent.

**Comment by brianpetro** [comment]
@ObsidianTTRPGProject are you sure that your high bill isn't from this other plugin that's giving you the errors submitted in #99 ?

**Comment by ObsidianTTRPGProject** [comment]
It absolutely got me questioning everything right now. I'll be doing some testing today and get back to you. Apologies for the confusion. I thought I'd turned that one off.

**Comment by brianpetro** [comment]
Closing as platforms are increasing usage visibility 🌴

**Comment by brianpetro** [comment]
Response recording: https://www.youtube.com/watch?v=8r1DRAfq1ec

**Comment by brianpetro** [comment]
Recorded response https://youtu.be/DS5pUHa2UCk
