### ISSUE TITLE
Not able to connect to models after latest update.

### ISSUE THREAD

**Issue by SyndicatedPillbug** [brianpetro/obsidian-smart-connections#932]
Prior to the latest update, my Groq API key worked great. Now it isn't working. Confirmed this by using the exact same settings in a different vault without the latest version and Groq works fine. 

I also can't connect to LM Studio's server anymore.

**OS**
Obsidian 1.7.7
Linux Mint

No Model Selected Error
![image](https://github.com/user-attachments/assets/09c1ec0c-9f57-4b33-ac94-5fe6b3c840fc)

![image](https://github.com/user-attachments/assets/bbb9c6c5-6dba-415c-98d7-5aead820a0fa)

**Comment by SyndicatedPillbug** [comment]
Nothing changes when I try to start a new chat.

**Comment by brianpetro** [comment]
@SyndicatedPillbug I added a Groq adapter in the latest version so you don't have to use the Custom API configuration. Let me know how it works 🌴

**Comment by SyndicatedPillbug** [comment]
Looks like that works now!
