### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by abdcef** [brianpetro/obsidian-smart-connections#94]
If you do not mind, I'd love to see a few bullets to understand what is added in each future release. I saw four updates, wondering what all has happened in the past few hours. You are way ahead of us in anticipating and implementing what we want :)

**Comment by brianpetro** [comment]
Every so often I try to make an announcement that includes notes on all the released features. 

In the meantime, I try to ping relevant people that might beta test the features. 

I've made over a hundred releases, and the time for a few bullet points in that many releases adds up. I know it's unconventional, but my goal is to move fast.

**Comment by abdcef** [comment]
We are not living in conventional times. Up, up and away… 🤣

**Comment by brianpetro** [comment]
Hopefully I'll be able to use this soon https://githubnext.com/projects/copilot-for-pull-requests/

But that's for pulls. Maybe I'll be able to adapt my workflow to use it, though. I'll keep an eye on it!

**Comment by brianpetro** [comment]
@abdcef added a note to the latest release for `v1.5.2`

**Comment by brianpetro** [comment]
Working on it, recent updates should have improved notes 🌴

**Comment by brianpetro** [comment]
Recorded response https://youtu.be/DS5pUHa2UCk
