### ISSUE TITLE
Request - Notes Processed Count

### ISSUE THREAD

**Issue by ObsidianTTRPGProject** [brianpetro/obsidian-smart-connections#97]
It would be very handy to have some sort of indication on how many unique notes have been processed. 

Usage: I very quickly hit my monthly OpenAI cost cap when using this plugin but I am not sure how far through the 'training' that the plugin got. If I was to increase my cap... how much more do I need to increase it by? Am I likely to want to allow the process to complete or is it likely that the cost to train might be too high?

If I knew how many notes had been processed I could complete my own risk analysis so this would be very handy info to have.

**Comment by brianpetro** [comment]
This type of telemetry/visibility would be great. The trade-off is that it adds overhead to creating to new features so that the calculations remains accurate. 

While it will likely be in some time when the feature set is undergoing fewer changes, this is definitely on the roadmap.

**Comment by brianpetro** [comment]
Closing because improved visibility into usage via platforms 🌴
