### ISSUE TITLE
401 Errors

### ISSUE THREAD

**Issue by ObsidianTTRPGProject** [brianpetro/obsidian-smart-connections#99]
Sharing the errors I have been receiving. 
My Console is completely full of these. Its worth noting my vault is huge and has resulted in $25 in API charges so far. My hard cap was $20 so I initially thought the 401 error maybe related to that. Once I hit the cap I increased the limit to $30. Waited about 1 hour and started the plugin again and I am still getting these errors. I have confirmed I can chat with ChatGPT while these errors were being displayed. 

![image](https://user-images.githubusercontent.com/96321415/227772458-374e82e3-2ebf-4983-804b-7aaa2c984519.png)

![image](https://user-images.githubusercontent.com/96321415/227772448-a17f73a9-1596-42e6-aa69-45c66188d217.png)

**Comment by brianpetro** [comment]
Those errors are from a different plugin. If they were from this one, you would see "smart-connections" on the right-hand side of the log.
